### ISSUE TITLE
import-theta error

### ISSUE THREAD

**Issue by stephensammut** [etal/cnvkit#103]
Hi!

I've been trying to import THetA2's results back into cnvkit by using import-theta,  however I consistently get the following error:

cnvkit.py import-theta tumour.cns tumour.BEST.results

**Traceback (most recent call last):
  File "/nfs/users/nfs_s/ss36/software/cnvkit/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/nfs/users/nfs_s/ss36/software/cnvkit/cnvlib/commands.py", line 1654, in _cmd_import_theta
    args.ploidy)):
  File "/nfs/users/nfs_s/ss36/software/cnvkit/cnvlib/commands.py", line 1664, in do_import_theta
    segarr = segarr[~mask_drop].copy()
  File "/nfs/users/nfs_s/ss36/software/cnvkit/cnvlib/gary.py", line 139, in __getitem__
    return self.as_dataframe(self.data[index])
  File "/nfs/users/nfs_s/ss36/lib/python/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 1986, in **getitem**
    return self._getitem_array(key)
  File "/nfs/users/nfs_s/ss36/lib/python/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/core/frame.py", line 2023, in _getitem_array
    (len(key), len(self.index)))
ValueError: Item wrong length 1085 instead of 1086.**

THetA2 files are generated using:

RunTHetA tumour.interval_count \
--TUMOR_FILE  tumour.snps.txt --NORMAL_FILE normal.snps.txt \
--NUM_PROCESSES 20 \
--BAF --FORCE \
--MAX_K 6 

Any help would be greatly appreciated!

Stephen

**Comment by etal** [comment]
I've seen this too, I think -- THetA2 seems to sometimes return 1 segment fewer than it was given, e.g. `tumour.cns` has 1087 lines (1086 segments + a header), but the columns in `tumour.BEST.results` each contain 1084 commas, delimiting 1085 segments. (Could you check and let me know if this doesn't match what you see?)

Which segment was it? If this was an off-by-1 error in THetA2's code, or ending a loop early/incompletely, then I would guess it's the last segment that was dropped. So try deleting the last segment from a copy of `tumour.cns` and trying `import-theta` again. Compare `scatter` or `heatmap` plots of the THetA2-derived .cns files vs. `tumor.cns` to see if they generally match up (good-ish), or appear shifted (it's another segment that was dropped).

If this goes as expected and it looks like an off-by-1 error in THetA2, let's report the bug to https://github.com/raphael-group/THetA.
