### ISSUE TITLE
segmentation error

### ISSUE THREAD

**Issue by dauss75** [etal/cnvkit#111]
Have you seen this problem below?
command: cnvkit.py segment sample.cnr -o sample.cns

Some of the data in sample.cnr:
chromosome	start	end	gene	log2	weight
chr1	14134	14400	DDX11L1	1.40429	0.996255
chr1	14400	14667	DDX11L1	0.753478	1
chr1	14667	14934	DDX11L1	1.10925	1
chr1	14934	15200	DDX11L1	1.32047	0.996255
chr1	15200	15467	DDX11L1	1.39442	1
chr1	15467	15734	DDX11L1	1.21592	1
chr1	15734	16000	DDX11L1	-0.223433	0.996255
chr1	16000	16267	DDX11L1	0.770793	1
chr1	16267	16534	DDX11L1	1.53924	1
chr1	16534	16800	DDX11L1	1.15127	0.996255
chr1	16800	17067	DDX11L1	1.12213	1
chr1	17067	17334	DDX11L1	1.43399	1
chr1	17334	17600	DDX11L1	1.6308	0.996255

--------------------------------------------------------------------------------------------------
sys:1: DtypeWarning: Columns (4,5) have mixed types. Specify dtype option on import or set low_memory=False.

Traceback (most recent call last):
  File "/mnt/galaxyTools/tools/pymodules/python2.7/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/commands.py", line 646, in _cmd_segment
    rlibpath=args.rlibpath)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/segmentation/__init__.py", line 28, in do_segmentation
    filtered_cn = drop_outliers(filtered_cn, 50, skip_outliers)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/segmentation/__init__.py", line 99, in drop_outliers
    for _chrom, subarr in cnarr.by_chromosome()])
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/smoothing.py", line 209, in rolling_outlier_quantile
    dists = np.abs(x - smoothed(x, width))
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/pandas-0.17.1-py2.7-linux-x86_64.egg/pandas/core/ops.py", line 619, in wrapper
    return left._constructor(wrap_results(na_op(lvalues, rvalues)),
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/pandas-0.17.1-py2.7-linux-x86_64.egg/pandas/core/ops.py", line 560, in na_op
    result[mask] = op(x[mask], _values_from_object(y[mask]))
TypeError: unsupported operand type(s) for -: 'str' and 'float'

**Comment by etal** [comment]
I have not seen this, thanks for reporting it. My guess is that the "log2" column somewhere further down the .cnr file contains a value that is not a number.

1. Which version of CNVkit are you using? You can find out with: `cnvkit.py version`. The current version is 0.7.11, so you might try updating and seeing if the error still happens.

2. Could you send me the full .cnr file that causes the error, or a portion of it containing rows that can reproduce the problem?

**Comment by dauss75** [comment]
Thanks for the quick reply. I checked the input file and indeed there was a row containing string at the end of the file. After removing that line, I've got a new error which seems to look for a R script. Am I missing a file?

1. cnvkit.py version
0.7.6.dev0
2. new error 
Traceback (most recent call last):
  File "/mnt/galaxyTools/tools/pymodules/python2.7/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/commands.py", line 646, in _cmd_segment
    rlibpath=args.rlibpath)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/segmentation/__init__.py", line 55, in do_segmentation
    seg_out = ngfrills.call_quiet('Rscript', script_fname)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/ngfrills/__init__.py", line 38, in call_quiet
    + "\n(Original error: %s)" % exc)
RuntimeError: Could not find the executable 'Rscript' -- is it installed correctly?
(Original error: [Errno 2] No such file or directory)

**Comment by etal** [comment]
Cool. Do you know how that last line crept into the .cnr file? Did it come from CNVkit?

The `Rscript` command is a binary that [runs a given R script](http://www.inside-r.org/r-doc/utils/rscript). It doesn't seem to be in your system path, but it's normally part of the default R installation, at least on Linux and R 3.0+. See if you can run `Rscript` independently on the command line, or locate it on your system.

If Rscript is not working out, then you can try the R-free segmentation method "haar" -- it's not CBS, but it does all right:

    cnvkit.py segment sample.cnr -m haar

**Comment by dauss75** [comment]
Thanks again for your help.
I had that line shown below in antitargetcoverage.cnn.
chromosome	start	end	gene	log2
chrM	500	16071	Background	14.382

At the end of .cnr file, the line with background was causing the error. I am not sure when cnvkit introduced this or not.

I forgot to load the R program before running cnvkit. It's been running fine without a problem.

**Comment by etal** [comment]
OK, sounds good. I'm going to close this ticket then, but please let me know if you see the original problem again in a newer version of CNVkit.
