### ISSUE TITLE
ValueError("Unexpected dataframe contents

### ISSUE THREAD

**Issue by jsmedmar** [etal/cnvkit#112]
After running the batch pipeline on many many samples successfully, I decided to rerun it, just to make sure everything was stable. However, I got errors this second time...

The only different thing I did was updating pandas to 0.18.1...

For every single sample I consistently got this:

```
Dropped 4 outlier bins:
  chromosome      start        end  \
0          4  143348454  143348574   
1          7    6798580    6798700   
2          8   61531203   61531323   
3         16   25066262   25066381   

                                                gene       log2    weight  
0  mRNA|BC144255,mRNA|BC110918,mRNA|AK302936,mRNA... -25.662069  0.223140  
1  mRNA|BC157871,mRNA|BC157864,mRNA|AK314983,mRNA... -26.065751  0.193055  
2  ref|NM_001242644,ref|NM_002865,mRNA|AK297576,m... -26.201593  0.158078  
3                                                  - -27.418958  0.122485  
Traceback (most recent call last):
  File "/ifs/work/leukgen/bin/python/.virtualenvs//isabel2/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/cnvlib/commands.py", line 117, in _cmd_batch
    args.diagram, args.rlibpath, args.count_reads))
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/cnvlib/parallel.py", line 14, in apply_async
    func(*args)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/cnvlib/commands.py", line 215, in batch_run_sample
    segments = segmentation.do_segmentation(cnarr, 'cbs', rlibpath=rlibpath)
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 58, in do_segmentation
    segarr = cnarr.as_dataframe(seg2cns(seg_out))
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 135, in seg2cns
    raise ValueError("Unexpected dataframe contents:\n%s" % (seg_text))
ValueError: Unexpected dataframe contents:
Setting R repository:http://cran.case.edu
Loading BiocInstaller:
"sampleName"	"chromosome"	"start"	"end"	"nbrOfLoci"	"mean"
"E-H-103313-T1-1-D1-1"	"1"	10500	3782805	298	0.340627576251594
"E-H-103313-T1-1-D1-1"	"1"	3784516	53716532	5072	0.0331288248008401
"E-H-103313-T1-1-D1-1"	"1"	53720782	121484934	4227	-0.0367209874208655
"E-H-103313-T1-1-D1-1"	"1"	142540785	156908291	1601	0.0656747047026803
"E-H-103313-T1-1-D1-1"	"1"	156909280	210847884	4203	-0.0410670163885313
"E-H-103313-T1-1-D1-1"	"1"	210848384	249240121	2621	0.0259086760001507
"E-H-103313-T1-1-D1-1"	"2"	10500	92325671	5295	-0.00726987730309075
"E-H-103313-T1-1-D1-1"	"2"	95326671	189839376	4729	-0.0253390391289677
"E-H-103313-T1-1-D1-1"	"2"	189842698	189871792	29	-1.15902125499951
"E-H-103313-T1-1-D1-1"	"2"	189872638	243188873	4013	-0.0342393101863894
"E-H-103313-T1-1-D1-1"	"3"	60500	90504354	5524	-0.0301014374223136
"E-H-103313-T1-1-D1-1"	"3"	93505354	197961930	6353	-0.0327268965266186
"E-H-103313-T1-1-D1-1"	"4"	53238	49659617	2382	0.0254564255778723
"E-H-103313-T1-1-D1-1"	"4"	52660617	191043776	6233	0.0154147168579585
"E-H-103313-T1-1-D1-1"	"5"	10500	46303935	1654	-0.070302734249376
"E-H-103313-T1-1-D1-1"	"5"	49406141	180904760	6876	-0.0398048352551686
"E-H-103313-T1-1-D1-1"	"6"	60500	58672748	4322	-0.0139539319580534
"E-H-103313-T1-1-D1-1"	"6"	61880666	171054567	5120	-0.0345586386930428
"E-H-103313-T1-1-D1-1"	"7"	10500	57948900	3253	-0.0885666847645266
"E-H-103313-T1-1-D1-1"	"7"	61054831	159128163	5728	0.0240861286781366
"E-H-103313-T1-1-D1-1"	"8"	10500	39226975	2185	-0.0540343958562078
"E-H-103313-T1-1-D1-1"	"8"	39226975	39335272	10	-1.96420778054534
"E-H-103313-T1-1-D1-1"	"8"	39335772	43838387	356	-0.00538765042475741
"E-H-103313-T1-1-D1-1"	"8"	46839387	146303522	4629	-0.0414362403425111
"E-H-103313-T1-1-D1-1"	"9"	10500	38542656	1720	-0.0215814106423217
"E-H-103313-T1-1-D1-1"	"9"	38543156	47317179	83	-0.291652111312016
"E-H-103313-T1-1-D1-1"	"9"	65468179	141152931	4854	-0.0235521727188082
"E-H-103313-T1-1-D1-1"	"10"	60500	39144330	2050	-0.0459880858711885
"E-H-103313-T1-1-D1-1"	"10"	42450811	135524247	6102	-0.0142980044677472
"E-H-103313-T1-1-D1-1"	"11"	60500	51593705	3916	-0.0191837057206779
"E-H-103313-T1-1-D1-1"	"11"	54808230	134946016	6292	-0.0319081595400695
"E-H-103313-T1-1-D1-1"	"12"	146239	34856194	2693	-0.0230825667529595
"E-H-103313-T1-1-D1-1"	"12"	37857194	133501402	7597	-0.0300647241941196
"E-H-103313-T1-1-D1-1"	"12"	133501902	133841395	44	-0.646720866663907
"E-H-103313-T1-1-D1-1"	"13"	19020500	115109378	4282	-0.0114326450986525
"E-H-103313-T1-1-D1-1"	"14"	19000500	107283180	6115	0.0333248624363718
"E-H-103313-T1-1-D1-1"	"15"	20000500	22211614	28	0.657271346888308
"E-H-103313-T1-1-D1-1"	"15"	22262614	102520892	6231	0.00228834280587174
"E-H-103313-T1-1-D1-1"	"16"	60500	31895192	3202	-0.0541325150572331
"E-H-103313-T1-1-D1-1"	"16"	31897054	35285301	56	0.416530291355946
"E-H-103313-T1-1-D1-1"	"16"	46386301	90294253	3519	-0.0202177087678559
"E-H-103313-T1-1-D1-1"	"17"	6006	22262506	2434	0.0109241624432036
"E-H-103313-T1-1-D1-1"	"17"	25263506	81194710	6446	0.0338968167195099
"E-H-103313-T1-1-D1-1"	"18"	10500	15410398	832	-0.0084063083061765
"E-H-103313-T1-1-D1-1"	"18"	18511398	78016748	2670	0.00989339540146838
"E-H-103313-T1-1-D1-1"	"19"	60500	8495818	1772	-0.136082387087422
"E-H-103313-T1-1-D1-1"	"19"	8496318	24631282	2334	0.0257658280978688
"E-H-103313-T1-1-D1-1"	"19"	27732282	59118483	4315	-0.0134090212235763
"E-H-103313-T1-1-D1-1"	"20"	60500	26319069	1532	-0.0245614048453059
"E-H-103313-T1-1-D1-1"	"20"	29420069	62965020	3128	-0.0484434084897423
"E-H-103313-T1-1-D1-1"	"21"	9411693	11098783	25	0.913912142838144
"E-H-103313-T1-1-D1-1"	"21"	14338629	45857094	1784	0.0295445663483426
"E-H-103313-T1-1-D1-1"	"21"	45858966	46191415	49	0.709489459579069
"E-H-103313-T1-1-D1-1"	"21"	46193488	48119395	333	-0.0147641622896188
"E-H-103313-T1-1-D1-1"	"22"	16050500	51244066	3739	0.0240616121097883
"E-H-103313-T1-1-D1-1"	"X"	60500	58474126	2876	0.0356916063529684
"E-H-103313-T1-1-D1-1"	"X"	61879584	151562076	3713	0.0206345079188955
"E-H-103313-T1-1-D1-1"	"X"	151562898	155260060	359	0.190246973563428
"E-H-103313-T1-1-D1-1"	"Y"	2654933	14832016	163	-5.78693459345312
"E-H-103313-T1-1-D1-1"	"Y"	14832516	15481243	94	-16.1545237846237
"E-H-103313-T1-1-D1-1"	"Y"	15481743	28818861	226	-6.83320408512754
"E-H-103313-T1-1-D1-1"	"Y"	58819861	59033549	2	-0.520025542573895

```

**Comment by etal** [comment]
The problem is that R is now injecting a couple of its own log/status messages into the R script's output, which would otherwise be SEG format starting at `"sampleName"`. You might have something happening in your R startup routine, e.g. you've configured it to automatically load Bioconductor and set your preferred CRAN mirror. Can you disable those? (And/or, suggest how I can tell `Rscript` to prevent those messages from entering standard output?)

**Comment by jsmedmar** [comment]
I think that you can use `Rscript --vanilla`, from the help:

```
  --vanilla         Combine --no-save, --no-restore, --no-site-file
                    --no-init-file and --no-environ
```

Do you know how can I disable autoloading Bioconductor? I have no idea why that started happening...

**Comment by etal** [comment]
I just added the `--vanilla` flag, thanks for the suggestion. Maybe that will disable the Bioconductor message too. Could you pull the latest and try it again?

**Comment by jsmedmar** [comment]
It disables the message, I tried before commenting. I'm now testing the latest commit, I'll let you know. I was having another error, but I think it has to do with my bioconductor installation:

```
Bioconductor version 3.2 (BiocInstaller 1.20.3), ?biocLite for help
Error : .onAttach failed in attachNamespace() for 'BiocInstaller', details:
  call: if (IS_END_OF_LIFE) {
  error: argument is of length zero
In addition: Warning message:
In read.dcf(conn) : unable to connect to 'bioconductor.org' on port 80.
Error: package or namespace load failed for ‘BiocInstaller’
Execution halted
```

So I reinstalled it and I'm about to test again.

**Comment by jsmedmar** [comment]
Ok @etal, we are good now!

**Comment by etal** [comment]
Awesome.

**Comment by cutsort** [comment]
`Rscript --vanilla` breaks compatibility with [packrat](https://rstudio.github.io/packrat/) which relies on the following .Rprofile

```
#### -- Packrat Autoloader (version 0.4.8-1) -- ####
source("packrat/init.R")
#### -- End Packrat Autoloader -- ####
```

`test/` directory completes fine without the `--vanilla` flag.  Safe to remove it?

**Comment by etal** [comment]
@cutsort If you installed CNVkit from source, you can remove the `--vanilla` flag from your installation (in `cnvlib/segmentation/__init__.py`) and if that works for you now, it most likely won't hurt anything. If the R subprocess crashes, you'll know.

The recommended way to install CNVkit is through `conda`, where both R and Python dependencies are managed in an isolated environment. If packrat is not compatible with that setup, then (a) :thinking: (b) that's unfortunate, but most DIY installations do not involve packrat, and hopefully the number that do will decrease to zero over time.

**Comment by etal** [comment]
@cutsort I think the option `cnvkit.py segment --rlibpath=...` will do what you want. Give it the path to your CNVkit-specific R library installation, and it will load the packages from there instead of your default global/user-wide installation.
