### ISSUE TITLE
AssertionError in "diagram" with WGS-level gene density

### ISSUE THREAD

**Issue by mjafin** [etal/cnvkit#12]
Hi there,
Thanks for cnvkit, what a great tool!
I've come across this error:

```
Relative log2 coverage of X chromosome: -0.820871 (assuming male)
Traceback (most recent call last):
 File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/bin/cnvkit.py", line 9, in <module>
   args.func(args)
 File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 685, in _cmd_diagram
   args.output, args.male_reference)
 File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/diagram.py", line 48, in create_diagram
   probe_rows = probe_rows.squash_genes()
 File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/cnarray.py", line 532, in squash_genes
   outrows.append(squash_rows(name, subarr))
 File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/cnarray.py", line 513, in squash_rows
   chrom = core.check_unique(rows['chromosome'], 'chromosome')
 File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/core.py", line 154, in check_unique
   % (title, ' '.join(map(str, sorted(its)))))
AssertionError: Inconsistent chromosome keys: chr11_gl000202_random chr17_ctg5_hap1 chr17_gl000203_random
```

I think the error is caused by the gene column containing a dot ( `.` ) as these contigs have no annotated genes.

**Comment by mjafin** [comment]
There's another issue I could use help with in plotting,:
```
Traceback (most recent call last):
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 685, in _cmd_diagram
    cnarr = CNA.read(args.filename) if args.filename else None
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/diagram.py", line 70, in create_diagram
    drawing = build_chrom_diagram(features, chrom_sizes, probe_pset.sample_id)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/diagram.py", line 116, in build_chrom_diagram
    return bc_organism_draw(chr_diagram, title)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/diagram.py", line 163, in bc_organism_draw
    sub_component.draw(cur_drawing)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/Bio/Graphics/BasicChromosome.py", line 281, in draw
    sub_component.draw(cur_drawing)
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/Bio/Graphics/BasicChromosome.py", line 426, in draw
    self._overdraw_subcomponents(cur_drawing)  # Anything on top
  File "/group/ngs/src/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/Bio/Graphics/BasicChromosome.py", line 680, in _overdraw_subcomponents
    assert 0 <= start <= end <= self.bp_length
```

**Comment by etal** [comment]
I merged a pull request that should fix this. Can you try it now?

**Comment by mjafin** [comment]
@etal thanks, I managed to circumvent the initial problem but the second one above still bugs me. Is it maybe because it's a whole genome analysis and I'm trying to include the cnr file in the diagram command and it gets too crowded? Without the cnr file the diagram gets produced fine (but without gene labels)

**Comment by etal** [comment]
Do the alternative contigs in the .cnr file (chr11_gl000202_random, chr17_ctg5_hap1, chr17_gl000203_random) also appear in the .cns file? I'm guessing they don't, any in any case those contigs probably don't have usable copy number information on them. Can you try deleting those rows (i.e. those contigs) from the .cnr file and retrying the plots?

**Comment by mjafin** [comment]
I removed all the alternative contigs prior to getting the second error. Thanks for looking into this, again. I'll do some more testing tomorrow if it's something to do with the fact that we have sometimes overlapping genes on one row as comma separated lists.

**Comment by etal** [comment]
Sorry, I misunderstood what you did. If this is whole-genome data, then it could be an overcrowding issue where a feature gets squeezed to a size of less than a pixel. What averge bin size did you use to split the "targets" for your WGS dataset?

**Comment by mjafin** [comment]
Hi @etal, I was calling cnvkit from within bcbio and it uses the following settings:
```
--antitarget-avg-size 1000 --antitarget-min-size 75 --target-avg-size 1000
```

**Comment by etal** [comment]
I haven't seen this error in a while, and testing with a WGS-density snippet of chr17 works fine for me. Maybe something was fixed in CNVkit or Reportlab in the interim. But please reopen if you see it again.
