### ISSUE TITLE
Run cnvkit bacth 

### ISSUE THREAD

**Issue by OrsonMM** [etal/cnvkit#136]
Hi. 

I have these error: 

for command: cnvkit.py batch MN12.bam -n -t TruSeq_exome_targeted_regions.hg19.bed -f hg19.fasta --access data/access-5k-mappable.hg19.bed --output-reference my_flat_reference.cnn -d example/

Calculating GC and RepeatMasker content in hg19/hg19_cut.fasta ...
Extracting sequences from chromosome chr1
Extracting sequences from chromosome chr2
Extracting sequences from chromosome chr3
Extracting sequences from chromosome chr4
Extracting sequences from chromosome chr5
Traceback (most recent call last):
  File "./cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/orson/cnvkit/cnvlib/commands.py", line 97, in _cmd_batch
    args.count_reads, args.method)
  File "/home/orson/cnvkit/cnvlib/commands.py", line 193, in batch_make_reference
    male_reference)
  File "/home/orson/cnvkit/cnvlib/commands.py", line 596, in do_reference_flat
    gc, rmask = reference.get_fasta_stats(ref_probes, fa_fname)
  File "/home/orson/cnvkit/cnvlib/reference.py", line 215, in get_fasta_stats
    fa_coords)]
  File "/home/orson/cnvkit/cnvlib/ngfrills/faidx.py", line 20, in fasta_extract_regions
    yield fa_file[_chrom][start:end]
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 557, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 691, in get_seq
    return self.faidx.fetch(name, start, end)
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 435, in fetch
    seq = self.from_file(name, start, end)
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 466, in from_file
    self.file.seek(bstart)
IOError: [Errno 22] Invalid argument

**Comment by etal** [comment]
The error message here is coming from inside the pyfaidx package (paging @mdshw5), which is separate from CNVkit.

Just a guess, but maybe the .fai file is corrupted or otherwise does not match the .fasta file -- could you try rebuilding the fasta index with `samtools faidx hg19.fasta`?

**Comment by mdshw5** [comment]
This is certainly a strange error. The `bstart` value is calculated from a few other objects that are all `int` types. I think that your .fai file has corrupt values such that `bstart` becomes an invalid negative integer value:

```python
>>> x = open('/tmp/test', 'wb')
>>> x.seek(0)
>>> x.seek(10)
>>> x.seek(-10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 22] Invalid argument
```
It's definitely not an informative error and I should probably handle it better by warning the user of the cause and give some context about how to fix it. Thanks for letting me know, @etal.
