### ISSUE TITLE
ValueError: All numbers are identical in mannwhitneyu

### ISSUE THREAD

**Issue by rienix** [etal/cnvkit#144]
Hi Etal,

just for your information: I encountered the error below after upgrading to version 0.8 . In version 0.7.11 everything works fine again.

Loading /media/SingleWorkingDisk2/rebecca/dev_cli_ecnv/cnvkit_results_8048_sample1/KIRP_F1N_L2.antitargetcoverage.cnn
Calculating GC and RepeatMasker content in /media/SingleWorkingDisk2/rebecca/data/dataSets/references/Broad/ucsc.hg19.fasta ...
Extracting sequences from chromosome chr1
...
Extracting sequences from chromosome chr22
Extracting sequences from chromosome chrX
Extracting sequences from chromosome chrY
Traceback (most recent call last):
  File "/home/rebecca/code/dev/.venv/cli_adtex/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/cnvlib/commands.py", line 97, in _cmd_batch
    args.count_reads, args.method)
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/cnvlib/commands.py", line 219, in batch_make_reference
    do_edge=(method == "hybrid"), do_rmask=True)
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/cnvlib/commands.py", line 575, in do_reference
    do_gc, False, do_rmask))
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/cnvlib/reference.py", line 120, in combine_probes
    all_coverages = [flat_coverage, bias_correct_coverage(cnarr1)]
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/cnvlib/reference.py", line 99, in bias_correct_coverage
    shift_sex_chroms(cnarr)
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/cnvlib/reference.py", line 86, in shift_sex_chroms
    is_sample_female = cnarr.guess_xx()
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/cnvlib/cnary.py", line 197, in guess_xx
    is_xy, stats = self.compare_sex_chromosomes(male_reference)
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/cnvlib/cnary.py", line 238, in compare_sex_chromosomes
    female_chrx_u = mannwhitneyu(auto_l, chrx_l)[0]
  File "/home/rebecca/code/dev/.venv/cli_adtex/local/lib/python2.7/site-packages/scipy/stats/stats.py", line 4672, in mannwhitneyu
    raise ValueError('All numbers are identical in mannwhitneyu')
ValueError: All numbers are identical in mannwhitneyu

Btw: Thanks for this great tool and support!

**Comment by etal** [comment]
Thanks for letting me know! I'll see about improving the handling of this case.

The failed comparison was between the off-target read depths of chromosome X versus the autosomes in your sample when evaluating the sample for inclusion in a pooled reference. If your sequencing protocol was target amplicon capture (`batch --method amplicon`) instead of hybrid capture (`--method hybrid`, the default), then these depths would all be 0, triggering the error. If that's the case, in CNVkit 0.8 try the `batch` option `-m amplicon` and that should avoid the error.
