### ISSUE TITLE
Error using cnvkit.py coverage

### ISSUE THREAD

**Issue by murphycj** [etal/cnvkit#147]
Using CNVKit 0.8.1 on python 2.7.8. The command I run:

```
cnvkit.py coverage -q 30 -p 4 ~/chm2059/elementoCantley_2014_9_29/results/WEX/BWAGATK/HL-WES-01/HL-WES-01.gatk.bam /home/chm2059/chm2059/data/refdata/GRCm38/cnvkit/my_targets.bed -o test.cnn
```

The error I get

```
Processing reads in HL-WES-01.gatk.bam
Traceback (most recent call last):
  File "/zenodotus/dat02/elemento_lab_scratch/oelab_scratch_scratch007/chm2059/lib/python2.7.8/bin/cnvkit.py", line 13, in <module>
args.func(args)
  File "/zenodotus/dat02/elemento_lab_scratch/oelab_scratch_scratch007/chm2059/lib/python2.7.8/lib/python2.7/site-packages/cnvlib/commands.py", line 498, in _cmd_coverage
pset = do_coverage(args.interval, args.bam_file, args.count, args.min_mapq, args.processes)
  File "/zenodotus/dat02/elemento_lab_scratch/oelab_scratch_scratch007/chm2059/lib/python2.7.8/lib/python2.7/site-packages/cnvlib/commands.py", line 522, in do_coverage
min_mapq, processes)
  File "/zenodotus/dat02/elemento_lab_scratch/oelab_scratch_scratch007/chm2059/lib/python2.7.8/lib/python2.7/site-packages/cnvlib/coverage.py", line 42, in interval_coverages
read_counts, cna_rows = list(zip(*list(results)))
  File "/zenodotus/dat02/elemento_lab_scratch/oelab_scratch_scratch007/chm2059/lib/python2.7.8/lib/python2.7/site-packages/cnvlib/coverage.py", line 172, in interval_coverages_pileup
for bed_chunk_fname, biter in pool.map(_bedcov, args_iter):
  File "/zenodotus/dat02/elemento_lab_scratch/oelab_scratch_scratch007/chm2059/lib/python2.7.8/lib/python2.7/site-packages/concurrent/futures/_base.py", line 581, in result_iterator
yield future.result()
  File "/zenodotus/dat02/elemento_lab_scratch/oelab_scratch_scratch007/chm2059/lib/python2.7.8/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
return self.__get_result()
  File "/zenodotus/dat02/elemento_lab_scratch/oelab_scratch_scratch007/chm2059/lib/python2.7.8/lib/python2.7/site-packages/concurrent/futures/_base.py", line 357, in __get_result
raise type(self._exception), self._exception, self._traceback
TypeError: Expected bytes, got newts
```

But I get no error if I remove the -q 30 flag

**Comment by etal** [comment]
Thanks for reporting this error, I'll look into it.

In my own benchmarking and in papers describing other CNV callers, filtering reads by mapping quality score did not improve results -- the ambiguously mapped reads still provide useful copy number information, in contrast to standard practice for SNV callers.

**Comment by murphycj** [comment]
Thanks. Yeah I think for datasets with good quality reads I can see mapping quality filtering not making much of a difference. But I've got a few normal control samples that have some issues. But maybe you're right. I'll being doing some parameter testing, we'll see...

**Comment by etal** [comment]
I cannot find any mention of "newts" in pysam, samtools, htslib, multiprocessing or concurrent.futures. But it could be related to this bug: pysam/issues#197

Which version of pysam are you using? If it's not the latest, could you update and see if the error still appears?

**Comment by murphycj** [comment]
Pysam version 0.9.1.4
