### ISSUE TITLE
cnvkit export to theta:

### ISSUE THREAD

**Issue by ramaniak** [etal/cnvkit#153]
Hello Eric,
I am running cnvkit under python/2.7.9 and R/3.2.2 with the following command
```
cnvkit.py export theta ../CNVKit/cnr/A3/A3.cns --reference ../CNVKit/reference/Reference.cnn -v ../muse/results/A3/A3.MuSE.vcf -i TUMOR -n NORMAL 
```
and get the following error:

```
Warning message:
In local({ : bytecode version mismatch; using eval
Error in objects(db.pos, all.names = TRUE) : 
  3 arguments passed to .Internal(ls) which requires 2
Second positional argument normal_reference is deprecated; use --reference instead.
Wrote A3.interval_count
Selected test sample TUMOR and control sample NORMAL
Skipped records: 26 somatic, 9 depth, 0 homozygous
Traceback (most recent call last):
  File "/hpf/tools/centos6/python/2.7.9/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.7.11', 'cnvkit.py')
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg/pkg_resources/__init__.py", line 723, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg/pkg_resources/__init__.py", line 1643, in run_script
    exec(script_code, namespace, namespace)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/CNVkit-0.7.11-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 11, in <module>
    
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 1829, in _cmd_export_theta
    
  File "build/bdist.linux-x86_64/egg/cnvlib/export.py", line 467, in export_theta_snps
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/pandas-0.19.0rc1-py2.7-linux-x86_64.egg/pandas/core/indexing.py", line 1662, in __getitem__
    return self.obj.get_value(*key, takeable=self._takeable)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/pandas-0.19.0rc1-py2.7-linux-x86_64.egg/pandas/core/series.py", line 918, in get_value
    return _maybe_box_datetimelike(self._values[label])
IndexError: index 0 is out of bounds for axis 0 with size 0
```
As you can see the the interval_count file is generated but there is an IndexError that is being thrown. I am not sure if it is actually considering the vcf file or not. Is this something you have come across before?

thanks
Arun

**Comment by etal** [comment]
It looks like there is some text missing from the traceback, but CNVkit did read your VCF file and then failed at the next step. Could you try again with the latest CNVkit version 0.8.1, where VCF processing has some more safety checks built in?

**Comment by ramaniak** [comment]
Hello Eric,
Thanks for getting back. I updated to 0.8.1 and re-tried and still get the same errors:

```
cnvkit.py export theta ../CNVKit/cnr/A3/A3.cns --reference ../CNVKit/reference/Reference.cnn -v ../muse/results/A3/A3.MuSE.vcf -i TUMOR -n NORMAL
Warning message:
In local({ : bytecode version mismatch; using eval
Error in nchar(.Library.site) : 
  4 arguments passed to .Internal(nchar) which requires 3
Error in .Internal(getOption(x)) : 
  there is no .Internal function 'getOption'
Error in .Internal(getOption(x)) : 
  there is no .Internal function 'getOption'
Wrote A3.interval_count
Loaded 0 records; skipped: 26 somatic, 9 depth
Selected test sample TUMOR and control sample NORMAL
Traceback (most recent call last):
  File "/hpf/tools/centos6/python/2.7.9/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.8.1', 'cnvkit.py')
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg/pkg_resources/__init__.py", line 723, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg/pkg_resources/__init__.py", line 1643, in run_script
    exec(script_code, namespace, namespace)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 13, in <module>
    
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 1914, in _cmd_export_theta
    
  File "build/bdist.linux-x86_64/egg/cnvlib/export.py", line 462, in export_theta_snps
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/pandas-0.19.0rc1-py2.7-linux-x86_64.egg/pandas/core/indexing.py", line 1662, in __getitem__
    return self.obj.get_value(*key, takeable=self._takeable)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/pandas-0.19.0rc1-py2.7-linux-x86_64.egg/pandas/core/series.py", line 918, in get_value
    return _maybe_box_datetimelike(self._values[label])
IndexError: index 0 is out of bounds for axis 0 with size 0
```
I was incorrect in my previous reporting. It is indeed reading the vcf but seems to be skipping most of them?

**Comment by etal** [comment]
Yeah, it looks like CNVkit does not see any of the VCF records as usable, so the first operation that requires the dataset to be non-empty crashes. Could you tell me how you generated this VCF, and maybe send me the VCF header and the first non-somatic record? (Or the whole thing is also fine, if you're able.)

Note: This operation is intended to drop somatic records and keep only the germline SNPs identified from tumor-normal paired calling, so if your VCF is filtered to contain only somatic SNVs, it can't be used with THetA2. In that case you can just drop the `-v` option, or look for an unfiltered version of the VCF.

**Comment by ramaniak** [comment]
Hi Eric,
I have tested this with vcfs from multiple sources and I am attaching the
output from mutect2, which also fails in an identical fashion.

Thanks for looking into it
Arun

**Comment by etal** [comment]
I didn't get your VCF attachment, could you re-send it?

**Comment by ramaniak** [comment]
Hello Eric,
I have attached the vcf. Please let me know if you got it this time

Arun

**Comment by etal** [comment]
No, I think GitHub is scrubbing the attachment. Send it to: etal@uga.edu

**Comment by etal** [comment]
Got it, thanks.

**Comment by etal** [comment]
Got it, thanks.

**Comment by etal** [comment]
I've updated CNVkit's VCF reader to correctly extract depths from your Mutect2 output. Now I see another problem: the genotypes listed for the tumor sample look reasonable, but the the normal sample all genotypes are 0, i.e. not present in that sample. (CNVkit will filter these out.) Does Mutect2 always mark the normal sample as 0, even if the variant is germline, or did you already filter out germline calls from this VCF?

**Comment by biowang** [comment]
i run the theta use the results of theta , got following error:

`(cnvkit_env)[liangliang@DN02 theta]$ /nextcode/nfs_test/users/llwang_prod/install/THetA-master/bin/RunTHetA \
>   WGC079129U_sorted_dedup.interval_count \
>   --TUMOR_FILE  WGC079129U_sorted_dedup.tumor.snp_formatted.txt \
>   --NORMAL_FILE WGC079129U_sorted_dedup.normal.snp_formatted.txt \
>   --BAF --NUM_PROCESSES 8 --FORCE
=================================================
Arguments are:
	Query File: WGC079129U_sorted_dedup.interval_count
	k: 3
	tau: 2
	Output Directory: ./
	Output Prefix: WGC079129U_sorted_dedup
	Num Processes: 8
	Graph extension: .pdf
	Force: True
	 Tumor SNP File Location:  WGC079129U_sorted_dedup.tumor.snp_formatted.txt
	 Normal SNP File Location:  WGC079129U_sorted_dedup.normal.snp_formatted.txt

Valid sample for THetA analysis:
	Ratio Deviation: 0.1
	Min Fraction of Genome Aberrated: 0.05
	Program WILL cluster intervals.
=================================================
Reading in query file...
Frac with potential copy numbers: 0.588455779993
Reading SNP file at WGC079129U_sorted_dedup.tumor.snp_formatted.txt
Reading SNP file at WGC079129U_sorted_dedup.normal.snp_formatted.txt
Reading interval file at WGC079129U_sorted_dedup.interval_count
Calculating BAFs
Determining heterozygosity.
Calculating BAFs.
Traceback (most recent call last):
  File "/nextcode/nfs_test/users/llwang_prod/install/THetA-master/bin/../python/RunTHetA.py", line 504, in <module>
    main()
  File "/nextcode/nfs_test/users/llwang_prod/install/THetA-master/bin/../python/RunTHetA.py", line 282, in main
    resultsfile2, boundsfile2 = run_fixed_N(2, args, intervals)
  File "/nextcode/nfs_test/users/llwang_prod/install/THetA-master/bin/../python/RunTHetA.py", line 316, in run_fixed_N
    intervals, missingData, corrRatio, meanBAFs = get_clustering_args(tumorfile, normalfile, filename, num_processes, m, tumorCounts, normCounts)
  File "/nextcode/nfs_test/users/llwang_prod/install/THetA-master/bin/../python/RunTHetA.py", line 263, in get_clustering_args
    intervalsByChrm[chrm].append(interval)
IndexError: list index out of range
`

**Comment by biowang** [comment]
and you example parameter is different

--TUMOR_FILE not --TUMOR_SNP

**Comment by etal** [comment]
That traceback looks like a bug in [THetA2](https://github.com/raphael-group/THetA), perhaps failing to handle a non-canonical or mitochondrial chromosome. Pinging: @raphael-group @gsatas @loesper

**Comment by biowang** [comment]
Thank you for the help.
I read the example of the theta2, it drop the chrom X and Y . so , I delete chroms 23 and 24 in the files to be used by theta2. then the command  theta sucessfully run.
but then I must delete XY record in cns file.
so there is no XY segments results.

`(cnvkit_env)[liangliang@DN02 theta]$ cnvkit.py  import-theta WGC079129U_sorted_dedup.bam.cns WGC079129U_sorted_dedup.BEST.results 
Traceback (most recent call last):
  File "/nextcode/nfs_test/users/mengxin/envs/cnvkit_env/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/nextcode/nfs_test/users/mengxin/envs/cnvkit_env/lib/python2.7/site-packages/cnvlib/commands.py", line 1654, in _cmd_import_theta
    args.ploidy)):
  File "/nextcode/nfs_test/users/mengxin/envs/cnvkit_env/lib/python2.7/site-packages/cnvlib/commands.py", line 1664, in do_import_theta
    segarr = segarr[~mask_drop].copy()
  File "/nextcode/nfs_test/users/mengxin/envs/cnvkit_env/lib/python2.7/site-packages/cnvlib/gary.py", line 139, in __getitem__
    return self.as_dataframe(self.data[index])
  File "/nextcode/nfs_test/users/mengxin/envs/cnvkit_env/lib/python2.7/site-packages/pandas/core/frame.py", line 1991, in __getitem__
    return self._getitem_array(key)
  File "/nextcode/nfs_test/users/mengxin/envs/cnvkit_env/lib/python2.7/site-packages/pandas/core/frame.py", line 2028, in _getitem_array
    (len(key), len(self.index)))
ValueError: Item wrong length 572 instead of 593.
`
