### ISSUE TITLE
call error using vcf

### ISSUE THREAD

**Issue by dwaggott** [etal/cnvkit#159]
I'm running into this error when trying to add a vcf to a `call` command. Notably, the vcf is a gatk gvcf. I pulled out the line it doesn't like, see below. Looks like AS_RAW_MQ INFO tag.

```
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/dwaggott/apps/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 810, in _cmd_call
    if args.vcf else None)
  File "/home/dwaggott/apps/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/__init__.py", line 78, in read
    dframe = reader(infile, **kwargs)
  File "/home/dwaggott/apps/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 25, in read_vcf
    sid, nid, dframe = next(results)
  File "/home/dwaggott/apps/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/tabio/vcfio.py", line 60, in parse_vcf
    records = list(vcf_reader)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/vcf/parser.py", line 572, in next
    info = self._parse_info(row[7])
  File "/home/dwaggott/.local/lib/python2.7/site-packages/vcf/parser.py", line 397, in _parse_info
    val = self._map(float, vals)
  File "/home/dwaggott/.local/lib/python2.7/site-packages/vcf/parser.py", line 360, in _map
    for x in iterable]
ValueError: invalid literal for float(): 0.00|1634.00|0.00
```

```
$ fgrep '0.00|1634.00|0.00'  04_73.g.vcf
20      29588980        .       T       A,<NON_REF>     108.18  .       AS_RAW_BaseQRankSum=|20,2,37,1|;AS_RAW_MQ=0.00|1634.00|0.00;AS_RAW_MQRankSum=|23,2,24,1|;AS_RAW_ReadPosRankSum=|6,1,22,1,42,1|;AS_SB_TABLE=0,0|2,1|0,0;DP=3;ExcessHet=3.0103;MLEAC=2,0;MLEAF=1.00,0.00;RAW_MQ=1634.00 GT:AD:GQ:PGT:PID:PL:SB  1/1:0,3,0:9:0|1:29588972_C_T:135,9,0,135,9,135:0,0,2,1
20      29588984        .       G       A,<NON_REF>     95.03   .       AS_RAW_BaseQRankSum=|20,2,37,1|;AS_RAW_MQ=0.00|1634.00|0.00;AS_RAW_MQRankSum=|23,2,24,1|;AS_RAW_ReadPosRankSum=|10,1,18,1,38,1|;AS_SB_TABLE=0,0|2,1|0,0;DP=3;ExcessHet=3.0103;MLEAC=1,0;MLEAF=0.500,0.00;RAW_MQ=1634.00       GT:AD:GQ:PGT:PID:PL:SB  0/1:0,3,0:13:0|1:29588972_C_T:123,0,13,126,22,148:0,0,2,1
```

**Comment by etal** [comment]
It looks like the failure is within PyVCF. Which versions of PyVCF and GATK are you using?

**Comment by etal** [comment]
Could you post the VCF header here, or send it to me?

**Comment by dwaggott** [comment]
https://gist.github.com/1d36e77a1f87ec3d7c525e3ee7a8ae00

**Comment by etal** [comment]
Thanks. It looks like PyVCF simply doesn't handle this INFO field. But pysam does, so I'll look into using pysam as the VCF parser in the next version of CNVkit.
