### ISSUE TITLE
Cannot allocate memory during segmentation

### ISSUE THREAD

**Issue by chapmanb** [etal/cnvkit#162]
Eric;
I'm running segmentation on a whole genome sample and running into R memory issues on a pretty large AWS machine (m4.4xlarge with 16 cores and 64Gb of memory). It's not an especially helpful message (Cannot allocate memory) but I've pasted the full traceback/log below. segment is called with this command:
```
/mnt/work/bcbio/anaconda/bin/cnvkit.py segment -o /mnt/work/NA12878-hg38-val/work/structural/NA12878-1/cnvkit/raw/tx/tmpmK4z2e/NA12878-1-sort-flatbackground.cns /mnt/work/NA12878-hg38-val/work/structural/NA12878-1/cnvkit/raw/NA12878-1-sort-flatbackground.cnr -v /mnt/work/NA12878-hg38-val/work/freebayes/NA12878-1-effects-ploidyfix-filter-NA12878-1.vcf.gz --threshold 0.00001
```
Do you have any tips to tweak memory usage or debug further? I think this is relatively recent behavior as I've only got one other report about it and only been able to reproduce it myself recently but am definitely not ruling out things I'm doing wrong on the bcbio side. Thanks so much for any tips or tricks.
```
[2016-11-17T06:55Z] CNVkit segment
[2016-11-17T07:12Z] Loaded 4256605 records; skipped: 0 somatic, 0 depth
[2016-11-17T07:12Z] Selected test sample NA12878-1 and control sample
[2016-11-17T07:12Z] Dropped 107 outlier bins:
[2016-11-17T07:12Z]    chromosome      start        end  \
[2016-11-17T07:12Z] 0        chr1   31431646   31432148
[2016-11-17T07:12Z] 1        chr1   59583279   59583779
[2016-11-17T07:12Z] 2        chr1   67542548   67543046
[2016-11-17T07:12Z] 3        chr1  233827072  233827569
[2016-11-17T07:12Z] 4        chr1  234397168  234397667
[2016-11-17T07:12Z] 5        chr1  243619489  243619989
[2016-11-17T07:12Z] 6        chr2   16145293   16145797
[2016-11-17T07:12Z] 7        chr2   32867480   32867980
[2016-11-17T07:12Z] 8        chr2   97189014   97189514
[2016-11-17T07:12Z] 9        chr2  108239193  108239692
[2016-11-17T07:12Z] 10       chr3  120175137  120175637
[2016-11-17T07:12Z] 11       chr3  125217574  125218074
[2016-11-17T07:12Z] 12       chr3  179936537  179937037
[2016-11-17T07:12Z] 13       chr3  194678586  194679086
[2016-11-17T07:12Z] 14       chr4    6650245    6650745
[2016-11-17T07:12Z] 15       chr5   10273853   10274353
[2016-11-17T07:12Z] 16       chr5  127836946  127837444
[2016-11-17T07:12Z] 17       chr5  139453107  139453607
[2016-11-17T07:12Z] 18       chr6   18401900   18402400
[2016-11-17T07:12Z] 19       chr6   32811281   32811782
[2016-11-17T07:12Z] 
[2016-11-17T07:12Z]                                                  gene      log2      depth  \
[2016-11-17T07:12Z] 0                                  AC114494.1,SERINC2   3.98474  737.29100
[2016-11-17T07:12Z] 1              FGGY,MIR4711,RP4-782L23.1,RP4-782L23.2 -25.68500    0.00000
[2016-11-17T07:12Z] 2                RNU6-1031P,RP11-393N21.1,RP4-763G1.2 -25.68230    0.00000
[2016-11-17T07:12Z] 3                                       RP11-301G21.1 -25.75420    0.00000
[2016-11-17T07:12Z] 4   COA6,RP5-827C21.1,RP5-827C21.2,RP5-827C21.4,RP...  -3.79770    3.24048
[2016-11-17T07:12Z] 5                 AKT3,AKT3-IT1,FABP7P1,RP11-370K11.1 -25.76200    0.00000
[2016-11-17T07:12Z] 6                                        WI2-2221J1.1 -25.80470    0.00000
[2016-11-17T07:12Z] 7   AL121656.5,AL133243.1,AL133243.2,AL133243.3,AL... -25.80490    0.00000
[2016-11-17T07:12Z] 8   AC018892.9,AC159540.3,ANKRD36,FAHD2B,IGKV1OR2-... -25.74920    0.00000
[2016-11-17T07:12Z] 9   AC019100.7,RP11-443K8.1,RP11-465O11.2,SULT1C2,... -25.71130    0.00000
[2016-11-17T07:12Z] 10                                       GPR156,Y_RNA  -3.94995    3.17000
[2016-11-17T07:12Z] 11  DUTP1,MIR5092,RNU6-230P,RNU6-232P,RP11-775J23.... -25.62560    0.00000
[2016-11-17T07:12Z] 12  PEX5L,PEX5L-AS1,PEX5L-AS2,RP11-473P24.2,RP11-4...  -4.39429    2.49400
[2016-11-17T07:12Z] 13  AC046143.3,AC090505.4,AC090505.5,AC090505.6,AC... -25.67220    0.00000
[2016-11-17T07:12Z] 14                         MAN2B2,MRFAP1,PPP2R2C,WFS1 -25.72100    0.00000
[2016-11-17T07:12Z] 15  AC012640.1,ANKRD33B,ANKRD33B-AS1,CCT5,CMBL,CTD... -25.54020    0.00000
[2016-11-17T07:12Z] 16                             CTC-228N24.2,LINC01183 -25.74040    0.00000
[2016-11-17T07:12Z] 17  AC034243.1,AC138517.4,AC138517.5,CTB-164L20.1,... -25.80500    0.00000
[2016-11-17T07:12Z] 18                RNF144B,RP11-528A10.1,RP11-528A10.2 -25.73160    0.00000
[2016-11-17T07:12Z] 19  HLA-DOB,HLA-Z,PPP1R2P1,PSMB8,PSMB8-AS1,PSMB9,T... -25.65970    0.00000
[2016-11-17T07:12Z] 
[2016-11-17T07:12Z]       weight
[2016-11-17T07:12Z] 0   0.990138
[2016-11-17T07:12Z] 1   0.986193
[2016-11-17T07:12Z] 2   0.982249
[2016-11-17T07:12Z] 3   0.980276
[2016-11-17T07:12Z] 4   0.984221
[2016-11-17T07:12Z] 5   0.986193
[2016-11-17T07:12Z] 6   0.994083
[2016-11-17T07:12Z] 7   0.986193
[2016-11-17T07:12Z] 8   0.986193
[2016-11-17T07:12Z] 9   0.984221
[2016-11-17T07:12Z] 10  0.986193
[2016-11-17T07:12Z] 11  0.986193
[2016-11-17T07:12Z] 12  0.986193
[2016-11-17T07:12Z] 13  0.986193
[2016-11-17T07:12Z] 14  0.986193
[2016-11-17T07:12Z] 15  0.986193
[2016-11-17T07:12Z] 16  0.982249
[2016-11-17T07:12Z] 17  0.986193
[2016-11-17T07:12Z] 18  0.986193
[2016-11-17T07:12Z] 19  0.988166
[2016-11-17T07:12Z] ...
[2016-11-17T07:13Z] Traceback (most recent call last):
[2016-11-17T07:13Z]   File "/mnt/work/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
[2016-11-17T07:13Z]     args.func(args)
[2016-11-17T07:13Z]   File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 748, in _cmd_segment
[2016-11-17T07:13Z]     processes=args.processes)
[2016-11-17T07:13Z]   File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 35, in do_segmentation
[2016-11-17T07:13Z]     skip_outliers, save_dataframe, rlibpath)
[2016-11-17T07:13Z]   File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/segmentation/__init__.py", line 105, in _do_segmentation
[2016-11-17T07:13Z]     seg_out = core.call_quiet('Rscript', '--vanilla', script_fname)
[2016-11-17T07:13Z]   File "/mnt/work/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/core.py", line 34, in call_quiet
[2016-11-17T07:13Z]     + "\n(Original error: %s)" % exc)
[2016-11-17T07:13Z] RuntimeError: Could not find the executable 'Rscript' -- is it installed correctly?
[2016-11-17T07:13Z] (Original error: [Errno 12] Cannot allocate memory)
```

**Comment by etal** [comment]
Dang. I think the suspects are:

- CBS segmentation hogs memory as well as CPU. If haar or flasso perform OK, maybe they should be preferred for WGS. That doesn't explain why this is a recent problem, though. The underlying Bioconductor package DNAcopy has been pretty stable since 2007, but PSCBS is quite active.
- Even though I don't see parallelization happening here, maybe the code reorg for parallelization is preventing or dissuading Python from doing garbage collection after processing each chromosome. The memory allocation error happening on chr1 suggests this isn't the problem.
- Bioconductor doesn't make it easy to test running the same command and data with an older version of the PSCBS package, but that might help track down the issue. Looking at the timestamps above, it looks like the crash is happening within a minute after starting to load the chr1 dataset in R. Is that right? If so, then I can test this on my own workstation if you send me chr1 of your .cnr file.

**Comment by chapmanb** [comment]
Eric;
Thanks much for the ideas and help with this. I dug into it more with these suggestions, trying to put together a reproducible test case. In the process of doing that, I tested some different options and it looks like the issue is with passing in a VCF file (via `-v`). For whole genome files that appears to use up a lot of memory, resulting in the system not having enough for the segmentation. Dropping that lets things finish cleanly now for whole genome runs again. I'd introduced the VCF for allele frequency segmentation after testing on panels/exomes recently, so that is likely the source of the whole genome change. Thanks again for the help debugging this and happy to have things working cleanly again.

**Comment by etal** [comment]
Interesting. It sounds like VCF loading for BAF segmentation needs to be lazier, and use an index if it's available to select each chromosome individually.

**Comment by chapmanb** [comment]
Thanks Eric, we can close this if you think that's a big project to undertake. I haven't got a full sense of how much VCF versus non-VCF helps, especially for whole genome so have no problem with the current state of things.

**Comment by etal** [comment]
At one point I did some back-of-the-envelope math to decide that loading WGS data in a single DataFrame should be feasible. The last commit here should reduce the size of the VCF dataframe in memory during segmentation -- maybe by half? That might be enough to get your dataset to work.
