### ISSUE TITLE
Correcting for density bias...true_divide

### ISSUE THREAD

**Issue by ramaniak** [etal/cnvkit#167]
Hello Eric,

I am running cnvkit fix step as follows:

```
cnvkit.py fix A2.targetcoverage.cnn A2.antitargetcoverage.cnn Reference.cnn -o A2.cnr

```
and am seeing the following log which I am not sure how to interpret/fix.

```
Processing target: A2
Keeping 254401 of 256375 bins
Correcting for GC bias...
Correcting for density bias...
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:170: : divide by zero encountered in true_divide
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:175: RuntimeWarning: divide by zero encountered in true_divide
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:175: RuntimeWarning: invalid value encountered in subtract
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:198: RuntimeWarning: divide by zero encountered in true_divide
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:204: RuntimeWarning: divide by zero encountered in true_divide
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:204: RuntimeWarning: invalid value encountered in subtract
Processing antitarget: A2
Traceback (most recent call last):
  File "/hpf/tools/centos6/python/2.7.12/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.8.1', 'cnvkit.py')
  File "/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(script_code, namespace, namespace)
  File "/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 13, in <module>
    
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 677, in _cmd_fix
    
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 691, in do_fix
    
  File "build/bdist.linux-x86_64/egg/cnvlib/fix.py", line 24, in load_adjust_coverages
  File "build/bdist.linux-x86_64/egg/cnvlib/fix.py", line 94, in match_ref_to_sample
ValueError: Reference is missing 7309 bins found in A2
```

Thanks
Arun

**Comment by etal** [comment]
This error is meant to indicate that the reference bins are not a strict superset of the targets and antitargets, e.g. either the wrong reference was used, or the given targets or antitargets don't match the reference -- or perhaps there's a bug.

Could you check whether it's the targets or antitargets that have extra rows not found in `Reference.cnn`? For example, take the set of start positions in A2.targetcoverage.cnn and test that they're all present in Reference.cnn's start positions, then do the same for A2.antitargetcoverage.cnn.

**Comment by ramaniak** [comment]
Neither the target or antitarget cnn file have any extra rows. 

I checked the code and both the target, antitarget were generated with the same reference fasta file. 

I removed the existing cnn files and reference file and re-generated them afresh.

Now I am getting the following result:

```
Processing target: A2
Keeping 254938 of 256375 bins
Correcting for GC bias...
Correcting for density bias...
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:170: RuntimeWarning: divide by zero encountered in true_divide
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:175: RuntimeWarning: divide by zero encountered in true_divide
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:175: RuntimeWarning: invalid value encountered in subtract
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:198: RuntimeWarning: divide by zero encountered in true_divide
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:204: RuntimeWarning: divide by zero encountered in true_divide
/hpf/tools/centos6/python/2.7.12/lib/python2.7/site-packages/CNVkit-0.8.1-py2.7.egg/cnvlib/fix.py:204: RuntimeWarning: invalid value encountered in subtract
Processing antitarget: A2
Keeping 30289 of 30311 bins
Correcting for GC bias...
Correcting for RepeatMasker bias...
Targets are 1.84 x more variable than antitargets
Wrote A2.cnr with 285227 regions
Dropped 295 low-coverage bins
Dropped 5 outlier bins:
  chromosome      start        end      gene     log2      depth    weight
0          5   42629140   42629205       GHR -9.55781     0.6000  0.246867
1          5   69372348   69372398      SMN1 -4.34696    18.2200  0.226686
2          6  167791443  167791580     TCP10  1.47220  1907.6000  0.210400
3         16   55866916   55866967      CES1 -4.69691    25.0784  0.208363
4         19   52148730   52148783  SIGLEC14 -9.28682     1.0000  0.253525
Wrote A2.cns with 731 regions
```

As you can see the second set of errors seem to have disappeared, but the initial error with the fix.py is still present.

Arun

**Comment by ramaniak** [comment]
Okay, I figured it out. There were instances in my target bed where the start and end positions were the same. This was resulting in a target size of '0' and hence the  "divide by zero" error.

Fixing these clears the errors.

thanks
Arun

**Comment by etal** [comment]
Thanks for tracking down this issue. I'll see about dropping zero-width bins in the `target` and `reference` commands to avoid the warning. The underlying array implementations handle division by zero as NaN instead of crashing, which is why you see the repeated RuntimeWarnings instead of a single error traceback there.
