### ISSUE TITLE
Error in 'export theta' with normal/reference

### ISSUE THREAD

**Issue by nuin** [etal/cnvkit#168]
Hi 

I am getting this error during tests

```python

python ../cnvkit.py export vcf build/p2-9_2.call.cns -y -o p2-9_2.vcf
/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py:878: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
Treating sample gender as female
Wrote p2-9_2.vcf
python ../cnvkit.py export theta build/p2-9_2.cns -r build/reference-picard.cnn -o p2-9_2.theta2.input
/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py:878: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
Traceback (most recent call last):
  File "../cnvkit.py", line 13, in <module>
    args.func(args)
  File "/Users/nuin/src/cnvkit/cnvlib/commands.py", line 1954, in _cmd_export_theta
    table = export.export_theta(tumor_cn, normal_cn)
  File "/Users/nuin/src/cnvkit/cnvlib/export.py", line 374, in export_theta
    table["normalCount"] = theta_read_counts(ref_means, nbins)
  File "/Users/nuin/src/cnvkit/cnvlib/export.py", line 451, in theta_read_counts
    return read_count.round().astype('int')
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3189, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 3056, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 461, in astype
    values=values, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 504, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/usr/local/lib/python2.7/site-packages/pandas/types/cast.py", line 531, in _astype_nansafe
    raise ValueError('Cannot convert NA to integer')
ValueError: Cannot convert NA to integer
make: *** [p2-9_2.theta2.input] Error 1
```

All requirements are installed correctly, and running with `make -j 8` still shows the error but the process completes.

**Comment by etal** [comment]
Thanks for reporting. Which versions of CNVkit and pandas are you using?

**Comment by nuin** [comment]
@etal 

```
>>> pandas.__version__
u'0.19.1
```

And I just pulled CNVkit from your repo.

Thanks

**Comment by etal** [comment]
Strange, I don't see the error. I did `make clean; make all` and `make clean; make p2-9_2.theta2.input`; no error. Did you run the tests from a clean repo, or run `make clean` beforehand? Maybe an outdated p2-9_2.cns or reference-picard.cnn's bins did not match up cleanly and pandas inserted an NaN to fill a row.

If that's not it, do you have any other ideas what might cause this?

**Comment by nuin** [comment]
@etal With the `make clean; make all` it worked fine. Thanks for the help. I am testing the software today.

**Comment by jlac** [comment]
Hi,

I am using the most recent version of CNVKit (0.8.5), and am having this issue, although only for some samples. However, I am unable to tell what it is about samples that fail that is causing the failure. The installation was performed as described above, but this did not get rid of the issue. I ran the following series of commands to generate all input/output files:

cnvkit.py target /data/CCBR_Pipeliner/db/PipeDB/lib/access-5k-mappable.grch37.bed --split --short-names -o targets.bed -a 3000

cnvkit.py coverage ../12-CT35-normal-saliva.recal.bam targets.bed -o 12-CT35-normal-saliva.targetcoverage.cnn -p 8

cnvkit.py coverage ../11-CT35-2-neck-metastasis-G11.recal.bam targets.bed -o 11-CT35-2-neck-metastasis-G11.targetcoverage.cnn -p 8

cnvkit.py coverage ../10-CT35-1-neck-metastasis-G7.recal.bam targets.bed -o 10-CT35-1-neck-metastasis-G7.targetcoverage.cnn -p 8

cnvkit.py reference -f /data/CCBR_Pipeliner/db/PipeDB/lib/hs37d5.fa -o 12-CT35-normal-saliva.reference.cnn --no-edge -y -x male 12-CT35-normal-saliva.targetcoverage.cnn MT.antitargetcoverage.cnn

cnvkit.py fix 10-CT35-1-neck-metastasis-G7.targetcoverage.cnn MT.antitargetcoverage.cnn 12-CT35-normal-saliva.reference.cnn -o 10-CT35-1-neck-metastasis-G7.cnr --no-edge

cnvkit.py segment 10-CT35-1-neck-metastasis-G7.cnr --min-variant-depth 5 -p 8 -v ../cnvkit_out/12-CT35-normal-saliva+10-CT35-1-neck-metastasis-G7_filtGermpairs.vcf -i 10-CT35-1-neck-metastasis-G7 -n 12-CT35-normal-saliva -o 10-CT35-1-neck-metastasis-G7.cns -t 1e-6

cnvkit.py export theta -v ../cnvkit_out/12-CT35-normal-saliva+11-CT35-2-neck-metastasis-G11_filtGermpairs.vcf -i 11-CT35-2-neck-metastasis-G11 -n 12-CT35-normal-saliva -m 5 -r 12-CT35-normal-saliva.reference.cnn -o 11-CT35-2-neck-metastasis-G11_THETAin 11-CT35-2-neck-metastasis-G11.cns


It is the last command that is failing with the following error:

Traceback (most recent call last):
  File "/usr/local/apps/cnvkit/0.8.5/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/cnvlib/commands.py", line 1493, in _cmd_export_theta
    table = export.export_theta(tumor_cn, normal_cn)
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/cnvlib/export.py", line 375, in export_theta
    table["normalCount"] = theta_read_counts(ref_means, nbins)
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/cnvlib/export.py", line 452, in theta_read_counts
    return read_count.round().astype('int')
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/pandas/core/internals.py", line 3189, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/pandas/core/internals.py", line 3056, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/pandas/core/internals.py", line 461, in astype
    values=values, **kwargs)
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/pandas/core/internals.py", line 504, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/usr/local/Anaconda/envs_app/cnvkit/0.8.5/lib/python2.7/site-packages/pandas/types/cast.py", line 531, in _astype_nansafe
    raise ValueError('Cannot convert NA to integer')
ValueError: Cannot convert NA to integer

I am attaching the file that failed (11-CT35-2-neck-metastasis-G11.cns), as well as the file that ran without issue(10-CT35-1-neck-metastasis-G7.cns). Both samples are tumors from the sample, so the reference used was actually the same. Any ideas on what might be happening? Thanks!

Justin

[11-CT35-2-neck-metastasis-G11.cns.txt](https://github.com/etal/cnvkit/files/855150/11-CT35-2-neck-metastasis-G11.cns.txt)
[10-CT35-1-neck-metastasis-G7.cns.txt](https://github.com/etal/cnvkit/files/855151/10-CT35-1-neck-metastasis-G7.cns.txt)

**Comment by etal** [comment]
It looks like the crash was triggered in `export theta` when processing the reference used for normal bin counts, `12-CT35-normal-saliva.reference.cnn`. Could you try the last command without `-r 12-CT35-normal-saliva.reference.cnn`?

**Comment by jlac** [comment]
That worked! But I’m still not sure why the error happens in the first place, since the tumor sample that ran without issue was run with that same reference file.

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Comment by etal** [comment]
I think this is fixed in the development version now.

**Comment by jlac** [comment]
Thanks!

Justin Lack
Bioinformatic Analyst
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Post Office Box B
Frederick, MD  21702
Phone: 405-314-4356
justin.lack@nih.gov

**Comment by cnizo** [comment]
Hi @etal!

I ran into an error while performing the test. Here is the log:

```
Treating sample p2-5_5.call as male
Treating sample p2-9_2.call as male
Treating sample p2-20_1.call as male
Treating sample p2-20_2.call as male
Treating sample p2-20_3.call as male
Treating sample p2-20_4.call as male
Treating sample p2-20_5.call as male
Wrote p2-all.bed
python ../cnvkit.py export vcf -o p2-9_2.vcf -y --cnr build/p2-9_2.cnr build/p2-9_2.call.cns -y -o p2-9_2.vcf
Treating sample p2-9_2.call as male
Traceback (most recent call last):
  File "../cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/varianttools/bioinfo/app/cnvkit/cnvlib/commands.py", line 1625, in _cmd_export_vcf
    is_sample_female, args.sample_id, cnarr)
  File "/home/varianttools/bioinfo/app/cnvkit/cnvlib/export.py", line 237, in export_vcf
    segments = assign_ci_start_end(segments, cnarr)
  File "/home/varianttools/bioinfo/app/cnvkit/cnvlib/export.py", line 261, in assign_ci_start_end
    ci_lefts, ci_rights = zip(*lefts_rights)
  File "/home/varianttools/bioinfo/app/cnvkit/cnvlib/export.py", line 260, in <genexpr>
    for _seg, bins in cnarr.by_ranges(segarr, mode="outer"))
  File "/home/varianttools/_env/lib/python3.5/site-packages/pandas/core/indexing.py", line 1869, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/varianttools/_env/lib/python3.5/site-packages/pandas/core/series.py", line 928, in _get_value
    return _maybe_box_datetimelike(self._values[label])
IndexError: index 0 is out of bounds for axis 0 with size 0
Makefile:148: recipe for target 'p2-9_2.vcf' failed
make: *** [p2-9_2.vcf] Error 1
```

Do you have an idea of what it might be? I have just cloned the repository and I have already tried doing ```make clean; make all```
