### ISSUE TITLE
scatter: throws error when requesting a region in gene-list where theres no data

### ISSUE THREAD

**Issue by gabeng** [etal/cnvkit#174]
`--range-list` is very useful for plotting a standard set of graphs for a large number of samples. In some instances there may be very few target regions on chromosomes which are then ommitted for certain samples due to sparse data. In these cases, there is no data to plot. The scatter command then throws an error. It would be better if cnvkit just printed a warning.

**Comment by etal** [comment]
Thanks for catching this. Could you post a traceback of the error?

**Comment by gabeng** [comment]
Here it is:
```
Traceback (most recent call last):
  File "/home/ubuntu/local/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/ubuntu/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1047, in _cmd_scatter
    args.segment_color)
  File "/home/ubuntu/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1142, in do_scatter
    start, end)[chrom]
  File "/home/ubuntu/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/plots.py", line 547, in gene_coords_by_range
    for row in probes.in_range(chrom, start, end):
  File "/home/ubuntu/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/gary.py", line 322, in in_range
    return self.as_dataframe(next(results))
  File "/home/ubuntu/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/genome/gary.py", line 100, in as_dataframe
    return self.__class__(dframe.reset_index(drop=True), self.meta.copy())
AttributeError: 'list' object has no attribute 'reset_index'
```

**Comment by etal** [comment]
It should be working in the development version now.
