### ISSUE TITLE
KeyError: None in regions.py, }[fmt]

### ISSUE THREAD

**Issue by mjafin** [etal/cnvkit#19]
Hi Eric,
I'm running a whole genome analysis without normals and am getting the following error:
```
Splitting: .                26381
Wrote ./2_2015-04-02_bcbio_cnvkit-sort-callable-callableblocks-merged-annotated.target.bed with 4410794 target intervals
Detected file format: BED
Detected file format: BED
Detected file format: BED
Wrote ./2_2015-04-02_bcbio_cnvkit-sort-callable-callableblocks-merged-annotated.antitarget.bed with 1 background intervals
Building a flat reference...
Detected file format: BED
Traceback (most recent call last):
  File "/group/ngs/src/bcbio-nextgen/0.8.8/rhel6-x64/anaconda/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/group/ngs/src/bcbio-nextgen/0.8.8/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 80, in _cmd_batch
    args.processes, args.count_reads)
  File "/group/ngs/src/bcbio-nextgen/0.8.8/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 148, in batch_make_reference
    male_reference)
  File "/group/ngs/src/bcbio-nextgen/0.8.8/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 509, in do_reference_flat
    ref_probes.extend(reference.bed2probes(antitarget_list))
  File "/group/ngs/src/bcbio-nextgen/0.8.8/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/reference.py", line 15, in bed2probes
    for chrom, start, end, name in ngfrills.parse_regions(bed_fname)]
  File "/group/ngs/src/bcbio-nextgen/0.8.8/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/ngfrills/regions.py", line 62, in parse_regions
    }[fmt]
KeyError: None
```
The command is roughly:
``cnvkit.py batch 2_2015-04-02_bcbio_cnvkit-sort.bam -n -f /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa --targets 2_2015-04-02_bcbio_cnvkit-sort-callable-callableblocks-merged-annotated.bed --access 2_2015-04-02_bcbio_cnvkit-sort-callable-callableblocks-merged-annotated.bed -d ./ --split -p 1 --output-reference ./flat_background.cnn --antitarget-avg-size 1000 --antitarget-min-size 75 --target-avg-size 1000 --rlibpath /group/ngs/src/bcbio-nextgen/0.8.8/rhel6-x64/lib/R/site-library``

The antitarget bed file that gets produced is empty (as expected). The target bed file has 4 columns.

Any ideas?

**Comment by etal** [comment]
Can you pull from git and see if commit 4b4569caff9d97363c3fa836dba35225fc640d40 fixes it?

**Comment by mjafin** [comment]
Nice, thanks, I'll give that a try

**Comment by mjafin** [comment]
Yep, that got me past the point of the crash, many thanks again!
