### ISSUE TITLE
Can't get cnvkit.py segment Sample.cnr -o Sample.cns to work

### ISSUE THREAD

**Issue by mgfield** [etal/cnvkit#215]
I am getting the following error and can't figure out what is going on. 

cnvkit.py segment Rb006T_abra_fixed.cnr -o Rb006T_abra_fixed.cns
...
/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/CNVkit-0.8.5-py2.7.egg/cnvlib/tabio/seg.py:140: FutureWarning: pandas.parser is deprecated and will be removed in a future version.
You can access CParserError as pandas.errors.ParserError
Traceback (most recent call last):
  File "/projects/med/hlab/software/virtualpython/ENV/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.8.5', 'cnvkit.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 745, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1677, in run_script
  File "/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/CNVkit-0.8.5-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 13, in <module>
    
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 597, in _cmd_segment
    
  File "build/bdist.linux-x86_64/egg/cnvlib/segmentation/__init__.py", line 31, in do_segmentation
  File "build/bdist.linux-x86_64/egg/cnvlib/segmentation/__init__.py", line 116, in _do_segmentation
  File "build/bdist.linux-x86_64/egg/cnvlib/tabio/__init__.py", line 80, in read
  File "build/bdist.linux-x86_64/egg/cnvlib/tabio/seg.py", line 63, in read_seg
  File "build/bdist.linux-x86_64/egg/cnvlib/tabio/seg.py", line 127, in parse_seg
  File "/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/pandas-0.20.0rc1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/pandas-0.20.0rc1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 392, in _read
    filepath_or_buffer, encoding, compression)
  File "/projects/med/hlab/software/virtualpython/ENV/lib/python2.7/site-packages/pandas-0.20.0rc1-py2.7-linux-x86_64.egg/pandas/io/common.py", line 210, in get_filepath_or_buffer
    raise ValueError(msg.format(_type=type(filepath_or_buffer)))
ValueError: Invalid file path or buffer object type: <type 'cStringIO.StringI'>

**Comment by etal** [comment]
Thanks for letting me know. Pandas version 0.20 hasn't been officially released yet, so I haven't tested it with CNVkit. Apparently, the pandas CSV parser will no longer accept StringIO instances as file-like objects for input. I'll look for a workaround.

CNVkit 0.8.5. should work for you if you use pandas 0.19. I see you're using an isolated Python installation (a precursor to virtualenv and conda?), so just try downgrading to `pandas=0.19.2` within that environment.
