### ISSUE TITLE
IndexError when run cnvkit.py access

### ISSUE THREAD

**Issue by anyone1985** [etal/cnvkit#235]
Hi, 
I'd like to run the cnvkit as following command : "cnvkit.py batch Cancer_*.bam --normal Normal_*.bam -f ../Human/ucsc.hg19.fasta --annotate ../Human/refFlat.txt --access ../packages/access-5k-mappable.hg19.bed --method wgs --output-reference p2_reference.cnn --output-dir p2_cnv -p 24". And , I come access this error. Please help me to fix the error.

chr10: Scanning for accessible regions
        Accessible region chr10:60000-17974675 (size 17914675)
        Accessible region chr10:18024675-38818835 (size 20794160)
        Accessible region chr10:38868835-39154935 (size 286100)
        Accessible region chr10:42354935-42546687 (size 191752)
        Accessible region chr10:42596687-46426964 (size 3830277)
        Accessible region chr10:46476964-47429169 (size 952205)
        Accessible region chr10:47529169-47792476 (size 263307)
        Accessible region chr10:47892476-48055707 (size 163231)
        Accessible region chr10:48105707-49095536 (size 989829)
        Accessible region chr10:49195536-51137410 (size 1941874)
        Accessible region chr10:51187410-51398845 (size 211435)
        Accessible region chr10:51448845-60027702 (size 8578857)
        Accessible region chr10:60027703-64321063 (size 4293360)
Traceback (most recent call last):
  File "/home/dragon/prostate/tools/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.9.0.dev0', 'cnvkit.py')
  File "/home/dragon/prostate/tools/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 741, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dragon/prostate/tools/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1509, in run_script
    exec(script_code, namespace, namespace)
  File "/home/dragon/prostate/tools/local/lib/python2.7/site-packages/CNVkit-0.9.0.dev0-py2.7.egg/EGG-INFO/scripts/cnvkit.py", lin
e 13, in <module>

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 107, in _cmd_batch

  File "build/bdist.linux-x86_64/egg/cnvlib/batch.py", line 62, in batch_make_reference
  File "build/bdist.linux-x86_64/egg/cnvlib/access.py", line 20, in do_access
  File "build/bdist.linux-x86_64/egg/skgenome/gary.py", line 86, in from_rows
  File "/home/dragon/prostate/tools/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1008, in from_records
    values += data
  File "build/bdist.linux-x86_64/egg/cnvlib/access.py", line 61, in get_regions
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1

**Comment by etal** [comment]
Thanks for reporting. This looks like the same bug as #238 . I'll put a priority on it.
