### ISSUE TITLE
problem when running cnvkit.py access

### ISSUE THREAD

**Issue by mdtorohernando** [etal/cnvkit#238]
Hi, I'm dealing with the following error when installing CNVKit v0.9.0.dev0 from the master package. It didn't happened to me with previous versions. 

azken@azken2:/media/azken/RAID5/bowtie_indexes$ cnvkit.py access mus_musculus.GRCm38_80.fa -s 1000 -o access-prueba.bed
1: Scanning for accessible regions
	Accessible region 1:3000000-3002129 (size 2129)
	Accessible region 1:3003118-22424867 (size 19421749)
	Accessible region 1:22424967-22433268 (size 8301)
	Accessible region 1:22466510-25909750 (size 3443240)
	Accessible region 1:25909751-75055556 (size 49145805)
	Accessible region 1:75121556-78606965 (size 3485409)
	Accessible region 1:78607065-78608149 (size 1084)
	Accessible region 1:78609094-78610150 (size 1056)
	Accessible region 1:78610785-78613879 (size 3094)
	Accessible region 1:78614162-85347103 (size 6732941)
	Accessible region 1:85447103-143399970 (size 57952867)
	Accessible region 1:143449970-156118743 (size 12668773)
	Accessible region 1:156168743-167552380 (size 11383637)
	Accessible region 1:167552390-167646222 (size 93832)
	Accessible region 1:167646232-167685492 (size 39260)
	Accessible region 1:167685502-167817559 (size 132057)
	Accessible region 1:167817569-171228615 (size 3411046)
Traceback (most recent call last):
  File "/home/azken/sw/cnvkit-master/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/azken/sw/cnvkit-master/cnvlib/commands.py", line 263, in _cmd_access
    args.min_gap_size)
  File "/home/azken/sw/cnvkit-master/cnvlib/access.py", line 20, in do_access
    access_regions = GA.from_rows(get_regions(fa_fname))
  File "/home/azken/sw/cnvkit-master/skgenome/gary.py", line 86, in from_rows
    table = pd.DataFrame.from_records(rows, columns=columns)
  File "/home/azken/miniconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 1008, in from_records
    values += data
  File "/home/azken/sw/cnvkit-master/cnvlib/access.py", line 61, in get_regions
    ok_starts = n_indices[gap_mask] + 1 + cursor
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1

Thank you

**Comment by leiendeckerlu** [comment]
I get the same error with version 0.8.6a0 

`cnvkit.py access Homo_sapiens_assembly38.fasta`

Output:

chr1: Scanning for accessible regions
	Accessible region chr1:10000-207666 (size 197666)
	Accessible region chr1:257666-297968 (size 40302)
	Accessible region chr1:347968-535988 (size 188020)
	Accessible region chr1:585988-2702781 (size 2116793)
	Accessible region chr1:2746290-12954384 (size 10208094)
	Accessible region chr1:13004384-16799163 (size 3794779)
	Accessible region chr1:16849163-29552233 (size 12703070)
	Accessible region chr1:29553835-121757468 (size 92203633)
	Accessible region chr1:121757469-121757508 (size 39)
	Accessible region chr1:121757509-121757928 (size 419)
Traceback (most recent call last):
  File "cnvkit.py", line 13, in <module>
    args.func(args)
  File "/Software/cnvkit/lib/python2.7/site-packages/cnvlib/commands.py", line 263, in _cmd_access
    args.min_gap_size)
  File "/Software/cnvkit/lib/python2.7/site-packages/cnvlib/access.py", line 20, in do_access
    access_regions = GA.from_rows(get_regions(fa_fname))
  File "/Software/cnvkit/lib/python2.7/site-packages/skgenome/gary.py", line 86, in from_rows
    table = pd.DataFrame.from_records(rows, columns=columns)
  File "/Software/cnvkit/lib/python2.7/site-packages/pandas/core/frame.py", line 1008, in from_records
    values += data
  File "/Software/cnvkit/lib/python2.7/site-packages/cnvlib/access.py", line 61, in get_regions
    ok_starts = n_indices[gap_mask] + 1 + cursor
IndexError: boolean index did not match indexed array along dimension 0; dimension is 40 but corresponding boolean dimension is 39

Thank you!

**Comment by mcieslik-mctp** [comment]
Same error on 0.8.5. Tried downgrading pandas but it did not work.
```
chr1: Scanning for accessible regions
	Accessible region chr1:10000-207666 (size 197666)
	Accessible region chr1:257666-297968 (size 40302)
	Accessible region chr1:347968-535988 (size 188020)
	Accessible region chr1:585988-2702781 (size 2116793)
	Accessible region chr1:2746290-12954384 (size 10208094)
	Accessible region chr1:13004384-16799163 (size 3794779)
	Accessible region chr1:16849163-29552233 (size 12703070)
	Accessible region chr1:29553835-121757468 (size 92203633)
Traceback (most recent call last):
  File "/wdir/libs/py27/full/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/wdir/libs/py27/full/local/lib/python2.7/site-packages/cnvlib/commands.py", line 101, in _cmd_batch
    args.count_reads, args.method)
  File "/wdir/libs/py27/full/local/lib/python2.7/site-packages/cnvlib/batch.py", line 58, in batch_make_reference
    access_arr = access.do_access(fasta)
  File "/wdir/libs/py27/full/local/lib/python2.7/site-packages/cnvlib/access.py", line 21, in do_access
    access_regions = GA.from_rows(get_regions(fa_fname))
  File "/wdir/libs/py27/full/local/lib/python2.7/site-packages/cnvlib/genome/gary.py", line 90, in from_rows
    table = pd.DataFrame.from_records(rows, columns=columns)
  File "/wdir/libs/py27/full/local/lib/python2.7/site-packages/pandas/core/frame.py", line 992, in from_records
    values += data
  File "/wdir/libs/py27/full/local/lib/python2.7/site-packages/cnvlib/access.py", line 62, in get_regions
    ok_starts = n_indices[gap_mask] + 1 + cursor
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 1
```

**Comment by mcieslik-mctp** [comment]
Ok... I was able to "fix" this error by down-grading pandas, numpy and scipy and keeping the same CNVkit version

These versions work:
```
/wdir/libs/py27/full/lib/python2.7/site-packages/numpy-1.12.1-py2.7.egg-info/
/wdir/libs/py27/full/lib/python2.7/site-packages/scipy-0.19.0-py2.7-linux-x86_64.egg/
/wdir/libs/py27/full/lib/python2.7/site-packages/pandas-0.19.2-py2.7-linux-x86_64.egg/
```

**Comment by etal** [comment]
Thanks for investigating, @mcieslik-mctp . Which versions of pandas triggered the bug? The latest I tested was 0.20.2.

**Comment by mcieslik-mctp** [comment]
The current defaults on pypi: pandas 0.20.3 and numpy 1.13.1

**Comment by etal** [comment]
OK, I've located and fixed the bug. It looks like numpy 1.11 allowed indexing with a boolean array that was shorter than the array being indexed, with a deprecation warning, but this permissive behavior was removed in numpy 1.12 or 1.13, triggering an IndexError instead. Thanks everyone for the feedback.

**Comment by mcieslik-mctp** [comment]
I think it would be good to commit a fixed package to pypi, now everyone who installs cnvkit though pip etc. will end up with a broken cnvkit

**Comment by etal** [comment]
Sure, will do.
