### ISSUE TITLE
erro in R script

### ISSUE THREAD

**Issue by mattoslmp** [etal/cnvkit#257]
Dear, 
I'm having the following error below. But the AR was installed together with cnvkit by the anaconda.
Any suggestion?

 File "/root/myprogramas/anaconda3/lib/python3.6/site-packages/cnvlib/core.py", line 28, in call_quiet
    stderr=subprocess.PIPE)
  File "/root/myprogramas/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/root/myprogramas/anaconda3/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'Rscript'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/myprogramas/anaconda3/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/root/myprogramas/anaconda3/lib/python3.6/site-packages/cnvlib/commands.py", line 605, in _cmd_segment
    processes=args.processes)
  File "/root/myprogramas/anaconda3/lib/python3.6/site-packages/cnvlib/segmentation/__init__.py", line 40, in do_segmentation
    skip_outliers, save_dataframe, rlibpath)
  File "/root/myprogramas/anaconda3/lib/python3.6/site-packages/cnvlib/segmentation/__init__.py", line 117, in _do_segmentation
    seg_out = core.call_quiet('Rscript', '--vanilla', script_fname)
  File "/root/myprogramas/anaconda3/lib/python3.6/site-packages/cnvlib/core.py", line 32, in call_quiet
    + "\n(Original error: %s)" % exc)
RuntimeError: Could not find the executable 'Rscript' -- is it installed correctly?
(Original error: [Errno 2] No such file or directory: 'Rscript')

**Comment by etal** [comment]
This sounds like it might be a packaging issue for bioconda on Python 3.6. Are you able to run R or Rscript directly from the command line, outside of CNVkit?

**Comment by mattoslmp** [comment]
Dear Eric, outside of CNVKit its running R version 3.3.2 (2016-10-31) or Rscript.

**Comment by mattoslmp** [comment]
Hi Eric, I found the solution, is because my R script is installed into folder: /root/myprogramas/anaconda3/bin/Rscript, but the cnvkit points to path /usr/bin/Rscript. I just made a copy: sudo cp -r /root/myprogramas/anaconda3/bin/R /usr/bin/ . Its running now

**Comment by etal** [comment]
OK, interesting. It seems like you might also need the `segment` option `--rlibpath` to point to the anaconda R package directory, but maybe Rscript found it automatically.

**Comment by mattoslmp** [comment]
Thanks for your attention Eric. Best, Leandro
