### ISSUE TITLE
AttributeError: 'int' object has no attribute 'item'

### ISSUE THREAD

**Issue by thakki** [etal/cnvkit#274]
With the most recent version installed I get the following error:

Traceback (most recent call last):
  File "/mnt/hiseq1-galaxy/galaxy_devel_working_dir/gatc_galaxy_centos6/galaxy_ska/tool_binaries/variant_analysis_pipeline_tools/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/mnt/hiseq1-galaxy/galaxy_devel_working_dir/gatc_galaxy_centos6/galaxy_ska/tool_binaries/bin/cnvkit-0.8.5/cnvlib/commands.py", line 101, in _cmd_batch
    args.count_reads, args.method)
  File "/mnt/hiseq1-galaxy/galaxy_devel_working_dir/gatc_galaxy_centos6/galaxy_ska/tool_binaries/bin/cnvkit-0.8.5/cnvlib/batch.py", line 134, in batch_make_reference
    do_rmask=True)
  File "/mnt/hiseq1-galaxy/galaxy_devel_working_dir/gatc_galaxy_centos6/galaxy_ska/tool_binaries/bin/cnvkit-0.8.5/cnvlib/reference.py", line 30, in do_reference
    True, do_gc, do_edge, False)
  File "/mnt/hiseq1-galaxy/galaxy_devel_working_dir/gatc_galaxy_centos6/galaxy_ska/tool_binaries/bin/cnvkit-0.8.5/cnvlib/reference.py", line 119, in combine_probes
    gc, rmask = get_fasta_stats(cnarr1, fa_fname)
  File "/mnt/hiseq1-galaxy/galaxy_devel_working_dir/gatc_galaxy_centos6/galaxy_ska/tool_binaries/bin/cnvkit-0.8.5/cnvlib/reference.py", line 270, in get_fasta_stats
    for subseq in fasta_extract_regions(fa_fname, cnarr)]
  File "/mnt/hiseq1-galaxy/galaxy_devel_working_dir/gatc_galaxy_centos6/galaxy_ska/tool_binaries/bin/cnvkit-0.8.5/cnvlib/reference.py", line 299, in fasta_extract_regions
    yield fa_file[_chrom][start.item():end.item()]
AttributeError: 'int' object has no attribute 'item'

I don't know whether it is a bug or a problem on my side. Can you please help me?

Thanks!
Sascha

**Comment by etal** [comment]
It looks like you're using CNVkit version 0.8.5, which is not fully compatible with the recently released Pandas version 0.21.0 (see #273 ). You can solve the problem by either installing the development version of CNVkit from git, or by downgrading pandas to version 0.20.3 in the environment where CNVkit is currently installed.

**Comment by thakki** [comment]
Hi! Sorry for the confusion. I did a last test with CNVkit 0.8.5. I get the same error with a fresh Python 2.7.14 installation and letting CNVkit 0.9.0 fetch all dependencies.

**Comment by filipzembol** [comment]
I have similar problem:

Extracting sequences from chromosome chr17
Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 107, in _cmd_batch
    args.count_reads, args.method)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/batch.py", line 147, in batch_make_reference
    do_rmask=True)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/reference.py", line 40, in do_reference
    do_gc, do_edge, False)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/reference.py", line 145, in combine_probes
    gc, rmask = get_fasta_stats(cnarr1, fa_fname)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/reference.py", line 297, in get_fasta_stats
    for subseq in fasta_extract_regions(fa_fname, cnarr)]
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/reference.py", line 326, in fasta_extract_regions
    yield fa_file[_chrom][start.item():end.item()]
AttributeError: 'int' object has no attribute 'item'

Could you help me with this?

**Comment by thakki** [comment]
Using the development version solved the problem for me!

**Comment by filipzembol** [comment]
Really? I have python 2.7.6 and CNVKIT 0.9.0 doesnt work for me. Pandas version what I have 0.20.3 :-( So I try to downgrade CNVKIT to 0.8.5

**Comment by thakki** [comment]
The development version is 0.9.1 actually. Did you download/clone the repository?

**Comment by filipzembol** [comment]
On github I see only 0.9.0 ..

**Comment by thakki** [comment]
Yeah, which is the latest official release. Go to the main page (https://github.com/etal/cnvkit) and click clone or download.

**Comment by filipzembol** [comment]
Great, so I installed it by pip only, I tried this version. Or I downgrade pandas and CNVKIT to 0.8.5 and I will see... But thank you. I hope It will be ok..

**Comment by filipzembol** [comment]
Thank you, it wokrs well... 0.9.1
