### ISSUE TITLE
tabio read vcf error

### ISSUE THREAD

**Issue by davisem** [etal/cnvkit#279]
I'm seeing a crash in vcf reader. I'm sure it's a format related issue (as always with vcf formats), but I wanted to log it here and see if anyone had suggestions. 

```     44     rows = _parse_records(vcf_reader, sid, nid, skip_reject)
---> 45     table = pd.DataFrame.from_records(rows, columns=columns)
     46     table['alt_freq'] = table['alt_count'] / table['depth']
     47     if nid:

/Library/Python/2.7/site-packages/pandas/core/frame.pyc in from_records(cls, data, index, exclude, columns, coerce_float, nrows)
    995
    996             try:
--> 997                 first_row = next(data)
    998             except StopIteration:
    999                 return cls(index=index, columns=columns)

/Users/edavis5/Library/Python/2.7/lib/python/site-packages/skgenome/tabio/vcfio.pyc in _parse_records(records, sample_id, normal_id, skip_reject)
    227         # XXX Ensure sample genotypes are handled properly
    228         start = record.start
--> 229         for alt in record.alts:
    230             if alt == '<NON_REF>':
    231                 # gVCF placeholder -- not a real allele
```
Here is a bit from the header:
```
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes for each ALT allele, in the same order as listed">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=DP4,Number=4,Type=Integer,Description="Number of high-quality ref-forward , ref-reverse, alt-forward and alt-reverse bases">
##INFO=<ID=MQ,Number=1,Type=Integer,Description="Average mapping quality">
##bcftools_callVersion=1.6+htslib-1.6
##bcftools_callCommand=call -m; Date=Fri Nov 17 10:50:53 2017
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  na12878-chrM-Y-trunc.bam
chrY    11023   .       G       .       29.5864 .       DP=1;MQ0F=1;AN=0;DP4=0,0,0,0;MQ=.       GT      ./.
chrY    11024   .       A       .       29.5864 .       DP=1;MQ0F=1;AN=0;DP4=0,0,0,0;MQ=.       GT      ./.
chrY    11025   .       T       .       29.5864 .       DP=1;MQ0F=1;AN=0;DP4=0,0,0,0;MQ=.       GT      ./.
```

The vcf was made by running on the sample test case:
```
samtools mpileup -uf genome -Q 20 sample | bcftools call -m > out
```

The error is thrown when calling
```
cnvkit.py call cns -v sample_vcf --purity 0.8 -m none -o call.cns
```
Thanks!

**Comment by etal** [comment]
Thanks for reporting. Could you show the full traceback from the crash?

**Comment by etal** [comment]
In the meantime, you could possibly skip these problematic records by adding the option: `--min-variant-depth 1`

**Comment by davisem** [comment]
```
Traceback (most recent call last):
  File "/cgs02/home/edavis5/.local/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/edavis5/.local/lib/python3.5/site-packages/cnvlib/commands.py", line 690, in _cmd_call
    args.min_variant_depth, args.zygosity_freq)
  File "/home/edavis5/.local/lib/python3.5/site-packages/cnvlib/cmdutil.py", line 25, in load_het_snps
    skip_somatic=True)
  File "/home/edavis5/.local/lib/python3.5/site-packages/skgenome/tabio/__init__.py", line 80, in read
    dframe = reader(infile, **kwargs)
  File "/home/edavis5/.local/lib/python3.5/site-packages/skgenome/tabio/vcfio.py", line 45, in read_vcf
    table = pd.DataFrame.from_records(rows, columns=columns)
  File "/home/edavis5/.local/lib/python3.5/site-packages/pandas/core/frame.py", line 997, in from_records
    first_row = next(data)
  File "/home/edavis5/.local/lib/python3.5/site-packages/skgenome/tabio/vcfio.py", line 229, in _parse_records
    for alt in record.alts:
TypeError: 'NoneType' object is not iterable
```
unfortunately, `--min-variant-depth 1` didn't fix it. Same error.

**Comment by etal** [comment]
I pushed a possible fix. Could you try the latest from git?

**Comment by davisem** [comment]
Ok that seemed to do the trick. Thanks!
