### ISSUE TITLE
Autobin fails in WGS mode

### ISSUE THREAD

**Issue by OgnjenSB** [etal/cnvkit#289]
Hi! Autobin keeps failing on the command:

cnvkit.py autobin --method wgs /sbgenomics/Projects/8c9116a9-502c-4732-83b8-0771eb061c44/HCC1143.gathered.bam

The error log is:

2017-12-06T11:50:34.138205058Z Indexing BAM file /sbgenomics/Projects/8c9116a9-502c-4732-83b8-0771eb061c44/HCC1143.gathered.bam
2017-12-06T12:34:07.749612665Z Estimated read length 101.0
2017-12-06T12:34:07.753839052Z Traceback (most recent call last):
2017-12-06T12:34:07.753846245Z   File "/usr/local/bin/cnvkit.py", line 13, in <module>
2017-12-06T12:34:07.753850129Z     args.func(args)
2017-12-06T12:34:07.753853471Z   File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 353, in _cmd_autobin
2017-12-06T12:34:07.759711437Z     do_split=True, avg_size=tgt_bin_size)
2017-12-06T12:34:07.759719229Z   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 14, in do_target
2017-12-06T12:34:07.760150315Z     tgt_arr = bait_arr.copy()
2017-12-06T12:34:07.760156191Z AttributeError: 'NoneType' object has no attribute 'copy'

I tried with different samples as well, same error. Can you help me fix this? Thanks in advance!

**Comment by etal** [comment]
Currently, `autobin` in `wgs` mode needs the `-g`/`--access` option with a BED file of sequencing-accessible regions, which you can produce with the `access` command and your reference genome FASTA sequence.

I'll look into having `autobin` either generate this file, or at least produce a meaningful error when it's missing.

**Comment by OgnjenSB** [comment]
Just let me point out that your documentation page also gives a use case without access:

cnvkit.py autobin *.bam -m wgs -b 50000 --annotate refFlat.txt

Also, batch for me at the instance fails silently in wgs mode when similar inputs are provided. Would that be automatically fixed once autobin is changed?

**Comment by etal** [comment]
Thanks for catching these issues. I've updated the documentation to add `-g` to the autobin WGS example.

I'll make sure `batch` handles this portion of the WGS safely -- at this point the `batch` command should have all the information it needs to run `autobin` with the accessible regions. For the `autobin` command itself, I'll have it handle the case where `-g` is missing by using the full length of each chromosome instead.

I still recommend using the access BED file with `autobin` -- for the human genome, at least, the accessible regions are only about 2/3 of the total genome size, so without it the `autobin` bin size estimates would be up to 50% larger than ideal.
