### ISSUE TITLE
Not working in python 3?

### ISSUE THREAD

**Issue by dawe** [etal/cnvkit#3]
I've installed cnvkit using pip, at first run it raises a SyntaxError:

```
$ cnvkit.py -h
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/cnvkit.py", line 5, in <module>
    from cnvlib import commands
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cnvlib/__init__.py", line 1, in <module>
    from .cnarray import CopyNumArray as _CNA
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cnvlib/cnarray.py", line 11, in <module>
    from . import core, metrics, ngfrills, smoothing
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cnvlib/core.py", line 9, in <module>
    from .ngfrills import echo, safe_write
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cnvlib/ngfrills.py", line 407
    except OSError, exc:
                  ^
SyntaxError: invalid syntax
```

After correction of entries in python3 syntax (i.e. `OSError, exc` becomes `OSError as exc`) I have

```
$ cnvkit.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/cnvkit.py", line 9, in <module>
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by etal** [comment]
CNVkit isn't currently designed to work on Python 3, but thanks for bringing this up. If you have a changeset that improves Python 3 compatibility, I'll see if I can merge it.

It looks like argparse has changed in some crucial way between Pythons 2.7 and 3.x, and that will require some futher investigation.

**Comment by mpschr** [comment]
Hi - I have created a pull request with python3 compatibility
 #100

**Comment by mpschr** [comment]
I guess this can be closed @etal
