### ISSUE TITLE
python3 compatibility issue in example

### ISSUE THREAD

**Issue by davisem** [etal/cnvkit#310]
in the plots example:
```
segments = map(cnvlib.read, glob("*.cns"))
```
```
Traceback (most recent call last):
  File "../../p_cnvkit/rNd/make_heatmap.py", line 46, in <module>
    ax = cnvlib.do_heatmap(segments, do_desaturate=True)
  File "/Users/edavis5/workspace/cnvkit/cnvlib/heatmap.py", line 23, in do_heatmap
    axis.set_yticks([i + 0.5 for i in range(len(cnarrs))])
TypeError: object of type 'map' has no len()
```
map returns an iterator in Python 3x, so you would need to:
```
segments = list(map(cnvlib.read, glob("*.cns")))
```

**Comment by etal** [comment]
Thanks for catching. I might convert it to a list comprehension in the docs to reduce parenthesis overload.
