### ISSUE TITLE
segmetrics commad fails

### ISSUE THREAD

**Issue by tushardave26** [etal/cnvkit#327]
Hello Eric,

I am trying to run the `segmetrics` command on `*.cnr` and `*.cns` files but it produced the error. Below is my command line and error message.

```bash
#command line
$ ~/packages//cnvkit/cnvkit.py segmetrics 745_a.cnr -s 745_a.cns --ci
```

```bash
#error message
Traceback (most recent call last):
  File "/home/tushardave26/packages//cnvkit/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/tushardave26/packages/cnvkit/cnvlib/commands.py", line 1259, in _cmd_segmetrics
    args.interval_stats, args.alpha, args.bootstrap)
  File "/home/tushardave26/packages/cnvkit/cnvlib/segmetrics.py", line 42, in do_segmetrics
    for statname in location_stats:
TypeError: 'NoneType' object is not iterable
```
Can you please help me to understand the problem and probably help to figure out the solution?

Thanks for your help.

**Comment by tushardave26** [comment]
@etal -- sorry for duplication of the issue. I will close this issue write away.
