### ISSUE TITLE
cnvkit.py segment Sample.cnr -o Sample.cns  Suddenly went out

### ISSUE THREAD

**Issue by BioLiu** [etal/cnvkit#328]
I got  the following error and can't figure out what is going on.
Segmenting with method 'cbs', significance threshold 0.0001, in 16 processes
....
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/public/software/anaconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/public/software/anaconda3/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/public/software/anaconda3/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/public/software/biosoft/cnvkit-master/cnvlib/segmentation/__init__.py", line 76, in _ds
    return _do_segmentation(*args)
  File "/public/software/biosoft/cnvkit-master/cnvlib/segmentation/__init__.py", line 119, in _do_segmentation
    seg_out = core.call_quiet('Rscript', '--vanilla', script_fname)
  File "/public/software/biosoft/cnvkit-master/cnvlib/core.py", line 36, in call_quiet
    % (' '.join(args), err))
RuntimeError: Subprocess command failed:
$ Rscript --vanilla /tmp/3057.1.sens1/tmpldwnbnc2

b'/public/software//apps/R/3.2.1/lib64/R/bin/exec/R: symbol lookup error: /public/software//anaconda3/lib/libreadline.so.6: undefined symbol: PC\n'
"""
Thank you very much for your kindly support.

**Comment by etal** [comment]
It look like one of the supporting libraries for your R installation might be out of date. If you run segmentation with just 1 process it should be easier to see the full traceback. For troubleshooting, you could also try running CBS separately in an interactive R session. Maybe just `library("DNAcopy")` in R would reveal the error. In any case, if it's an out-of-date library, updating your installed packages (R and conda) and checking paths would usually be the solution.

**Comment by BioLiu** [comment]
When using 1 process, I got the  message followed.  My R version is 3.2.1, I update the ```DNAcopy```, it still doesn't work well.

Segmenting with method 'cbs', significance threshold 0.0001, in 1 processes
...
Traceback (most recent call last):
  File "/public/software/biosoft/cnvkit-master/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/public/software/biosoft/cnvkit-master/cnvlib/commands.py", line 605, in _cmd_segment
    processes=args.processes)
  File "/public/software/biosoft/cnvkit-master/cnvlib/segmentation/__init__.py", line 52, in do_segmentation
    for _, ca in cnarr.by_arm())))
  File "/public/software/biosoft/cnvkit-master/cnvlib/segmentation/__init__.py", line 76, in _ds
    return _do_segmentation(*args)
  File "/public/software/biosoft/cnvkit-master/cnvlib/segmentation/__init__.py", line 119, in _do_segmentation
    seg_out = core.call_quiet('Rscript', '--vanilla', script_fname)
  File "/public/software/biosoft/cnvkit-master/cnvlib/core.py", line 36, in call_quiet
    % (' '.join(args), err))
RuntimeError: Subprocess command failed:
$ Rscript --vanilla /tmp/3097.1.sens1/tmptloeaj_c

b'/public/software//apps/R/3.2.1/lib64/R/bin/exec/R: symbol lookup error: /public/software//anaconda3/lib/libreadline.so.6: undefined symbol: PC\n'

**Comment by etal** [comment]
I've seen an error like this on OS X. The problem or similar ones appear in a few other issue trackers:
https://github.com/conda-forge/r-feedstock/issues/2
https://github.com/conda-forge/rpy2-feedstock/issues/1
https://github.com/COMBINE-lab/salmon/issues/147
https://github.com/bioconda/bioconda-recipes/issues/5350

Installing or updating `readline` through conda might fix it.
