### ISSUE TITLE
Option to not re-index reference fasta

### ISSUE THREAD

**Issue by sheenams** [etal/cnvkit#344]
My reference genome fasta is already indexed, and in a read-only folder. cnkit.py (via pyfaidx) is attempting to re-create this file and failing:

Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 107, in _cmd_batch
    args.count_reads, args.method)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/batch.py", line 147, in batch_make_reference
    do_rmask=True)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/reference.py", line 55, in do_reference
    do_gc, do_edge, False)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/reference.py", line 160, in combine_probes
    gc, rmask = get_fasta_stats(cnarr1, fa_fname)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/reference.py", line 312, in get_fasta_stats
    for subseq in fasta_extract_regions(fa_fname, cnarr)]
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/reference.py", line 337, in fasta_extract_regions
    with pyfaidx.Fasta(fa_fname, as_raw=True) as fa_file:
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 853, in __init__
    sequence_always_upper=sequence_always_upper, rebuild=rebuild)
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 370, in __init__
    self.build_index()
  File "/usr/local/lib/python2.7/dist-packages/pyfaidx/__init__.py", line 502, in build_index
    raise IOError("%s may not be writable. Please use Fasta(rebuild=False), Faidx(rebuild=False) or faidx --no-rebuild." % self.indexname)
IOError: /mnt/disk2/com/Genomes/gatk-bundle/human_g1k_v37.fasta.fai may not be writable. Please use Fasta(rebuild=False), Faidx(rebuild=False) or faidx --no-rebuild.

/mnt/disk2/com/Genomes/gatk-bundle/human_g1k_v37.fasta.fai  already exists 

Is there a way to get around this?

**Comment by etal** [comment]
If you can update the timestamp on the .fai file so that it has a later modification time than the corresponding .fasta, then CNVkit will accept it as up-to-date and won't try to rebuild the index.

**Comment by etal** [comment]
I agree it's not ideal behavior. I'll see about silencing the error and just printing a warning if the index is already available, older than the .fasta, but not in a writeable location.

**Comment by sheenams** [comment]
Perfect! Updating the timestamp did the trick. Thanks!

**Comment by auberginekenobi** [comment]
A note that the symbolic link suggestion didn't work for me - pyfaidx checks the dates of the linked files. I copied the .fai because it's small and left the linked .fasta unchanged.
