### ISSUE TITLE
import-rna implies normal samples are optional but they are not

### ISSUE THREAD

**Issue by lbeltrame** [etal/cnvkit#355]
At least when using gene counts (I actually used rsem, but I don't have access to the result files right now):

```
cnvkit.py import-rna test.data.txt --gene-resource ensembl-gene-info.hg38.tsv --correlations tcga-skcm.cnv-expr-corr.tsv  --output summary.tsv --output-dir out/ -f counts
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1443, in _cmd_import_rna
    args.normal)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/import_rna.py", line 19, in do_import_rna
    gene_count_fnames = sorted(set(gene_count_fnames) + set(normal_fnames))
TypeError: 'NoneType' object is not iterable
```

That's because `normal_fnames` is `None`.

If they are required, the documentation should be adjusted accordingly.

**Comment by lbeltrame** [comment]
That commit isn't yet in any tagged release, so reopening.

**Comment by lbeltrame** [comment]
At least with counts, it looks like normal samples are **required**. `align_gene_info_to_samples` will run a normalization step using normals: if there aren't (empty list) this will trigger an assert in `normalize_read_depths`.
