### ISSUE TITLE
Missing values in Entrez IDs ensembl-gene-info.hg38.tsv will make import-rna fail

### ISSUE THREAD

**Issue by lbeltrame** [etal/cnvkit#356]
That's because the missing IDs will be converted to NaNs, thus causing the values to become floats, and ultimately causing an error when joining:

```python

cnvkit.py import-rna test.data.txt --gene-resource ensembl-gene-info.hg38.tsv --correlations tcga-skcm.cnv-expr-corr.tsv  --output summary.tsv --output-dir out/ -f counts
Dropping 156 / 58254 rarely expressed genes from input samples
Loading gene metadata and TCGA gene expression/CNV profiles
Loaded ensembl-gene-info.hg38.tsv with shape: (221323, 9)
Loaded tcga-skcm.cnv-expr-corr.tsv with shape: (19177, 4)
Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/cnvlib/commands.py", line 1443, in _cmd_import_rna
    args.normal)
  File "/usr/local/lib/python3.6/site-packages/cnvlib/import_rna.py", line 33, in do_import_rna
    gene_info = rna.load_gene_info(gene_resource_fname, correlations_fname)
  File "/usr/local/lib/python3.6/site-packages/cnvlib/rna.py", line 83, in load_gene_info
    gi_corr = gene_info.join(corr_table, on='entrez_id', how='left')
  File "/usr/lib64/python3.6/site-packages/pandas/core/frame.py", line 6326, in join
    rsuffix=rsuffix, sort=sort)
  File "/usr/lib64/python3.6/site-packages/pandas/core/frame.py", line 6341, in _join_compat
    suffixes=(lsuffix, rsuffix), sort=sort)
  File "/usr/lib64/python3.6/site-packages/pandas/core/reshape/merge.py", line 60, in merge
    validate=validate)
  File "/usr/lib64/python3.6/site-packages/pandas/core/reshape/merge.py", line 554, in __init__
    self._maybe_coerce_merge_keys()
  File "/usr/lib64/python3.6/site-packages/pandas/core/reshape/merge.py", line 978, in _maybe_coerce_merge_keys
    raise ValueError(msg)
ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat
```

**Comment by lbeltrame** [comment]
This is currently fixed in master, as far as I can see.
