### ISSUE TITLE
pooled reference with duplicated genomic coordinates

### ISSUE THREAD

**Issue by yisu-li** [etal/cnvkit#376]
Hi there,

I am using cnvkit 0.9.4.dev0. I've gotten the following error message when I try to run cnvkit.py fix against a pooled reference.  This only happens with pooled references.  It worked fine with matched reference.  Any suggestion?
```
Traceback (most recent call last):
  File "/home/yisuli/opt/Python-3.6.6/bin/cnvkit.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/yisuli/software/cnvkit/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/yisuli/software/cnvkit/cnvlib/commands.py", line 583, in _cmd_fix
    args.do_gc, args.do_edge, args.do_rmask)
  File "/home/yisuli/software/cnvkit/cnvlib/fix.py", line 19, in do_fix
    do_gc, do_edge, False)
  File "/home/yisuli/software/cnvkit/cnvlib/fix.py", line 64, in load_adjust_coverages
    ref_matched = match_ref_to_sample(ref_cnarr, cnarr)
  File "/home/yisuli/software/cnvkit/cnvlib/fix.py", line 131, in match_ref_to_sample
    " set:\n" + "\n".join(map(str, dset.index[dupes])))
ValueError: Duplicated genomic coordinates in reference set:
```

**Comment by etal** [comment]
Can you show the command you used to construct the reference?

**Comment by yisu-li** [comment]
Hi @etal,

Thanks for the reply.  I've resolved this issue with regenerating our target bed file, which had duplicated entries. 

Thanks,
Yisu
