### ISSUE TITLE
Issues generating ref.cnn from hg1k_v37

### ISSUE THREAD

**Issue by robrollback** [etal/cnvkit#38]
Hi,

I am testing out your program using 1000G version of hg19 and I am receiving the following error for cvnkit 0.6.1.  

Number of target and antitarget files: 1, 1
Loading germline.targetcoverage.cnn
/lb/project/mugqic/analyste_dev/software/python/Python-2.7.8/lib/python2.7/site-packages/pandas/io/parsers.py:1170: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)
Calculating GC and RepeatMasker content in /lb/project/mugqic/analyste_dev/genomes/Homo_sapiens/hg1k_v37/fasta/hg1k_v37.fasta ...
Traceback (most recent call last):
  File "/home/reveleig/github/cnvkit/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/sb/home/reveleig/github/cnvkit/cnvlib/commands.py", line 498, in _cmd_reference
    args.male_reference)
  File "/sb/home/reveleig/github/cnvkit/cnvlib/commands.py", line 518, in do_reference
    male_reference)
  File "/sb/home/reveleig/github/cnvkit/cnvlib/reference.py", line 50, in combine_probes
    gc, rmask = get_fasta_stats(cnarr1, fa_fname)
  File "/sb/home/reveleig/github/cnvkit/cnvlib/reference.py", line 189, in get_fasta_stats
    fa_coords)]
  File "/sb/home/reveleig/github/cnvkit/cnvlib/ngfrills/faidx.py", line 71, in fasta_extract_regions
    + "file " + str(fa_fname))
ValueError: Sequence ID '1' is not in FASTA file /lb/project/mugqic/analyste_dev/genomes/Homo_sapiens/hg1k_v37/fasta/hg1k_v37.fasta

Thanks for any help you can provide.

Best,
 Rob E.

**Comment by etal** [comment]
Hi Rob,

This error would happen if your target BED file, and therefore the target and antitarget .cnn files, had integer chromosome names with no "chr" prefix, but the reference genome FASTA file does have the "chr" prefix in the sequence names. If that's the case (just check if the BED file has "1" instead of "chr1"), you can fix this by adding "chr" to the beginning of each line in your BED file, then re-running the pipeline.

Best,
Eric
