### ISSUE TITLE
error while performing test

### ISSUE THREAD

**Issue by cnizo** [etal/cnvkit#397]
Hi @etal!

I ran into an error while performing the test. Here is the log:
```
Treating sample p2-5_5.call as male
Treating sample p2-9_2.call as male
Treating sample p2-20_1.call as male
Treating sample p2-20_2.call as male
Treating sample p2-20_3.call as male
Treating sample p2-20_4.call as male
Treating sample p2-20_5.call as male
Wrote p2-all.bed
python ../cnvkit.py export vcf -o p2-9_2.vcf -y --cnr build/p2-9_2.cnr build/p2-9_2.call.cns -y -o p2-9_2.vcf
Treating sample p2-9_2.call as male
Traceback (most recent call last):
  File "../cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/varianttools/bioinfo/app/cnvkit/cnvlib/commands.py", line 1625, in _cmd_export_vcf
    is_sample_female, args.sample_id, cnarr)
  File "/home/varianttools/bioinfo/app/cnvkit/cnvlib/export.py", line 237, in export_vcf
    segments = assign_ci_start_end(segments, cnarr)
  File "/home/varianttools/bioinfo/app/cnvkit/cnvlib/export.py", line 261, in assign_ci_start_end
    ci_lefts, ci_rights = zip(*lefts_rights)
  File "/home/varianttools/bioinfo/app/cnvkit/cnvlib/export.py", line 260, in <genexpr>
    for _seg, bins in cnarr.by_ranges(segarr, mode="outer"))
  File "/home/varianttools/_env/lib/python3.5/site-packages/pandas/core/indexing.py", line 1869, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/varianttools/_env/lib/python3.5/site-packages/pandas/core/series.py", line 928, in _get_value
    return _maybe_box_datetimelike(self._values[label])
IndexError: index 0 is out of bounds for axis 0 with size 0
Makefile:148: recipe for target 'p2-9_2.vcf' failed
make: *** [p2-9_2.vcf] Error 1
```
Do you have an idea of what it might be? I have just cloned the repository and I have already tried doing``` make clean; make all```

**Comment by etal** [comment]
Thanks for letting me know. It looks like `export vcf` thinks one of its input files, or some component, is empty. Did segmentation work correctly, i.e. the .cns files list multiple segments, at least one per chromosome?

**Comment by cnizo** [comment]
yes, both have segmentations listed. I also ran ```make test``` and got errors in test_ranges_by_in, test_ranges_of and test_substract as you can see:

```python test_genome.py
test_autosomes (__main__.GaryTests)
Test selection of autosomes. ... ok
test_by_chromosome (__main__.GaryTests) ... ok
test_copy (__main__.GaryTests)
Test creation of an independent copy of the object. ... ok
test_empty (__main__.GaryTests)
Instantiate from an empty file. ... ok
test_filter (__main__.GaryTests)
Test sugary selection of a subset of the data array. ... ok
test_iter (__main__.GaryTests)
Test iteration. ... ok
test_ranges_by_in (__main__.GaryTests)
Test range methods: by_ranges, in_range, in_ranges. ... FAIL
test_ranges_into (__main__.GaryTests) ... ok
test_ranges_of (__main__.GaryTests) ... FAIL
test_ranges_resize (__main__.GaryTests) ... ok
test_shuffle_sort (__main__.GaryTests)
Test shuffling and re-sorting the data array. ... ok
test_total_range_size (__main__.GaryTests)
Test total region coverage calculation. ... ok
test_flatten (__main__.IntervalTests) ... ok
test_intersect (__main__.IntervalTests) ... ok
test_merge (__main__.IntervalTests) ... ok
test_subtract (__main__.IntervalTests) ... FAIL
test_chromsort (__main__.OtherTests) ... ok
test_detect_big_chroms (__main__.OtherTests) ... ok
test_rangelabel (__main__.OtherTests) ... ok
```
I don't know if it is useful but here is the last piece of log I had:
```
Traceback (most recent call last):
  File "test_genome.py", line 524, in test_subtract
    self._compare_regions(result, expect)
  File "test_genome.py", line 242, in _compare_regions
    "Expected:", str(expect.data)]))
AssertionError: Tuples differ: (3, 4) != (5, 4)

First differing element 0:
3
5

- (3, 4)
?  ^

+ (5, 4)
?  ^
 : Got:
  chromosome  start  end gene
0       chr0      5    7     
1       chr0     13   14     
2       chr0     17   20     
3       chr0     24   26     
4       chr0     28   31     
Expected:
  chromosome  start  end gene
0       chr0     17   19     
1       chr0     24   26     
2       chr0     28   31 
```

**Comment by cnizo** [comment]
Thank you for the answer!
I ended up running the vcf export command with some files I had and it worked!
Maybe it is something with the test files

**Comment by etal** [comment]
The underlying issue here (#393) is now fixed in the development version, and will be in the next CNVkit release.
