### ISSUE TITLE
errors during using access command 

### ISSUE THREAD

**Issue by ZKai0801** [etal/cnvkit#404]
Hi,

I'm trying to use access command to calculate the sequence accessible coordinates from hg19 Fasta file. This error message prompted when the program tried to joining over small gaps. 

Here is the command I used:
```
$ python3 cnvkit.py hg19.fa -x filename.bed -o output.bed
```

Here is my error message:

```
chr1: Joining over small gaps
Traceback (most recent call last):
  File "/public/home/kai/softwares/cnvkit/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/public/home/kai/softwares/cnvkit/cnvlib/commands.py", line 276, in _cmd_access
    args.min_gap_size)
  File "/public/home/kai/softwares/cnvkit/cnvlib/access.py", line 28, in do_access
    return GA.from_rows(join_regions(access_regions, min_gap_size))
  File "/public/home/kai/softwares/cnvkit/skgenome/gary.py", line 86, in from_rows
    table = pd.DataFrame.from_records(rows, columns=columns)
  File "/public/software/python3.7.1/lib/python3.7/site-packages/pandas/core/frame.py", line 1238, in from_records
    values += data
  File "/public/home/kai/softwares/cnvkit/cnvlib/access.py", line 113, in join_regions
    % (chrom, prev_start, prev_end, start, end, gap))
AssertionError: Impossible gap between chr1 10000-564449 and 227417-564449 (=-337032)
```

This error message did not shown when I used -s flag instead.

**Comment by etal** [comment]
Thanks for letting me know, I'll look into it. Did `hg19.fa` come from UCSC, and is there anything unusual about `filename.bed`?

**Comment by ZKai0801** [comment]
Hi Dr. Talevich,

Thanks for your reply. 
Yes, hg19.fa came from UCSC. Actually, the filename.bed came from UCSC as well. I used the file ```wgEncodeDukeMapabilityRegionsExcludable.bed``` suggested in your website, which I believe shouldn't have any problem.

The bed file looks like this:
```
chr1	10468	11447	TAR1	1000	.
chr1	564463	570304	chrM	1000	.
chr1	724137	727026	(GAATG)n	1000	.
chr1	825006	825115	BSR/Beta	1000	.
chr1	1815107	1815204	LSU-rRNA_Hsa	1000	.
chr1	3639224	3639747	TAR1	1000	.
chr1	4363064	4363242	(CATTC)n	1000	.
chr1	4417098	4417211	LSU-rRNA_Hsa	1000	.
chr1	16393109	16393136	(GAATG)n	1000	.
chr1	17562054	17562204	TAR1	1000	.
chr1	17568001	17568197	(GAATG)n	1000	.
chr1	22699407	22699475	(GAATG)n	1000	.
chr1	25483508	25483621	LSU-rRNA_Hsa	1000	.
chr1	28242609	28242680	LSU-rRNA_Hsa	1000	.
chr1	30802098	30802177	LSU-rRNA_Hsa	1000	.
chr1	31254019	31254168	(GAGTG)n	1000	.
chr1	32833269	32833349	SSU-rRNA_Hsa	1000	.
```

**Comment by etal** [comment]
I wasn't able to replicate this issue just now on my own machine with the same files. I'm guessing that this is fixed now -- please let me know if this still isn't working for you.
