### ISSUE TITLE
RNASeq CNVkit error

### ISSUE THREAD

**Issue by fnmirza** [etal/cnvkit#410]
I am new to CNVkit and have tried to run it on RNASeq counts. I am running 

`cnvkit.py import-rna -f counts -g ~/Desktop/CNV/ensembl-gene-info.hg38.tsv -c ~/Desktop/CNV/tcga-skcm.cnv-expr-corr.tsv -n ~/Desktop/CNV/controls/*.txt -o output.txt ~/Desktop/CNV/samples/*.txt`

My output is as follows:
> Dropping 39717 / 125196 rarely expressed genes from input samples
Loading gene metadata and TCGA gene expression/CNV profiles
Loaded /Users/username/Desktop/CNV/ensembl-gene-info.hg38.tsv with shape: (221323, 9)
Loaded /Users/username/Desktop/CNV/tcga-skcm.cnv-expr-corr.tsv with shape: (19177, 4)
Resetting 2846 ambiguous genes' correlation coefficients to default 0.100000
Trimmed gene info table to shape: (63966, 13)
Aligning gene info to sample gene counts
Weighting genes with below-average read counts
Calculating normalized gene read depths
Traceback (most recent call last):
  File "/Users/username/anaconda2/envs/cnvkit/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/cnvlib/commands.py", line 1467, in _cmd_import_rna
    args.normal, args.do_gc, args.do_txlen, args.max_log2)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/cnvlib/import_rna.py", line 39, in do_import_rna
    gene_info, sample_counts, tx_lengths, normal_ids)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/cnvlib/rna.py", line 272, in align_gene_info_to_samples
    axis=0),
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/pandas/core/ops.py", line 1554, in f
    level=level, try_cast=True)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/pandas/core/ops.py", line 1424, in _combine_series_frame
    return self._combine_match_index(other, func, level=level)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/pandas/core/frame.py", line 4761, in _combine_match_index
    copy=False)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/pandas/core/frame.py", line 3550, in align
    broadcast_axis=broadcast_axis)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/pandas/core/generic.py", line 7372, in align
    fill_axis=fill_axis)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/pandas/core/generic.py", line 7458, in _align_series
    fdata = fdata.reindex_indexer(join_index, lidx, axis=1)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/pandas/core/internals.py", line 4414, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/Users/username/anaconda2/envs/cnvkit/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 3576, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis

I am unsure what this ValueError is and how to resolve it. Any insight would be greatly appreciated. 

For background, my input files were generated using quantification to annotation model (Partek E/M), hg38, Ensembl in Partek Flow.

**Comment by etal** [comment]
Sorry for the trouble. Can you check if your sample input files have any duplicate gene names/IDs in them? That might have caused the error here.

**Comment by fnmirza** [comment]
Thank you for your response - summing the counts and collapsing by gene identifier did solve the issue.

As an additional question, is it typical for the ztest command to exclusively output log2 values less than zero?

Many thanks for your consideration.
