### ISSUE TITLE
Unable to use guess_bait.py unguided mode

### ISSUE THREAD

**Issue by ZKai0801** [etal/cnvkit#415]
Hi,

I tried to use the unguided mode for `guess_bait.py`, however, I encountered a bug about failing to provide a file. 

The error message I got looks like this:

```
[kai@admin] python2 guess_bait.py XXXX.bam -a access-10kb.hg19.bed -o output_bait.bed
Scanning for enriched regions in:
  NGS180428T-10SD.sorted.bam
Traceback (most recent call last):
  File "/public/software/cnvkit/scripts/guess_baits.py", line 250, in <module>
    args.min_gap, args.min_length, args.processes)
  File "/public/software/cnvkit/scripts/guess_baits.py", line 77, in scan_targets
    for bed_chunk_fname, bait_chunk in pool.map(_scan_depth, args_iter):
  File "/public/software/cnvkit/cnvlib/parallel.py", line 26, in map
    return map(func, iterable)
  File "/public/software/cnvkit/scripts/guess_baits.py", line 91, in _scan_depth
    min_length))
  File "/public/software/cnvkit/scripts/guess_baits.py", line 174, in <genexpr>
    return (reg for reg in regions
  File "/public/software/cnvkit/scripts/guess_baits.py", line 159, in merge_gaps
    prev = next(regions)
  File "/public/software/cnvkit/scripts/guess_baits.py", line 122, in scan_depth
    shell=False)
  File "/public/software/python2.7.15/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/public/software/python2.7.15/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Also, FYI, there is a typo in your manual. Under `guess_bait.py` section, you utilised `-g` to accept accessible genomic regions, however, I think it should be `-a`.

Thank you very much for your time!

**Comment by etal** [comment]
Thanks for reporting this bug. The unguided mode is not well tested; I've generally gotten better results from giving all exons in guided mode.

**Comment by ZKai0801** [comment]
Thanks for your suggestion! That's exactly how I did.
