### ISSUE TITLE
I am not able to install this software

### ISSUE THREAD

**Issue by beginner984** [etal/cnvkit#423]
Sorry, 

Whatever I am trying I am getting error in installation help me please

```
(py3venv) [fi1d18@cyan01 test]$ make
python ../cnvkit.py segment -p 2 --drop-low-coverage -t .01 build/p2-5_5.cnr -o build/p2-5_5.cns
/home/fi1d18/cnvkit/skgenome/tabio/tab.py:19: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  dframe = pd.read_table(infile, dtype={'chromosome': 'str'})
Segmenting with method 'cbs', significance threshold 0.01, in 2 processes
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/fi1d18/cnvkit/cnvlib/core.py", line 28, in call_quiet
    stderr=subprocess.PIPE)
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Rscript': 'Rscript'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/fi1d18/cnvkit/cnvlib/segmentation/__init__.py", line 87, in _ds
    return _do_segmentation(*args)
  File "/home/fi1d18/cnvkit/cnvlib/segmentation/__init__.py", line 159, in _do_segmentation
    seg_out = core.call_quiet(rscript_path, '--vanilla', script_fname)
  File "/home/fi1d18/cnvkit/cnvlib/core.py", line 32, in call_quiet
    + "\n(Original error: %s)" % exc)
RuntimeError: Could not find the executable 'Rscript' -- is it installed correctly?
(Original error: [Errno 2] No such file or directory: 'Rscript': 'Rscript')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/fi1d18/cnvkit/cnvlib/commands.py", line 635, in _cmd_segment
    processes=args.processes)
  File "/home/fi1d18/cnvkit/cnvlib/segmentation/__init__.py", line 62, in do_segmentation
    for _, ca in cnarr.by_arm())))
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/fi1d18/.conda/envs/py3venv/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: Could not find the executable 'Rscript' -- is it installed correctly?
(Original error: [Errno 2] No such file or directory: 'Rscript': 'Rscript')
make: *** [build/p2-5_5.cns] Error 1

```

**Comment by messersc** [comment]
Hi,

not the maintainer, but I can help.

`(Original error: [Errno 2] No such file or directory: 'Rscript': 'Rscript')` points to a missing R installation.

```
which Rscript
```
should come up empty.

I encourage you to look into miniconda (https://docs.conda.io/en/latest/miniconda.html) and bioconda, which makes things much easier. The bioconda package of cnvkit does have R installed as a dependency https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cnvkit/meta.yaml.

Your other option is of course to follow the installation manual closely.

Cheers,
Clemens

**Comment by beginner984** [comment]
Thank you for helping me

You please meant that I should save and run this script as .py

**Comment by messersc** [comment]
Rscript is an executable. It's meant to run scripts written in the programming language R. This is needed for some of the segmentation algorithms in cnvkit.

You need to have R installed, so Rscript will be available.

In bash, if you run 
```
which R
which Rscript
```

this will not yield any path to these executables.

**Comment by etal** [comment]
Yes, I recommend following the standard installation steps here:
https://github.com/etal/cnvkit#using-conda

If that doesn't work, then installing R separately with conda or your system's package manager should solve the Rscript issue.
