### ISSUE TITLE
pandas dtype error while trying to use scatter with a vcf file

### ISSUE THREAD

**Issue by aarslank** [etal/cnvkit#426]
I'm trying to use the scatter option like this: 

cnvkit.py scatter -s myCNS.cns -v myVCF.vcf -o myPlot.png

I'm on version 0.9.6.dev0. Happy to provide more details. 

This is the output I'm seeing: 
```
Loaded 3125 records; skipped: 0 somatic, 0 depth
Traceback (most recent call last):
  File "/packages/cnvkit/0.1/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/data/packages/cnvkit/0.1/cnvlib/commands.py", line 884, in _cmd_scatter
    args.min_variant_depth, args.zygosity_freq)
  File "/data/packages/cnvkit/0.1/cnvlib/cmdutil.py", line 25, in load_het_snps
    skip_somatic=True)
  File "/data/packages/cnvkit/0.1/skgenome/tabio/__init__.py", line 85, in read
    result = (into or suggest_into)(dframe, meta)
  File "/data/packages/cnvkit/0.1/cnvlib/vary.py", line 21, in __init__
    GenomicArray.__init__(self, data_table, meta_dict)
  File "/data/packages/cnvkit/0.1/skgenome/gary.py", line 56, in __init__
    data_table[col] = data_table[col].astype(dtype)
  File "/packages/python-2.7.5/lib/python2.7/site-packages/pandas/core/generic.py", line 5691, in astype
    **kwargs)
  File "/packages/python-2.7.5/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 531, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/packages/python-2.7.5/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 395, in apply
    applied = getattr(b, f)(**kwargs)
  File "/packages/python-2.7.5/lib/python2.7/site-packages/pandas/core/internals/blocks.py", line 534, in astype
    **kwargs)
  File "/packages/python-2.7.5/lib/python2.7/site-packages/pandas/core/internals/blocks.py", line 595, in _astype
    dtype = pandas_dtype(dtype)
  File "/packages/python-2.7.5/lib/python2.7/site-packages/pandas/core/dtypes/common.py", line 2029, in pandas_dtype
    raise TypeError("dtype '{}' not understood".format(dtype))
TypeError: dtype '<class 'future.types.newstr.newstr'>' not understood

```
Thank you for your help in advance.

**Comment by etal** [comment]
Thanks for reporting. Are you using the most recent stable version of pandas, v.0.24.2?

**Comment by etal** [comment]
I think this issue was fixed in the development branch by this PR:
https://github.com/etal/cnvkit/pull/413

Could you try the development version now with a fresh pull from GitHub?
