### ISSUE TITLE
weight zero error in genemetrics

### ISSUE THREAD

**Issue by ZKai0801** [etal/cnvkit#439]
Hi etal,
I tried to run `genemetrics` command to get CNA on gene-scale, but got the following error:
```
Treating sample NGS190413-8DU as male
Traceback (most recent call last):
  File "/data/ngs/softs/cnvkit/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/data/ngs/softs/cnvkit/cnvlib/commands.py", line 1108, in _cmd_genemetrics
    is_sample_female)
  File "/data/ngs/softs/cnvkit/cnvlib/reports.py", line 94, in do_genemetrics
    rows = list(rows)
  File "/data/ngs/softs/cnvkit/cnvlib/reports.py", line 133, in gene_metrics_by_segment
    for row in group_by_genes(subprobes, skip_low):
  File "/data/ngs/softs/cnvkit/cnvlib/reports.py", line 157, in group_by_genes
    segmean = segment_mean(rows, skip_low)
  File "/data/ngs/softs/cnvkit/cnvlib/segmetrics.py", line 190, in segment_mean
    return np.average(cnarr['log2'], weights=cnarr['weight'])
  File "/home/ionadmin/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 386, in average
    "Weights sum to zero, can't be normalized")
ZeroDivisionError: Weights sum to zero, can't be normalized
```
It looks like the problem was caused by having 0 on column "weight" in the cnr file. Is there a way to solve this problem? I would be very appreciated if you can help!
Thanks!

**Comment by etal** [comment]
I think I might have fixed that recently. Are you using the latest version of CNVkit, 0.9.6, or the development version from github?

**Comment by ZKai0801** [comment]
Hi etal,

I pulled the most recent development version from github, and now the command `genemetrics` works fine!

Thanks!
