### ISSUE TITLE
Bytes-like object required error with guess_baits.py 

### ISSUE THREAD

**Issue by GlyphDataServices** [etal/cnvkit#442]
Getting this error:

`guess_baits.py -a hg38_accessibleRegions.bed -c guessed-coverage.cnn -o guessed-baits.bed Control-mapped-sorted-mkdup.bam`

Scanning for enriched regions in:
  Control-mapped-sorted-mkdup.bam
Traceback (most recent call last):
  File "/usr/bin/guess_baits.py", line 250, in <module>
    args.min_gap, args.min_length, args.processes)
  File "/usr/bin/guess_baits.py", line 77, in scan_targets
    for bed_chunk_fname, bait_chunk in pool.map(_scan_depth, args_iter):
  File "/usr/bin/guess_baits.py", line 91, in _scan_depth
    min_length))
  File "/usr/bin/guess_baits.py", line 174, in <genexpr>
    return (reg for reg in regions
  File "/usr/bin/guess_baits.py", line 159, in merge_gaps
    prev = next(regions)
  File "/usr/bin/guess_baits.py", line 127, in scan_depth
    fields = line.split('\t')
TypeError: a bytes-like object is required, not 'str'

**Comment by GlyphDataServices** [comment]
My fix is to add universal_newlines=True after line 121.  Not sure if this repo is open for me to make a branch but if you want to add this fix it seems to solve the issue. 

  ```
  proc = subprocess.Popen(['samtools', 'depth',
                             '-Q',  '1',  # Skip pseudogenes
                             '-b', bed_fname,
                            ] + bam_fnames,
                            stdout=subprocess.PIPE,
                            **universal_newlines=True,**
                            shell=False)

```
