### ISSUE TITLE
ValueError import-picard

### ISSUE THREAD

**Issue by bwubb** [etal/cnvkit#453]
Greetings,

  I am having trouble converting the output of Picard CollectHsMetrics into the desired .cnn file format. First, and perhaps Im nitpicking(?), Im confused by the documentation/example. The output of picard tools is tsv not csv; the fifth column of the target_coverage file being a comma separated list of gene/target names. Unless there is some hidden argument I cannot see in the picard documentation. I only mention this point, in case cnvkit is looking for an input file format different from what I produce from CollectHsMetrics (which Im now actually noticing is not Picard "CalculateHsMetrics", which does not exist).

On to the error:

```
[bwubb@node065]$ cnvkit.py import-picard test_target_coverage.txt
Traceback (most recent call last):
  File "/home/bwubb/my_python-3.6.3/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/bwubb/my_python-3.6.3/lib/python3.6/site-packages/cnvlib/commands.py", line 1363, in _cmd_import_picard
    garr = importers.do_import_picard(fname)
  File "/home/bwubb/my_python-3.6.3/lib/python3.6/site-packages/cnvlib/importers.py", line 17, in do_import_picard
    garr = tabio.read(fname, "picardhs")
  File "/home/bwubb/my_python-3.6.3/lib/python3.6/site-packages/skgenome/tabio/__init__.py", line 77, in read
    dframe = reader(infile, **kwargs)
  File "/home/bwubb/my_python-3.6.3/lib/python3.6/site-packages/skgenome/tabio/picard.py", line 55, in read_picard_hs
    "depth", "ratio"]
  File "/home/bwubb/my_python-3.6.3/lib/python3.6/site-packages/pandas/core/generic.py", line 5080, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/bwubb/my_python-3.6.3/lib/python3.6/site-packages/pandas/core/generic.py", line 638, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/bwubb/my_python-3.6.3/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 155, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 14 elements, new values have 8 elements
```
The error looks straight forward enough, but I cannot imagine what I am doing incorrectly. Any help would be greatly appreciated.

Thanks.

EDIT: A look at my picard file:

```
[bwubb@node065]$ head test_target_coverage.txt
chrom   start   end     length  name    %gc     mean_coverage   normalized_coverage     min_normalized_coverage max_normalized_coverage min_coverage    max_coverage    pct_0x  read_count
1       65510   65625   116     -       0.327586        0       0       0       0       0       0       1       0
1       65832   65973   142     -       0.415493        19.838028       0.503227        0.101467        0.659536        4       26      0       49
1       69482   69600   119     ref|OR4F5,ref|NM_001005484,ens|ENST00000335137,ccds|CCDS30547.1 0.512605        0       0       0       0       0       0       1       0
1       721382  721519  138     ens|ENST00000591440,ens|ENST00000591702,ens|ENST00000586288,ens|ENST00000587530,ens|ENST00000586928,ens|ENST00000589531,ens|ENST00000593022,ens|ENST00000590848,ens|ENST00000585745,ens|ENST00000588951,ens|ENST00000585768,ens|ENST00000429505,ens|ENST00000358533,mRNA|AK290103,mRNA|AK125248  0.449275        34.572464       0.876992 0.405868        1.192238        16      47      0       84
1       721531  721806  276     ens|ENST00000591440,ens|ENST00000591702,ens|ENST00000586288,ens|ENST00000587530,ens|ENST00000586928,ens|ENST00000589531,ens|ENST00000593022,ens|ENST00000590848,ens|ENST00000585745,ens|ENST00000588951,ens|ENST00000585768,ens|ENST00000429505,ens|ENST00000358533,mRNA|AK290103,mRNA|AK125248  0.362319        49.224638       1.24867  0.761003        1.57274 30      62      0       180
```

**Comment by etal** [comment]
Thanks for reporting the documentation issues, I'll sort them out.

Here's an example of the type of Picard file CNVkit is expecting here:
https://github.com/etal/cnvkit/blob/master/test/picard/p1-21_1.targetcoverage.csv

I think it's the same format as yours, and `import-picard` works for me locally on this file, so I'm not sure what the problem is/was. There may have been some quirks in indexing behavior in CNVkit 0.9.6, so maybe 0.9.5 would behave better on your system if you need a stable installation right away. (Still triaging some other tickets.)

**Comment by etal** [comment]
Ancient pandas quirk, not reproduced; doc example already exists. Closing as stale — please reopen with a reproduction on a current release if this is still relevant.
