### ISSUE TITLE
there is something wrong with my installation

### ISSUE THREAD

**Issue by batis2ta** [etal/cnvkit#466]
Hi typing this cnvkit.py batch -h would result in the following:
but cnvkit.py -h works fine. what may be the cause ? 
Traceback (most recent call last):
  File "/home/mo/anaconda3/bin/cnvkit.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/mo/cnvkit/cnvkit.py", line 8, in <module>
    args = commands.parse_args()
  File "/home/mo/cnvkit/cnvlib/commands.py", line 1890, in parse_args
    return AP.parse_args(args=args)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 1024, in __call__
    parser.print_help()
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 2366, in print_help
    self._print_message(self.format_help(), file)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 2350, in format_help
    return formatter.format_help()
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 523, in _format_action
    help_text = self._expand_help(action)
  File "/home/mo/anaconda3/lib/python3.6/argparse.py", line 610, in _expand_help
    return self._get_help_string(action) % params
TypeError: %d format: a number is required, not str

**Comment by etal** [comment]
Sorry, this was a typo in the command line options formatting. Fixed.
