### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by shengzha** [etal/cnvkit#492]
I installed cnvkit via conda on linux, as recommended. But envoking cnvkit.py (e.g. `cnvkit.py scatter -h` or just `cnvkit.py`) gave the following error.
`ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

Here is the console log.

```
(base) -bash-4.2$ conda create -n cnvkit cnvkit
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: <USR>/miniconda3/envs/cnvkit

  added / updated specs:
    - cnvkit


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  _r-mutex           conda-forge/noarch::_r-mutex-1.0.1-anacondar_1
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.1-py_0
  backports_abc      conda-forge/noarch::backports_abc-0.5-py_1
  bcftools           bioconda/linux-64::bcftools-1.8-h4da6232_3
  binutils_impl_lin~ conda-forge/linux-64::binutils_impl_linux-64-2.33.1-he1b5a44_7
  binutils_linux-64  conda-forge/linux-64::binutils_linux-64-2.33.1-h9595d00_16
  bioconductor-dnac~ bioconda/linux-64::bioconductor-dnacopy-1.60.0-r36h6e990d7_0
  biopython          conda-forge/linux-64::biopython-1.76-py27h516909a_0
  bwidget            conda-forge/linux-64::bwidget-1.9.14-0
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  cairo              conda-forge/linux-64::cairo-1.16.0-hfb77d84_1002
  certifi            conda-forge/linux-64::certifi-2019.11.28-py27_0
  cnvkit             bioconda/noarch::cnvkit-0.9.6-py_2
  curl               conda-forge/linux-64::curl-7.65.3-hf8cf82a_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  decorator          conda-forge/noarch::decorator-4.4.1-py_0
  enum34             conda-forge/linux-64::enum34-1.1.6-py27_1002
  expat              conda-forge/linux-64::expat-2.2.5-he1b5a44_1004
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h86ecdb6_1001
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_1
  fribidi            conda-forge/linux-64::fribidi-1.0.5-h516909a_1002
  functools32        conda-forge/noarch::functools32-3.2.3.2-py_3
  future             conda-forge/linux-64::future-0.18.2-py27_0
  futures            conda-forge/linux-64::futures-3.3.0-py27_0
  gcc_impl_linux-64  conda-forge/linux-64::gcc_impl_linux-64-7.3.0-hd420e75_4
  gcc_linux-64       conda-forge/linux-64::gcc_linux-64-7.3.0-h553295d_16
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  gfortran_impl_lin~ conda-forge/linux-64::gfortran_impl_linux-64-7.3.0-hdf63c60_4
  gfortran_linux-64  conda-forge/linux-64::gfortran_linux-64-7.3.0-h553295d_16
  glib               conda-forge/linux-64::glib-2.58.3-py27h6f030ca_1002
  graphite2          conda-forge/linux-64::graphite2-1.3.13-hf484d3e_1000
  gsl                conda-forge/linux-64::gsl-2.5-h294904e_1
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.5-h0935bb2_0
  gstreamer          conda-forge/linux-64::gstreamer-1.14.5-h36ae1b5_0
  gxx_impl_linux-64  conda-forge/linux-64::gxx_impl_linux-64-7.3.0-hdf63c60_4
  gxx_linux-64       conda-forge/linux-64::gxx_linux-64-7.3.0-h553295d_16
  harfbuzz           conda-forge/linux-64::harfbuzz-2.4.0-h9f30f68_3
  htslib             bioconda/linux-64::htslib-1.7-0
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  joblib             conda-forge/noarch::joblib-0.14.1-py_0
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  kiwisolver         conda-forge/linux-64::kiwisolver-1.1.0-py27hc9558a2_0
  krb5               conda-forge/linux-64::krb5-1.16.4-h2fd8d38_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libclang           conda-forge/linux-64::libclang-9.0.1-default_hde54327_0
  libcurl            conda-forge/linux-64::libcurl-7.65.3-hda55be3_0
  libdeflate         conda-forge/linux-64::libdeflate-1.5-h516909a_0
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc             conda-forge/linux-64::libgcc-7.2.0-h69d50b8_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_4
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1005
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libllvm9           conda-forge/linux-64::libllvm9-9.0.1-hc9558a2_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libssh2            conda-forge/linux-64::libssh2-1.8.2-h22169c7_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc3755c2_3
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxkbcommon       conda-forge/linux-64::libxkbcommon-0.9.1-hebb1f50_0
  libxml2            conda-forge/linux-64::libxml2-2.9.10-hee79883_0
  lz4-c              conda-forge/linux-64::lz4-c-1.8.3-he1b5a44_1001
  make               conda-forge/linux-64::make-4.2.1-h14c3975_2004
  matplotlib         conda-forge/linux-64::matplotlib-2.2.4-py27_2
  matplotlib-base    conda-forge/linux-64::matplotlib-base-2.2.4-py27h250f245_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  networkx           conda-forge/linux-64::networkx-2.1-py27_0
  nspr               conda-forge/linux-64::nspr-4.24-he1b5a44_0
  nss                conda-forge/linux-64::nss-3.47-he751ad9_0
  numpy              conda-forge/linux-64::numpy-1.16.5-py27h95a1406_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  pandas             conda-forge/linux-64::pandas-0.24.2-py27hb3f55d8_0
  pango              conda-forge/linux-64::pango-1.42.4-ha030887_1
  pcre               conda-forge/linux-64::pcre-8.43-he1b5a44_0
  pillow             conda-forge/linux-64::pillow-6.2.1-py27hd70f55b_1
  pip                conda-forge/linux-64::pip-19.3.1-py27_0
  pixman             conda-forge/linux-64::pixman-0.38.0-h516909a_1003
  pomegranate        conda-forge/linux-64::pomegranate-0.12.0-py27hc9558a2_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pyfaidx            bioconda/noarch::pyfaidx-0.5.8-py_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pyqt               conda-forge/linux-64::pyqt-5.12.3-py27hcca6a23_1
  pysam              bioconda/linux-64::pysam-0.14.1-py27hae42fb6_1
  python             conda-forge/linux-64::python-2.7.15-h5a48372_1009
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  pytz               conda-forge/noarch::pytz-2019.3-py_0
  pyyaml             conda-forge/linux-64::pyyaml-5.3-py27h516909a_0
  qt                 conda-forge/linux-64::qt-5.12.5-hd8c4c69_1
  r-base             conda-forge/linux-64::r-base-3.6.2-h3a67422_0
  r-cghflasso        conda-forge/linux-64::r-cghflasso-0.2_1-r36h6e990d7_1003
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  reportlab          conda-forge/linux-64::reportlab-3.5.32-py27h7d98c4e_0
  samtools           bioconda/linux-64::samtools-1.6-h244ad75_5
  scipy              conda-forge/linux-64::scipy-1.2.1-py27h921218d_2
  sed                conda-forge/linux-64::sed-4.7-h1bed415_1000
  setuptools         pkgs/main/linux-64::setuptools-44.0.0-py27_0
  singledispatch     conda-forge/linux-64::singledispatch-3.4.0.3-py27_1000
  six                conda-forge/linux-64::six-1.14.0-py27_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  subprocess32       conda-forge/linux-64::subprocess32-3.5.4-py27h516909a_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  tktable            conda-forge/linux-64::tktable-2.10-h555a92e_3
  tornado            conda-forge/linux-64::tornado-5.1.1-py27h14c3975_1000
  wheel              conda-forge/linux-64::wheel-0.33.6-py27_0
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h516909a_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h84519dc_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.9-h516909a_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h516909a_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h516909a_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  yaml               conda-forge/linux-64::yaml-0.2.2-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006
  zstd               conda-forge/linux-64::zstd-1.4.4-h3b9ef0a_1


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate cnvkit
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) -bash-4.2$ conda activate cnvkit
(cnvkit) -bash-4.2$ cnvkit.py scatter -h
Traceback (most recent call last):
  File "<USR>/miniconda3/envs/cnvkit/bin/cnvkit.py", line 8, in <module>
    from cnvlib import commands
  File "<USR>/miniconda3/envs/cnvkit/lib/python2.7/site-packages/cnvlib/__init__.py", line 1, in <module>
    from skgenome.tabio import write
  File "<USR>/miniconda3/envs/cnvkit/lib/python2.7/site-packages/skgenome/__init__.py", line 1, in <module>
    from . import tabio
  File "<USR>/miniconda3/envs/cnvkit/lib/python2.7/site-packages/skgenome/tabio/__init__.py", line 17, in <module>
    from . import (bedio, genepred, gff, picard, seg, seqdict, tab, textcoord, vcfio,
  File "<USR>/miniconda3/envs/cnvkit/lib/python2.7/site-packages/skgenome/tabio/vcfio.py", line 11, in <module>
    import pysam
  File "<USR>/miniconda3/envs/cnvkit/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

```

**Comment by shengzha** [comment]
https://github.com/bioconda/bioconda-recipes/issues/12100 this post helps!

**Comment by etal** [comment]
Thanks, it looks like this problem may be resolved in the next release. If it appears again, for posterity, it looks like the fix was to install a specific version of openssl: `conda install openssl=1.0` -- ideally in a fresh conda environment to avoid breaking any packages that depend on other versions of openssl.

**Comment by llk578496** [comment]
Hi @etal !
I got the exact same situation as @shengzha and I just tried to install openssl by `mamba install openssl=1.0` but I got the following error messages:
```

                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.16.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['openssl=1.0']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
bioconda/linux-64        Using cache
bioconda/noarch          Using cache
pkgs/main/linux-64       Using cache
pkgs/main/noarch         Using cache
pkgs/r/linux-64          Using cache
pkgs/r/noarch            Using cache
r/linux-64               Using cache
r/noarch                 Using cache
cruizperez/linux-64      [====================] (00m:00s) No change
liulab-dfci/linux-64     [====================] (00m:00s) No change
cruizperez/noarch        [====================] (00m:00s) No change
liulab-dfci/noarch       [====================] (00m:00s) No change

Pinned packages:
  - python 3.6.*


Encountered problems while solving:
  - package libnghttp2-1.43.0-h812cca2_1 requires openssl >=1.1.1l,<1.1.2a, but none of the providers can be installed

```

May I know how to solve this problem?

**Comment by davidvanzessen** [comment]
Hi,

I was running into the same problem as @shengzha and after fixing that the same problem as @llk578496.
Finally found something that worked:  
`mamba create -n <env_name> -c conda-forge -c bioconda cnvkit=0.9.7 openssl=1.0`  

This installed everything without errors, note that just running `cnvkit.py` does still produce an error, but `cnvkit.py -h` does not.

**Comment by davidvanzessen** [comment]
Spoke to soon, it needs another pandas version, so:
mamba create -n <env_name> -c conda-forge -c bioconda cnvkit=0.9.7 openssl=1.0 pandas=1.0.5
