### ISSUE TITLE
Error while running cnvkit antitarget option

### ISSUE THREAD

**Issue by pwanj** [etal/cnvkit#494]
Hello,

I am getting the following error when i run cnvkit.py antitarget

Traceback (most recent call last):
  File "/apps/software/gcc-4.9.4/python/2.7.6b/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/apps/software/gcc-4.9.4/python/2.7.6b/lib/python2.7/site-packages/cnvlib/commands.py", line 464, in _cmd_antitarget
    access = tabio.read_auto(args.access)
  File "/apps/software/gcc-4.9.4/python/2.7.6b/lib/python2.7/site-packages/cnvlib/tabio/__init__.py", line 103, in read_auto
    % infile)
ValueError: Can only auto-detect format from filename or seekable (local, on-disk) files, which None is not

Please can you tell me what could cause this error. I would appreciate your help.

Thanks
Pankhuri

**Comment by pwanj** [comment]
I figured out why I was getting the error. Thanks!
