### ISSUE TITLE
Issue in cnvkit 'list' object has no attribute 'columns'

### ISSUE THREAD

**Issue by mjafin** [etal/cnvkit#51]
Hi Eric,
I was trying to rerun a past analysis with a newer version of cnvkit and am running into a few problems:
```
subprocess.CalledProcessError: Command '/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/bin/cnvkit.py reference -f /ngs/reference_data/genomes/Hsapiens/hg19/seq/hg19.fa -o /ngs/oncology/analysis/translation/TS_0028_CRUK_StratMed_Phase2_matrix_validation/Birmingham_test/Birmingham/work/structural/HDC140P/cnvkit/raw/tx/tmpSxtH5v/flat_background.cnn -t /ngs/oncology/analysis/translation/TS_0028_CRUK_StratMed_Phase2_matrix_validation/Birmingham_test/Birmingham/work/structural/HDC140P/cnvkit/raw/NexteraRapidCapture-CRUK_SMP2-1-2-merged-annotated.target.bed -a /ngs/oncology/analysis/translation/TS_0028_CRUK_StratMed_Phase2_matrix_validation/Birmingham_test/Birmingham/work/structural/HDC140P/cnvkit/raw/NexteraRapidCapture-CRUK_SMP2-1-2-merged-annotated.antitarget.bed
Detected file format: BED
Traceback (most recent call last):
  File "/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 463, in _cmd_reference
    args.fasta, args.male_reference)
  File "/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 515, in do_reference_flat
    ref_probes.concat(reference.bed2probes(antitarget_list))
  File "/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/reference.py", line 15, in bed2probes
    regions = RA.read(bed_fname)
  File "/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/rary.py", line 42, in read
    return cls([])
  File "/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/rary.py", line 19, in __init__
    gary.GenomicArray.__init__(self, data_table, meta_dict)
  File "/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/gary.py", line 22, in __init__
    if not all(c in data_table.columns for c in self._required_columns):
  File "/apps/bcbio-nextgen/latest-devel/rhel6-x64/anaconda/lib/python2.7/site-packages/cnvlib/gary.py", line 22, in <genexpr>
    if not all(c in data_table.columns for c in self._required_columns):
AttributeError: 'list' object has no attribute 'columns'
' returned non-zero exit status 1
```

Any idea where this might be coming from? The antitarget file is empty as this is data from a targeted panel

**Comment by etal** [comment]
I think this is a regression in the latest release that crept in when I moved the backend from numpy to pandas. I'll see about fixing it. There should really be unit tests for these edge cases, too.

**Comment by etal** [comment]
It should work now; can you confirm?

**Comment by mjafin** [comment]
Thanks Eric, let me try!

**Comment by mjafin** [comment]
Yep seems to be working cleanly now, thanks for the super quick fix Eric!
