### ISSUE TITLE
CNVkit couldn't recognize Y chromosome in the reference fasta file (KeyError: 'Y')

### ISSUE THREAD

**Issue by ryansohny** [etal/cnvkit#514]
Dear @etal 

I'm trying to operate cnvkit 0.9.6 from anaconda (https://anaconda.org/bioconda/cnvkit) to identify germline CNV from Normal WES data.

Below is my command. 

```
cnvkit.py batch \
${sample}.bam \
-n \
-t Exome-Agilent_V6_wochr.bed \
-f human_g1k_v37.fasta \
-g access-5k-mappable.grch37.bed \
--output-reference germline_${sample}.cnn \
--output-dir ${sample}/ \
--scatter \
--diagram \
-p 20

```

and the following error has occurred.

> CNVkit 0.9.6
> Detected file format: bed
> Splitting large targets
> Wrote N_BRCA1_5/Exome-Agilent_V6_wochr.target.bed with 280175 regions
> Detected file format: bed
> Skipping untargeted chromosomes MT
> Wrote N_BRCA1_5/Exome-Agilent_V6_wochr.antitarget.bed with 40341 regions
> Building a flat reference...
> Detected file format: bed
> Detected file format: bed
> Calculating GC and RepeatMasker content in /clinix1/Users/uugi0620/project/chul/wgs/v37/human_g1k_v37.fasta ...
> Extracting sequences from chromosome 1
> Extracting sequences from chromosome 2
> Extracting sequences from chromosome 3
> Extracting sequences from chromosome 4
> Extracting sequences from chromosome 5
> Extracting sequences from chromosome 6
> Extracting sequences from chromosome 7
> Extracting sequences from chromosome 8
> Extracting sequences from chromosome 9
> Extracting sequences from chromosome 10
> Extracting sequences from chromosome 11
> Extracting sequences from chromosome 12
> Extracting sequences from chromosome 13
> Extracting sequences from chromosome 14
> Extracting sequences from chromosome 15
> Extracting sequences from chromosome 16
> Extracting sequences from chromosome 17
> Extracting sequences from chromosome 18
> Extracting sequences from chromosome 19
> Extracting sequences from chromosome 20
> Extracting sequences from chromosome 21
> Extracting sequences from chromosome 22
> Extracting sequences from chromosome X
> Extracting sequences from chromosome Y
> Traceback (most recent call last):
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/lib/python3.7/site-packages/pyfaidx/__init__.py", line 1020, in __getitem__
>     return self.records[rname]
> KeyError: 'Y'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/bin/cnvkit.py", line 13, in <module>
>     args.func(args)
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/lib/python3.7/site-packages/cnvlib/commands.py", line 113, in _cmd_batch
>     args.count_reads, args.method)
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/lib/python3.7/site-packages/cnvlib/batch.py", line 118, in batch_make_reference
>     male_reference)
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/lib/python3.7/site-packages/cnvlib/reference.py", line 81, in do_reference_flat
>     gc, rmask = get_fasta_stats(ref_probes, fa_fname)
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/lib/python3.7/site-packages/cnvlib/reference.py", line 316, in get_fasta_stats
>     for subseq in fasta_extract_regions(fa_fname, cnarr)]
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/lib/python3.7/site-packages/cnvlib/reference.py", line 315, in <listcomp>
>     gc_rm_vals = [calculate_gc_lo(subseq)
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/lib/python3.7/site-packages/cnvlib/reference.py", line 345, in fasta_extract_regions
>     yield fa_file[_chrom][int(start):int(end)]
>   File "/ruby/Users/uugi0620/phenomata/Anaconda3/envs/cnvkit/lib/python3.7/site-packages/pyfaidx/__init__.py", line 1022, in __getitem__
>     raise KeyError("{0} not in {1}.".format(rname, self.filename))
> KeyError: 'Y not in /clinix1/Users/uugi0620/project/chul/wgs/v37/human_g1k_v37.fasta.'

### - In fact, human_g1k_v37.fasta has Y chromosome and subsequent sequence

> >Y dna:chromosome chromosome:GRCh37:Y:2649521:59034049:1
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
> NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

### - WES bam file were aligned onto the same reference human_g1k_v37.fasta which was used as an input to CNVkit.

Is there any solution to this anomalous behavior? There's clearly something I'm doing wrong.
Thanks for your help. 

Ryan

**Comment by etal** [comment]
That's odd. The lookups worked to create the target and antitarget BED files from the exome capture and access BED files, but once pyfaidx was used to extract sequences from the FASTA file, it failed. Is your .fai index file out of date or mismatched?

**Comment by ryansohny** [comment]
No it's not out of date nor mismatched.
I deleted chrY from reference fasta and from bed file and rerun the CNVkit and solved the problem. 
Yet I don't see why the error occurred in the first place.

**Comment by etal** [comment]
Likely stale .fai mismatch; resolved by workaround, no repro. Closing as resolved — please reopen with a reproduction on a current release if you still encounter it.
