### ISSUE TITLE
cnvkit fix requires old pandas version

### ISSUE THREAD

**Issue by sunnymouse25** [etal/cnvkit#549]
Hi! 
Running cnvkit fix on WGS data requires antitarget file, which in this case should be empty, so I use there an empty file Empty.antitarget.cnn. 

After updating cnvkit to version 0.9.7 cnvkit.py fix raised an error. It seems to be related to pandas v. 1.1.3, where pandas.io.common.EmptyDataError is now called pandas.errors.EmptyDataError. 
Changing "pd.io.common.EmptyDataError" to "pd.errors.EmptyDataError" or reverting to pandas 1.0.5 fixes this error. 

```
Traceback (most recent call last):
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/skgenome/tabio/__init__.py", line 74, in read
    dframe = reader(infile, **kwargs)
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/skgenome/tabio/tab.py", line 17, in read_tab
    dframe = pd.read_csv(infile, sep='\t', dtype={'chromosome': 'str'})
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/pandas/io/parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/pandas/io/parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/pandas/io/parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/cnvlib/commands.py", line 601, in _cmd_fix
    anti_raw = read_cna(args.antitarget, sample_id=args.sample_id)
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/cnvlib/cmdutil.py", line 12, in read_cna
    return tabio.read(infile, into=CNA, sample_id=sample_id, meta=meta)
  File "/aludisk/home/sunnymouse/tools/miniconda3_new/envs/cnvkit/lib/python3.7/site-packages/skgenome/tabio/__init__.py", line 75, in read
    except pd.io.common.EmptyDataError:
AttributeError: module 'pandas.io.common' has no attribute 'EmptyDataError'
```

Hope this helps.

**Comment by l0ka** [comment]
Hi all! I'm experiencing the same problem with some samples. I tried to run cnvkit on my Univeristy's HPC cluster (running CentOS Linux release 7.6.1810 (Core)), on a laptop running Ubuntu 20.04 and on a laptop running Fedora 33. I tried to install cnvkit using all available methods described in the wiki (conda, pip, installation from sources) and all runs ended in the same way. I'm going through further investigations, I'll let you know

**Comment by etal** [comment]
Already fixed; tabio now uses pd.errors.EmptyDataError. Closing as resolved — please reopen with a reproduction on a current release if you still encounter it.
