### ISSUE TITLE
ValueError: Duplicated genomic coordinates in sample set

### ISSUE THREAD

**Issue by cyanosoma01** [etal/cnvkit#567]
Hi, all, my question is as follows, how can I solve it? thanks

Processing target: samplename
Traceback (most recent call last):
  File "xxx/cnvkit.py", line 9, in <module>
    args.func(args)
  File "xxx/commands.py", line 610, in _cmd_fix
    target_table = fix.do_fix(tgt_raw, anti_raw, read_cna(args.reference),
  File "xxx/fix.py", line 15, in do_fix
    cnarr, ref_matched = load_adjust_coverages(target_raw, reference,
  File "xxx/fix.py", line 69, in load_adjust_coverages
    ref_matched = match_ref_to_sample(ref_cnarr, cnarr)
  File "xxx/fix.py", line 138, in match_ref_to_sample
    raise ValueError("Duplicated genomic coordinates in " + name +
ValueError: Duplicated genomic coordinates in sample set:
('chr1', 24359903, 24360023)
('chr1', 24360027, 24360149)
('chr1', 39762447, 39762623)

**Comment by bernarddbj** [comment]
I got the same problem.

**Comment by mquinodo** [comment]
I have also the same problem.

**Comment by mquinodo** [comment]
I had the same problem.

I realised that my target files had duplicated lines.
I did: target.bed | sort | uniq > new-target.bed
and it solved the problem.

**Comment by alextrouerntrend** [comment]
In my case, this was because the target bed bore an individual record of the same feature for potential synonyms of that feature. See below:
```
$ grep 152719709 target.bed
chrX       152719709       152719829       TREX2
chrX       152719709       152719829       HAUS7
```
This issue was solved with awk '!seen[$1$2$3]++' target.bed > new-target.bad. Only the first record for each identical region is taken. I think it's possible that these are different genes that occupy the same region, which would make this an imperfect solution.
