### ISSUE TITLE
DNAnexus app Import error

### ISSUE THREAD

**Issue by ashleyacevedo** [etal/cnvkit#569]
I tried to use the DNAnexus app but ran into the following error:
```
2021-02-08 22:03:23 CNVkit STDERR Traceback (most recent call last):
2021-02-08 22:03:23 CNVkit STDERR   File "/home/dnanexus/job-G0V2F2Q071b060BV070pzBv4", line 39, in <module>
2021-02-08 22:03:23 CNVkit STDERR     exec_code(job_code, _code_filename)
2021-02-08 22:03:23 CNVkit STDERR   File "/home/dnanexus/job-G0V2F2Q071b060BV070pzBv4", line 25, in exec_code
2021-02-08 22:03:23 CNVkit STDERR     exec(compiled_code, globals())
2021-02-08 22:03:23 CNVkit STDERR   File "/home/dnanexus/job-G0V2F2Q071b060BV070pzBv4.code.py", line 12, in <module>
2021-02-08 22:03:23 CNVkit STDERR     import magic
2021-02-08 22:03:23 CNVkit STDERR ImportError: No module named 'magic'
```
Any help would be appreciated.

**Comment by tskir** [comment]
Hi @ashleyacevedo, I was wondering if you're stil having this issue?

Unfortunately I don't use DNAnexus, but perhaps @etal could help with this one

**Comment by etal** [comment]
Hi  @ashleyacevedo , DNAnexus has its own app now. I suggest filing a support request with DNAnexus, and they will point you to their latest version and/or fix their packaging for it.

**Comment by ashleyacevedo** [comment]
Thanks @etal, I ended up using your docker image, etal/cnvkit:latest, to build a custom applet on DNAnexus. That did the trick.
