### ISSUE TITLE
Suggestion: joblib=0.17.0

### ISSUE THREAD

**Issue by sssimonyang** [etal/cnvkit#589]
When calling germline cnv and segmentation method is `-m hmm-germline`.
The cnvkit got error.
```
error:
    TypeError: delayed() got an unexpected keyword argument 'check_pickle'
```
By referring https://github.com/scikit-learn-contrib/hdbscan/issues/436
The package of joblib currently is 1.0.1
```
conda install joblib==0.17.0
```
can fix.
So I recommend to add this version specification or fix it by another way.

**Comment by tskir** [comment]
Hi @sssimonyang,

Thank you for reporting this! I think a preferred way would be to fix the underlying API calls to support joblib 1.0+ rather than pinning it to an old version. Could you please provide the command you're running and the complete traceback, so that I could look into where exactly this happens?

**Comment by sssimonyang** [comment]
Hi @tskir 

The command is 

```
cnvkit.py batch TCGA-DD-A4NK_blood.markdup.bqsr.bam --normal --targets baits.bed --segment-method hmm-germline --annotate refFlat.txt --fasta GRCh38.d1.vd1.fa --output-reference reference.cnn --output-dir TCGA-DD-A4NK_blood/ --diagram --scatter
```
And the error occur after Segment.
```
Segmenting TCGA-DD-A4NK_blood/TCGA-DD-A4NK_blood.markdup.bqsr.cnr ...
Segmenting with method 'hmm-germline' in 1 processes
Building model from observations
Traceback (most recent call last):
  File "/public/home/yangjk/software/miniconda3/envs/cnvkit/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/public/home/yangjk/software/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/commands.py", line 138, in _cmd_batch
    pool.submit(batch.batch_run_sample,
  File "/public/home/yangjk/software/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/parallel.py", line 19, in submit
    return SerialFuture(func(*args))
  File "/public/home/yangjk/software/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/batch.py", line 186, in batch_run_sample
    segments = segmentation.do_segmentation(cnarr, segment_method,
  File "/public/home/yangjk/software/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/segmentation/__init__.py", line 52, in do_segmentation
    cna = _do_segmentation(cnarr, method, threshold, variants, skip_low,
  File "/public/home/yangjk/software/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/segmentation/__init__.py", line 139, in _do_segmentation
    segarr = hmm.segment_hmm(filtered_cn, method, threshold, variants)
  File "/public/home/yangjk/software/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/segmentation/hmm.py", line 45, in segment_hmm
    model = hmm_get_model(cnarr, method, processes)
  File "/public/home/yangjk/software/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/segmentation/hmm.py", line 130, in hmm_get_model
    model.fit(sequences=observations,
  File "pomegranate/hmm.pyx", line 2564, in pomegranate.hmm.HiddenMarkovModel.fit
  File "pomegranate/hmm.pyx", line 2565, in pomegranate.hmm.HiddenMarkovModel.fit
TypeError: delayed() got an unexpected keyword argument 'check_pickle'
```
joblib=1.0.1 and hmmlearn=0.2.5

**Comment by etal** [comment]
I think this is pomegranate's internal call, not in CNVkit's codebase. I'll try adding a line `joblib < 1.0` to the dependencies in setup.py.

**Comment by risicle** [comment]
It might be worth trying this again with the latest `pomegranate` as the problematic call looks like it was removed a while ago https://github.com/jmschrei/pomegranate/commit/42d14bebc44ffd4a778b2a6430aa845591b7c3b7
