### ISSUE TITLE
CNVkit import-rna Error

### ISSUE THREAD

**Issue by starz77** [etal/cnvkit#596]
Hello,

I want to run using import-rna option, but it doesn't work well.

Here's my command and Error message.

python $DIR/cnvkit.py import-rna $INPUT/$i/$i".genes.results" |  \
    --gene-resource $DIR/data/ensembl-gene-info.hg38.tsv \
    --correlations $DIR/data/tcga-skcm.cnv-expr-corr.tsv \
    --output $i"_out_summary.tsv" --output-dir $OUTDIR/

/bio/scratch/starz77/Tools/cnvkit/cnvlib/rna.py:267: FutureWarning: clip_upper(threshold) is deprecated, use clip(upper=threshold) instead
  weights = [np.sqrt((gene_counts / gene_counts.quantile(.75)).clip_upper(1))]
Calculating normalized gene read depths
Traceback (most recent call last):
  File "/bio/scratch/starz77/Tools/cnvkit/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/bio/scratch/starz77/Tools/cnvkit/cnvlib/commands.py", line 1535, in _cmd_import_rna
    args.normal, args.do_gc, args.do_txlen, args.max_log2)
  File "/bio/scratch/starz77/Tools/cnvkit/cnvlib/import_rna.py", line 39, in do_import_rna
    gene_info, sample_counts, tx_lengths, normal_ids)
  File "/bio/scratch/starz77/Tools/cnvkit/cnvlib/rna.py", line 272, in align_gene_info_to_samples
    normal_ids)
  File "/bio/scratch/starz77/Tools/cnvkit/cnvlib/rna.py", line 308, in normalize_read_depths
    assert sample_depths.values.sum() > 0

Thank you.

**Comment by tskir** [comment]
Hi @starz77! From the error message it looks like the command didn't find any data to work on; as in, it thinks that the input dataset is empty. This could be either a real problem with your data, or indeed a bug with `cnvkit.py import-rna`.

Could you share one of the `.genes.results` files with me please? If these are private data, feel free to shuffle/randomise the values within it. Sharing the whole file is also not necessary, just the first ~100 lines or so should do the trick. In essence, I just need some minimal example to reproduce the issue & investigate further.

**Comment by starz77** [comment]
Hello,

Here's my '.genes.result' file.

send again.

 GSM2834488_paired_end_quals.genes.results
<https://drive.google.com/file/d/1_a48bbN3o4VZOL-wlIs_NuZSda3CJGkM/view?usp=drive_web>


thank you.
ᐧ

2021년 4월 24일 (토) 오후 12:46, Kirill Tsukanov ***@***.***>님이 작성:
