### ISSUE TITLE
Error while running cnvkit.py batch ......

### ISSUE THREAD

**Issue by cassandratzh** [etal/cnvkit#75]
Hi, 

I ran this code cnvkit.py batch *Tumor.bam --normal *Normal.bam \ --targets my_baits.bed --fasta hg19.fasta \ --split --access data/access-5kb-mappable.hg19.bed \ --output-reference my_reference.cnn --output-dir example/ 

There are several errors stating as below : 
Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.7.6.dev0', 'cnvkit.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/CNVkit-0.7.6.dev0-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 6, in <module>
    
  File "build/bdist.macosx-10.10-x86_64/egg/cnvlib/__init__.py", line 1, in <module>
  File "build/bdist.macosx-10.10-x86_64/egg/cnvlib/cnary.py", line 7, in <module>
  File "/usr/local/lib/python2.7/site-packages/pandas/__init__.py", line 44, in <module>
    from pandas.core.api import *
  File "/usr/local/lib/python2.7/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.groupby import Grouper
  File "/usr/local/lib/python2.7/site-packages/pandas/core/groupby.py", line 17, in <module>
    from pandas.core.frame import DataFrame
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 41, in <module>
    from pandas.core.series import Series
  File "/usr/local/lib/python2.7/site-packages/pandas/core/series.py", line 2909, in <module>
    import pandas.tools.plotting as _gfx
  File "/usr/local/lib/python2.7/site-packages/pandas/tools/plotting.py", line 28, in <module>
    import pandas.tseries.converter as conv
  File "/usr/local/lib/python2.7/site-packages/pandas/tseries/converter.py", line 7, in <module>
    import matplotlib.units as units
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Any idea how can I solve this problem? 

Thanks!

**Comment by etal** [comment]
This looks like an issue with the installation of `matplotlib` or `pandas` on your system. It looks like either Python 2.7 or some but not all of the Python packages were installed by homebrew, and then the system doesn't look how matplotlib expects. How did you install CNVkit?

The problem might resolve if you uninstall CNVkit (just delete `/usr/local/lib/python2.7/site-packages/CNVkit-0.7.6.dev0-py2.7.egg/` if you didn't use a package manager that can uninstall it), then reinstall with [Conda](https://github.com/etal/cnvkit/#using-conda).

If that doesn't appeal to you, you can try updating the homebrew packages you have installed, and see if the packagers have already noticed the issue and fixed it.

To quickly test your installation, you can do:

    cnvkit.py -h
