### ISSUE TITLE
RuntimeError: Subprocess command failed:

### ISSUE THREAD

**Issue by dauss75** [etal/cnvkit#76]
I am running cnvkit with only one sample for testing and get a following error.
Do you have any though on this?
Thanks!

Segmenting tt/dataset_1581.cnr ...
Traceback (most recent call last):
  File "/mnt/galaxyTools/tools/pymodules/python2.7/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/commands.py", line 109, in _cmd_batch
    args.diagram, args.rlibpath, args.count_reads))
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/parallel.py", line 14, in apply_async
    func(*args)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/commands.py", line 207, in batch_run_sample
    segments = segmentation.do_segmentation(cnarr, 'cbs', rlibpath=rlibpath)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/segmentation/__init__.py", line 55, in do_segmentation
    seg_out = ngfrills.call_quiet('Rscript', script_fname)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/cnvlib/ngfrills/__init__.py", line 42, in call_quiet
    % (' '.join(args), err))
RuntimeError: Subprocess command failed:

**Comment by etal** [comment]
My guess is that the R dependencies are not in place for this Galaxy tool -- can you see if the R packages "PSCBS" and "dnaCopy" are installed and available to the default R installation?

Note that the Galaxy tool for CNVkit does not package the current CNVkit version, and dependency management is not automatic (see #56).

**Comment by dauss75** [comment]
Thanks.  It works now.

**Comment by yaoyao926** [comment]
请问您怎么弄得，我现在也出现这个问题
