### ISSUE TITLE
NameError: name 'GC_MIN_FRACTION' is not defined

### ISSUE THREAD

**Issue by HeejunJang** [etal/cnvkit#763]
my command was 

$CNVKIT/cnvkit.py batch $INPUT/$i".bam" --n \
    --targets $REF/bed/mybed.bed \
    --fasta $REF/hg19/hg19_1-22-X-Y-M.fa \
    --output-reference $FINAL/$i".cnn" \
    --output-dir $FINAL

$CNVKIT/cnvkit.py segmetrics -s $FINAL/$i".cn"{s,r} --ci

here's error message

Traceback (most recent call last):
  File "/work/tools/cnvkit/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/work/tools/cnvkit/cnvlib/commands.py", line 138, in _cmd_batch
    pool.submit(batch.batch_run_sample,
  File "/work/tools/cnvkit/cnvlib/parallel.py", line 19, in submit
    return SerialFuture(func(*args))
  File "/work/tools/cnvkit/cnvlib/batch.py", line 180, in batch_run_sample
    cnarr = fix.do_fix(raw_tgt, raw_anti, read_cna(ref_fname),
  File "/work/tools/cnvkit/cnvlib/fix.py", line 15, in do_fix
    cnarr, ref_matched = load_adjust_coverages(target_raw, reference,
  File "/work/tools/cnvkit/cnvlib/fix.py", line 72, in load_adjust_coverages
    ok_cvg_indices = ~mask_bad_bins(ref_matched)
  File "/work/tools/cnvkit/cnvlib/fix.py", line 127, in mask_bad_bins
    lower_gc_bound = min(GC_MIN_FRACTION, GC_MAX_FRACTION)
NameError: name 'GC_MIN_FRACTION' is not defined

CNVkit can't make cns file

please help.

**Comment by tetedange13** [comment]
Hi @HeejunJang ,

Thanks for reporting this, I just submitted a PR (#764) to fix it
=> In the meantime, I suggest you use [latest stable release of CNVkit](https://github.com/etal/cnvkit/releases/tag/v0.9.9) instead

Sorry for the inconvenience !
Have a nice day,
Felix.
