### ISSUE TITLE
import-theta error (cnvkit version 0.7.7.dev0)

### ISSUE THREAD

**Issue by kw10** [etal/cnvkit#77]
Hello!

I ran theta2 using the BAF model and produced the *BEST.results files. I then tried to import the results back into CNVkit, but get the following error:

```
cnvkit.py import-theta ./10_tumour.cns ./THETA/10L_out/10L_tumour.BEST.results 
Traceback (most recent call last):
  File "/software/vertres/lib/python/python-2.7.3/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.7.7.dev0', 'cnvkit.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1659, in run_script
  File "/software/vertres/lib/python/python-2.7.3/lib/python2.7/site-packages/CNVkit-0.7.7.dev0-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 11, in <module>

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 1571, in _cmd_import_theta
    
TypeError: 'Pandas' object does not support item assignment

```
I get the same error when I run 'import-theta' with the *n2.results file produced by running theta via cnvkit as:  RunTHetA.py Sample.theta2.input -n 2 -k 4 -m .90 --FORCE 
as indicated in the CNVkit docs.

Thanks!

**Comment by etal** [comment]
Thanks for the detailed report, and sorry for the trouble. I've fixed the bug; could you pull the latest from GitHub and see if it works for you now?

**Comment by kw10** [comment]
Yes, that worked. I no longer get the error. Thanks!
