### ISSUE TITLE
Examining conflicts takes forever installing cnvkit with conda

### ISSUE THREAD

**Issue by HeejunJang** [etal/cnvkit#772]
Hello

I tried to install cnvkit using conda.

However, it is currently unfinished on the 3rd day. 

Only the process of "Examing conflicts ~~" is being repeated over and over again.

Can I solve this problem by changing my other options?

Please Help

Thank you.

**Comment by tetedange13** [comment]
Hi @HeejunJang,
<br>

In my experience this is due to conda struggling to find compatible packages within a single channel
1. What is your conda version (output of `conda --version`)
1. What is exact `conda` command you used ?
2. Do you have any channels specified in your `.condarc` config file ? (output of `conda config --show channels`)
3. What is your "channel priority" ? (output of `conda config --show channel_priority`)

To install CNVkit (or any "bioinformatics" package/app), I usually type `conda create -n <package> -c conda-forge -c bioconda <package>`
=> Order matters, so this tells conda to *first* look for dependencies in `conda-forge`, *then* in `bioconda` (then in `defaults` channel, see [conda's help](https://docs.conda.io/projects/conda/en/latest/commands/install.html#Channel%20Customization))
=> So here, please try : `conda create -n cnvkit -c conda-forge -c bioconda cnvkit`
(possibly helpful : https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it)
<br>

Hope this helps !
Have a nice day,
Felix.

**Comment by HeejunJang** [comment]
Hello, Here's my information.

1. conda 22.9.0
2. conda update --all 
   conda install cnvkit
3.   
  - conda-forge
  - bioconda
  - defaults

4. channel_priority: flexible

I'll try with your suggestion and reply again.

Thank you.

Heejun Jang.

**Comment by HeejunJang** [comment]
Hello, 

I installed with "conda create -n cnvkit -c conda-forge -c bioconda cnvkit"

and did "conda activate cnvkit"

But, Simmilar error occured before I ran cnvkit.py (source version) without conda environment.

/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/skgenome/gary.py:484: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self.data = self.data.append(other.data, ignore_index=True)
/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/skgenome/gary.py:484: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self.data = self.data.append(other.data, ignore_index=True)
WARNING: Most antitarget bins (100.00%, 19237/19237) have low or no coverage; is this amplicon/WGS?
/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/cnary.py:451: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.concat(resids) if resids else pd.Series([])
Antitargets are nan x more variable than targets
Wrote /work/hjjang/CNV/result/NEO83_S25_L001/NEO83_S25_L001.cnr with 22920 regions
Segmenting /work/hjjang/CNV/result/NEO83_S25_L001/NEO83_S25_L001.cnr ...
Segmenting with method 'cbs', significance threshold 0.0001, in 1 processes
Traceback (most recent call last):
  File "/usr/bin/anaconda3/envs/cnvkit/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/commands.py", line 138, in _cmd_batch
    pool.submit(batch.batch_run_sample,
  File "/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/parallel.py", line 19, in submit
    return SerialFuture(func(*args))
  File "/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/batch.py", line 186, in batch_run_sample
    segments = segmentation.do_segmentation(cnarr, segment_method,
  File "/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 61, in do_segmentation
    rets = list(pool.map(_ds, ((ca, method, threshold, variants,
  File "/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 89, in _ds
    return _do_segmentation(*args)
  File "/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 161, in _do_segmentation
    seg_out = core.call_quiet(rscript_path,
  File "/usr/bin/anaconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/core.py", line 31, in call_quiet
    raise RuntimeError("Subprocess command failed:\n$ %s\n\n%s"
RuntimeError: Subprocess command failed:
$ Rscript --no-restore --no-environ /tmp/tmprmliknp7

b'Loading probe coverages into a data frame\nWarning message:\nIn CNA(cbind(tbl$log2), tbl$chromosome, tbl$start, data.type = "logratio",  :\n  markers with missing chrom and/or maploc removed\n\nSegmenting the probe data\nError in segment(cna, weights = tbl$weight, alpha = 1e-04) : \n  length of weights should be the same as the number of probes\nExecution halted\n'

I confirmed that similar errors occur both when running with conda and without conda.

Thank you.

Heejun Jang

**Comment by etal** [comment]
Classic conda solver issue; answered with dedicated-env channel ordering. Closing as answered — please reopen, or open a new issue, if a concrete problem remains.

For general usage questions, we now use GitHub Discussions (Q&A): https://github.com/etal/cnvkit/discussions
