### ISSUE TITLE
Autobin

### ISSUE THREAD

**Issue by EmMaKaa** [etal/cnvkit#802]
Hi,

I have previously run CNVkit on default bin sizes, but now I'd like to try how using autobin affects the results. I have paired tumor-normal samples sequenced with hybrid capture method, am I supposed to use all of them as input for autobin, or only either tumor or normal samples? I understand that only the file with median file size is used for optimal bin size estimation, but obviously the set of files given as input affects the estimation. Another problem I have is that when I tested the command with either tumor or normal samples, it worked for tumor samples but for normal samples it gave an error:

Detected file format: bed
Detected file format: bed
Estimated read length 130.0
Wrote /tmp/tmpvncrgu42.bed with 100 regions
Limiting est. bin size 3250849 to given max. 500000
Splitting large targets
Traceback (most recent call last):
  File "/miniconda3/bin/cnvkit.py", line 10, in <module>
    sys.exit(main())
  File "/miniconda3/lib/python3.9/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/miniconda3/lib/python3.9/site-packages/cnvlib/commands.py", line 568, in _cmd_autobin
    target_out_arr = target.do_target(
  File "/miniconda3/lib/python3.9/site-packages/cnvlib/target.py", line 18, in do_target
    tgt_arr = tgt_arr.subdivide(avg_size, 0)
  File "/miniconda3/lib/python3.9/site-packages/skgenome/gary.py", line 689, in subdivide
    return self.as_dataframe(subdivide(self.data, avg_size, min_size, verbose))
  File "/miniconda3/lib/python3.9/site-packages/skgenome/subdivide.py", line 18, in subdivide
    return pd.DataFrame.from_records(
  File "/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 2297, in from_records
    first_row = next(data)
  File "/miniconda3/lib/python3.9/site-packages/skgenome/subdivide.py", line 44, in _split_targets
    nbins = int(round(span / avg_size)) or 1
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

Any tips how to solve this? The error confuses me since the bam files for tumor and normal have been generated similarly and I haven't had previous problems with the normal files.

**Comment by namxle** [comment]
Hi @EmMaKaa, have you solved this problem? I also having it right now ...

**Comment by etal** [comment]
Fixed in v0.9.14 (released 2026-07-01). This `TypeError` was raised when `autobin` couldn't estimate read depth in the target regions — most often a chromosome-name mismatch between the BAM, the reference FASTA, and the `--targets`/`--access` files (e.g. `chr1` vs `1`), or empty regions — which left the estimated bin size undefined and then failed during target subdivision. `autobin` now detects this up front and raises an explicit, actionable error naming the likely cause instead of the opaque `TypeError`. Please upgrade to v0.9.14; if depth still can't be estimated, the new message will point at the specific mismatch to fix. Happy to reopen if you hit this on matched inputs.
