### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'interval'

### ISSUE THREAD

**Issue by khaled196** [etal/cnvkit#806]
cnvkit.py antitarget my-targets.bed -g access-5k-mappable.hg19.bed
Detected file format: bed
Detected file format: bed
Traceback (most recent call last):
  File "/home/khaled/miniconda3/bin/cnvkit.py", line 10, in <module>
    sys.exit(main())
  File "/home/khaled/miniconda3/lib/python3.10/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/home/khaled/miniconda3/lib/python3.10/site-packages/cnvlib/commands.py", line 483, in _cmd_antitarget
    base, ext = args.interval.rsplit(".", 1)
AttributeError: 'Namespace' object has no attribute 'interval'

**Comment by etal** [comment]
Looks like an argparse problem; let me see if this has been fixed since this issue was reported.

**Comment by etal** [comment]
Confirmed still present on master. In the `antitarget` command, the fallback that builds the default output filename (used when `-o` isn't given) references `args.interval`, but the argument is named `targets`, so any `antitarget` run without `-o` raises this `AttributeError`. Workaround for now: pass `-o OUTPUT.bed` explicitly. The fix is a one-line correction; a patch with a regression test is on the way.

**Comment by khaled196** [comment]
Thank you @etal
