### ISSUE TITLE
AttributeError: module 'pomegranate' has no attribute 'NormalDistribution' in hmm-germline

### ISSUE THREAD

**Issue by mikpom** [etal/cnvkit#815]
Getting the following stack when running freshly installed cnvkit 0.9.10

```
Segmenting with method 'hmm-germline' in 1 processes
Smoothing overshot at 1 / 151 indices: (-0.2363971618901517, 1.1721341875644276) vs. original (-0.62521, 1.12396)
Building model from observations
Traceback (most recent call last):
  File "/home/mikpom/.local/venv/cnv/bin/cnvkit.py", line 8, in <module>
    sys.exit(main())
  File "/home/mikpom/.local/venv/cnv/lib/python3.8/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/home/mikpom/.local/venv/cnv/lib/python3.8/site-packages/cnvlib/commands.py", line 994, in _cmd_segment
    results = segmentation.do_segmentation(
  File "/home/mikpom/.local/venv/cnv/lib/python3.8/site-packages/cnvlib/segmentation/__init__.py", line 62, in do_segmentation
    cna = _do_segmentation(
  File "/home/mikpom/.local/venv/cnv/lib/python3.8/site-packages/cnvlib/segmentation/__init__.py", line 180, in _do_segmentation
    segarr = hmm.segment_hmm(filtered_cn, method, threshold, variants)
  File "/home/mikpom/.local/venv/cnv/lib/python3.8/site-packages/cnvlib/segmentation/hmm.py", line 42, in segment_hmm
    model = hmm_get_model(cnarr, method, processes)
  File "/home/mikpom/.local/venv/cnv/lib/python3.8/site-packages/cnvlib/segmentation/hmm.py", line 94, in hmm_get_model
    pom.NormalDistribution(-1.0, stdev, frozen=True),
AttributeError: module 'pomegranate' has no attribute 'NormalDistribution'
```

Happy to investigate the issue up to your hints and/or contribute fixes.

Best,
Mikhail

**Comment by mikpom** [comment]
pomegranate version 1.0.0

**Comment by savyajha** [comment]
Pomegranate version 1.0.0 is a major breaking change. `cnvlib/segmentation/hmm.py` will need to be refactored accordingly. I do not use either cnvkit or pomegranate else would have looked at submitting a PR.
