### ISSUE TITLE
cnvkit batch fails on pysam 0.9

### ISSUE THREAD

**Issue by kyleabeauchamp** [etal/cnvkit#86]
When I run cnvkit batch with pysam 0.9, I get the following error.  On 0.8.4 things seem to run fine.

```
Building a copy number reference from normal samples...
Processing reads in sample.bam
Traceback (most recent call last):
  File "~/opt/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "~/anaconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 97, in _cmd_batch
    args.processes, args.count_reads)
  File "~/anaconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 172, in batch_make_reference
    (target_bed, nbam, tgt_fname, by_count))
  File "~/anaconda2/lib/python2.7/site-packages/cnvlib/parallel.py", line 14, in apply_async
    func(*args)
  File "~/anaconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 193, in batch_write_coverage
    cnarr = do_coverage(bed_fname, bam_fname, by_count)
  File "~/anaconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 457, in do_coverage
    min_mapq)
  File "~/anaconda2/lib/python2.7/site-packages/cnvlib/coverage.py", line 37, in interval_coverages
    read_counts, cna_rows = zip(*list(results))
  File "~/anaconda2/lib/python2.7/site-packages/cnvlib/coverage.py", line 110, in interval_coverages_pileup
    min_mapq):
  File "~/anaconda2/lib/python2.7/site-packages/cnvlib/coverage.py", line 143, in bedcov
    raise RuntimeError("Bad line from bedcov:\n" + line)
RuntimeError: Bad line from bedcov:
c
```

**Comment by kyleabeauchamp** [comment]
I think this is a pysam issue.  See https://github.com/pysam-developers/pysam/issues/254

**Comment by etal** [comment]
This was reported on SeqAnswers too -- only the first character of the expected bedcov output is returned.

1. I could have setup.py/requirements.py insist on exactly "pysam==0.8.4", though not everyone uses virtualenv and this could cause other problems for people. And it's not a great long-term solution.
2. I could change CNVkit's error message to suggest using the `--count-reads` fallback option with the `batch` or `coverage` command.

**Comment by kyleabeauchamp** [comment]
OK, I just tried the read counting method and there's an issue with idxstats as well that breaks that as well:

```
Processing chromosome chr1 of control.bam
Time: 133.889 seconds (14221 reads/sec, 5 bins/sec)
Summary: [...]
Traceback (most recent call last):
  File "~/miniconda2/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "~/miniconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 97, in _cmd_batch
    args.processes, args.count_reads)
  File "~/miniconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 172, in batch_make_reference
    (target_bed, nbam, tgt_fname, by_count))
  File "~/miniconda2/lib/python2.7/site-packages/cnvlib/parallel.py", line 14, in apply_async
    func(*args)
  File "~/miniconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 193, in batch_write_coverage
    cnarr = do_coverage(bed_fname, bam_fname, by_count)
  File "~/miniconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 457, in do_coverage
    min_mapq)
  File "~/miniconda2/lib/python2.7/site-packages/cnvlib/coverage.py", line 53, in interval_coverages
    tot_mapped_reads = bam_total_reads(bam_fname)
  File "~/miniconda2/lib/python2.7/site-packages/cnvlib/coverage.py", line 164, in bam_total_reads
    _seqname, _seqlen, nmapped, _nunmapped = line.split()
ValueError: need more than 1 value to unpack
```

**Comment by kyleabeauchamp** [comment]
I made a pysam pull request that checks the stuff that we need to run.  

https://github.com/pysam-developers/pysam/pull/255/

**Comment by etal** [comment]
Wow. Thanks for reporting these issues here and following up with pysam. For now I'm going to ban pysam 0.9 in CNVkit's dependency list, then we'll see how and when pysam resolves the issue upstream.

**Comment by kyleabeauchamp** [comment]
Looks like all of these problems are actually manifestations of https://github.com/pysam-developers/pysam/issues/245

It's basically a matter of pysam pre-splitting the lines I think.  Should be easy enough to work around, but we may want to obtain some sort of clarity from the pysam folks on what the behavior will be moving forward.

**Comment by etal** [comment]
I've changed the code to just split the lines if a pysam call happens to return a string. I think this should be fine whether or not pysam grows a `split_lines` keyword argument in a future release.

**Comment by kyleabeauchamp** [comment]
AFAIK that should be future proof.

**Comment by kyleabeauchamp** [comment]
Also, thanks for the quick response!

**Comment by kyleabeauchamp** [comment]
FYI It appears that pysam has been updated with the split_lines changes:

https://github.com/pysam-developers/pysam/commit/8bcb76616b91fc55129cec2f0d6e37bdb4a9fc44
