### ISSUE TITLE
Runtime Error Using CNVKit Batch

### ISSUE THREAD

**Issue by hkarakurt8742** [etal/cnvkit#868]
Hello everyone,
I am new at CNVKit. I installed it using conda and installed DNAcopy library to R but when I run cnvkit.py batch, I have this error:

`
Traceback (most recent call last):
  File "/home/huk/anaconda3/envs/cnvkit/bin/cnvkit.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/huk/anaconda3/envs/cnvkit/lib/python3.11/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/home/huk/anaconda3/envs/cnvkit/lib/python3.11/site-packages/cnvlib/commands.py", line 194, in _cmd_batch
    pool.submit(
  File "/home/huk/anaconda3/envs/cnvkit/lib/python3.11/site-packages/cnvlib/parallel.py", line 18, in submit
    return SerialFuture(func(*args))
                        ^^^^^^^^^^^
  File "/home/huk/anaconda3/envs/cnvkit/lib/python3.11/site-packages/cnvlib/batch.py", line 264, in batch_run_sample
    segments = segmentation.do_segmentation(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huk/anaconda3/envs/cnvkit/lib/python3.11/site-packages/cnvlib/segmentation/__init__.py", line 79, in do_segmentation
    rets = list(
           ^^^^^
  File "/home/huk/anaconda3/envs/cnvkit/lib/python3.11/site-packages/cnvlib/segmentation/__init__.py", line 123, in _ds
    return _do_segmentation(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huk/anaconda3/envs/cnvkit/lib/python3.11/site-packages/cnvlib/segmentation/__init__.py", line 205, in _do_segmentation
    seg_out = core.call_quiet(
              ^^^^^^^^^^^^^^^^
  File "/home/huk/anaconda3/envs/cnvkit/lib/python3.11/site-packages/cnvlib/core.py", line 32, in call_quiet
    raise RuntimeError(
RuntimeError: Subprocess command failed:
$ Rscript --no-restore --no-environ /tmp/tmpwesj11ie

b'Loading probe coverages into a data frame\nWarning message:\nIn CNA(cbind(tbl$log2), tbl$chromosome, tbl$start, data.type = "logratio",  :\n  markers with missing chrom and/or maploc removed\n\nSegmenting the probe data\nError in segment(cna, weights = tbl$weight, alpha = 1e-04) : \n  length of weights should be the same as the number of probes\nExecution halted\n'
`

My code is:

`cnvkit.py batch cnvtest.bam -n -t test.bed -f hg19_v0_Homo_sapiens_assembly19.fasta --output-reference /home/huk/Desktop/Tool/cnvkit_test/FlatReference.cnn -d cnvtest/`

I am using a flatReferece created using "reference" command since I do not have any control samples. My data is a sequencing result of multiple exons of a single gene.

Thank you in advance.

**Comment by etal** [comment]
Could be related to #876
