### ISSUE TITLE
Bug when using fused lasso

### ISSUE THREAD

**Issue by pcingola** [etal/cnvkit#88]
There seems to be a small bug when trying to segment using fused lasso method:
Example:

    $ cnvkit.py segment -m flasso sample.cnr -o sample.segment.cns
    ...
    Traceback (most recent call last):
      File "/home/pcingola/tools/cnvkit/cnvkit.py", line 11, in <module>
        args.func(args)
      File "/home/pcingola/tools/cnvkit/cnvlib/commands.py", line 666, in _cmd_segment
        rlibpath=args.rlibpath)
      File "/home/pcingola/tools/cnvkit/cnvlib/segmentation/__init__.py", line 62, in do_segmentation
        segarr = squash_segments(segarr)
      File "/home/pcingola/tools/cnvkit/cnvlib/segmentation/__init__.py", line 160, in squash_segments
        if row['chromosome'] == curr_chrom and row['log2'] == curr_val:
    TypeError: tuple indices must be integers, not str

**Comment by etal** [comment]
Hi Pablo, thanks for catching this. I do have a unit test for `flasso` in `test_r.py`, but the R dependency makes it hard to run on TravisCI and I guess I haven't run it manually in a while.
