### ISSUE TITLE
Unable to use fix without antitarget file for WGS samples

### ISSUE THREAD

**Issue by GACGAMA** [etal/cnvkit#894]
Hello

This is related to  #242 

It seems like the newest version contains some old bugs for some reason

When trying to generate .cnr files with fix command without antitarget for whole-genomes:

`cnvkit.py fix /scratch4/nsobrei2/ggama1/somatic_SVs/cnvkit/call_genomes/BH10027_1_TUMOR.targetcoverage.cnn  /scratch4/nsobrei2/ggama1/somatic_SVs/cnvkit/needed_files/genomes_reference.cnn -o /scratch4/nsobrei2/ggama1/somatic_SVs/cnvkit/call_genomes/BH10027_1_TUMOR.cnr`

I get:
cnvkit.py fix: error: the following arguments are required: reference

If I create a decoy empty file antitarget, as proposed on older version, I get:

```
Blank tab file?: /scratch4/nsobrei2/ggama1/somatic_SVs/cnvkit/call_genomes/BH10027_1_TUMOR.antitargetcoverage.cnn
Processing target: BH10027_1_TUMOR
Traceback (most recent call last):
  File "/home/ggama1/.conda/envs/cnvkit/bin/cnvkit.py", line 10, in <module>
    sys.exit(main())
  File "/home/ggama1/.conda/envs/cnvkit/lib/python3.10/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/home/ggama1/.conda/envs/cnvkit/lib/python3.10/site-packages/cnvlib/commands.py", line 939, in _cmd_fix
    target_table = fix.do_fix(
  File "/home/ggama1/.conda/envs/cnvkit/lib/python3.10/site-packages/cnvlib/fix.py", line 24, in do_fix
    cnarr, ref_matched = load_adjust_coverages(
  File "/home/ggama1/.conda/envs/cnvkit/lib/python3.10/site-packages/cnvlib/fix.py", line 108, in load_adjust_coverages
    ref_matched = match_ref_to_sample(ref_cnarr, cnarr)
  File "/home/ggama1/.conda/envs/cnvkit/lib/python3.10/site-packages/cnvlib/fix.py", line 203, in match_ref_to_sample
    raise ValueError(
ValueError: Reference is missing 199 bins found in BH10027_1_TUMOR
```

When processing with batch, using the same reference, everything works fine.

**Comment by etal** [comment]
Sorry, sounds annoying. Let me see what I can do. Does it still behave that way?
