### ISSUE TITLE
Segmentation while running pipeline

### ISSUE THREAD

**Issue by NIBIL401** [etal/cnvkit#895]
Hi,
While running the CNVkit pipeline the coordinates from the cns file is merged to the final file. Can we not merge the coordinates? and keep it as it is and parse it to the final file. I cannot get the exact CNV because of merging the final "call.cns" file.  Is there any option not to merge the adjacent coordinates together? The merging is reducing the accuracy of the actual CNV. Please let me know if anything can be done to this. 

Thanks.

**Comment by bounlu** [comment]
I have the same issue that `.cns` file is not generated and no error is thrown when using `batch` command.

However, when I run `segment` function separately, it gives the below error:

```
# cnvkit.py segment -o my_sample.cns my_sample.cnr
Segmenting with method 'cbs', significance threshold 0.0001, in 1 processes
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cnvlib/core.py", line 23, in call_quiet
    proc = subprocess.run(args, check=True, capture_output=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('Rscript', '--no-restore', '--no-environ', '/tmp/tmpl21bppqx')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/cnvlib/commands.py", line 1022, in _cmd_segment
    results = segmentation.do_segmentation(
  File "/usr/local/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 81, in do_segmentation
    rets = list(
  File "/usr/local/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 126, in _ds
    return _do_segmentation(*args)
  File "/usr/local/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 209, in _do_segmentation
    seg_out = core.call_quiet(
  File "/usr/local/lib/python3.10/site-packages/cnvlib/core.py", line 30, in call_quiet
    raise RuntimeError(
RuntimeError: Subprocess command failed:
$ Rscript --no-restore --no-environ /tmp/tmpl21bppqx

Command '('Rscript', '--no-restore', '--no-environ', '/tmp/tmpl21bppqx')' returned non-zero exit status 1.
```

I am using the Docker image:

`quay.io/biocontainers/cnvkit:0.9.11--pyhdfd78af_0`

**Comment by etal** [comment]
There should be a plain .cns file in the output of batch, too, which the pipeline computes before merging bogus segments. Let me know if you're not seeing it.

The merging problem is addressed in the recent PR #1006 .
