### ISSUE TITLE
CNVkit segment command RuntimeError: Subprocess command failed

### ISSUE THREAD

**Issue by tanbiswas** [etal/cnvkit#901]
I am using CNVkit to call somatic CNAs from tumor-normal paired WES data. The BAM files were generated using GATK pipeline and the somatic VCF file was called using Mutect2 pipeline. However, I am getting the following error while running cnvkit segmentation command. 

(cnvkit) iit@lab:/P03-TD$ cnvkit.py segment P03-TD.cnr -o P03-TD.cns -m cbs --smooth-cbs --vcf P03.somatic.vcf --sample-id P03-TD --normal-id P03-BD --min-variant-depth 10 
Selected test sample P03-TD and control sample P03-BD
Loaded 3536 records; skipped: 0 somatic, 9 depth
VCF normal sample's genotypes are all 0/0 or missing; inferring genotypes from allele frequency instead
Skipping 99 additional somatic records based on T/N genotypes
Kept 31 heterozygous of 3437 VCF records
Segmenting with method 'cbs', significance threshold 0.0001, in 1 processes
Re-segmenting on variant allele frequency
.
.
Re-segmenting on variant allele frequency
Traceback (most recent call last):
  File "/home/iit/miniconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/core.py", line 23, in call_quiet
    proc = subprocess.run(args, check=True, capture_output=True)
  File "/home/iit/miniconda3/envs/cnvkit/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('Rscript', '--no-restore', '--no-environ', '/tmp/tmpgodv9oax')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/iit/miniconda3/envs/cnvkit/bin/cnvkit.py", line 10, in <module>
    sys.exit(main())
  File "/home/iit/miniconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/home/iit/miniconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/commands.py", line 1022, in _cmd_segment
    results = segmentation.do_segmentation(
  File "/home/iit/miniconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 81, in do_segmentation
    rets = list(
  File "/home/iit/miniconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 126, in _ds
    return _do_segmentation(*args)
  File "/home/iit/miniconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/segmentation/__init__.py", line 209, in _do_segmentation
    seg_out = core.call_quiet(
  File "/home/iit/miniconda3/envs/cnvkit/lib/python3.10/site-packages/cnvlib/core.py", line 30, in call_quiet
    raise RuntimeError(
RuntimeError: Subprocess command failed:
$ Rscript --no-restore --no-environ /tmp/tmpgodv9oax

Command '('Rscript', '--no-restore', '--no-environ', '/tmp/tmpgodv9oax')' returned non-zero exit status 1.
(cnvkit) iit@lab:P03-TD$ 

I have tried many ways but still getting this error. R package 'DNACopy' is successfully installed in my system. 

Please let me know how to solve this!

**Comment by bounlu** [comment]
Everybody gets the same error and this is still not solved: https://github.com/nf-core/sarek/issues/1625

**Comment by etal** [comment]
In P03-TD.cnr, is the weight column empty, or does it have some empty cells along with numeric values?

**Comment by etal** [comment]
Related: #436

**Comment by etal** [comment]
I merged a possible fix in #914. Could you try pulling the latest development version and see if the problem is fixed now?

**Comment by jezkoski** [comment]
I have the same issue and I'm using the latest version from github (0.9.12).

**Comment by haien2002** [comment]
same error report , same no idea
Kick me if solve the problem plz

**Comment by sjy0907** [comment]
Hello, in my .cnr file, there are no null values at all, but I still have the same issue. I'm using the latest version from github (0.9.12).  May I ask how to solve this problem? Thank you. @etal 

cnvkit.py segment 3056_T.mk.cnr -o 3056_T.mk.cns
Segmenting with method 'cbs', significance threshold 0.0001, in 1 processes
Traceback (most recent call last):
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/core.py", line 23, in call_quiet
    proc = subprocess.run(args, check=True, capture_output=True)
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('Rscript', '--no-restore', '--no-environ', '/tmp/tmpb0eg1kci')' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/bin/cnvkit.py", line 10, in <module>
    sys.exit(main())
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/cnvkit.py", line 10, in main
    args.func(args)
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/commands.py", line 1022, in _cmd_segment
    results = segmentation.do_segmentation(
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/segmentation/__init__.py", line 81, in do_segmentation
    rets = list(
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/segmentation/__init__.py", line 126, in _ds
    return _do_segmentation(*args)
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/segmentation/__init__.py", line 209, in _do_segmentation
    seg_out = core.call_quiet(
  File "/disks/node2_RAID6_120TB/gongmeiyuan/miniconda3/envs/cnvkit/lib/python3.9/site-packages/cnvlib/core.py", line 30, in call_quiet
    raise RuntimeError(
RuntimeError: Subprocess command failed:
$ Rscript --no-restore --no-environ /tmp/tmpb0eg1kci
