### ISSUE TITLE
targeted DNA seq

### ISSUE THREAD

**Issue by MaryGoAround** [etal/cnvkit#908]
I have a single tumour and I done targeted DNA seq but cnvkit gets this error permanently 

```
cnvkit.py heatmap converted.cns -d
Traceback (most recent call last):
  File "/camp/apps/eb/software/cnvkit/0.9.5-foss-2016b-Python-2.7.12/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.9.5', 'cnvkit.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1511, in run_script
  File "/camp/apps/eb/software/cnvkit/0.9.5-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/CNVkit-0.9.5-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 13, in <module>
    
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 999, in _cmd_heatmap
    
  File "build/bdist.linux-x86_64/egg/cnvlib/cmdutil.py", line 52, in verify_sample_sex
  File "build/bdist.linux-x86_64/egg/cnvlib/cnary.py", line 269, in guess_xx
  File "build/bdist.linux-x86_64/egg/cnvlib/cnary.py", line 385, in compare_sex_chromosomes
  File "build/bdist.linux-x86_64/egg/cnvlib/segmetrics.py", line 192, in segment_mean
  File "/camp/apps/eb/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/lib/function_base.py", line 959, in average
    "Weights sum to zero, can't be normalized")
ZeroDivisionError: Weights sum to zero, can't be normalized
```

I have tried this as wel but I get the same error 

`cnvkit.py segment converted.cnr --drop-low-coverage -o stricter_segmented.cns`

Thanks for any suggestion

**Comment by etal** [comment]
Looks like the same issue as #436

Could you try the development version from GitHub and see if that works for you? Alternatively, you could remove the rows in your .cnr file that have empty or null values, which seemed to be the immediate source of the errors reported previously.
