### ISSUE TITLE
Keeping 0 of 2851008 bins - Error- need at least one array to concatenate

### ISSUE THREAD

**Issue by wjaratlerdsiri** [etal/cnvkit#98]
Hello,

I ran with the following command in one of the samples:

python2.7 cnvkit.py batch PT.bam -n BLD.bam --rlibpath /home/r/R/x86_64-unknown-linux-gnu-library/3.1 --fasta hg19_chromosome.fa --targets access-5k-mappable.hg19.bed --antitargets empty.bed --access access-5k-mappable.hg19.bed --split -p 1 --annotate refFlat.hg19.txt --target-avg-size 1000 --output-reference UP_hg19_reference.update.cnn -y --output-dir cnvkit3_update/

I got only a header in the sample.cnr file with the error below:

Processing reads in PT.bam
Time: 56937.810 seconds (28048 reads/sec, 50 bins/sec)
Summary: #bins=2851008, #reads=1597018947, mean=560.1594, min=0.0, max=620598.51
Percent reads in regions: 107.742 (of 1482262140 mapped)
Wrote PT.targetcoverage.cnn
Skip processing PT.bam with empty regions file empty.bed
Wrote PT.antitargetcoverage.cnn
Processing target: PT
Keeping 0 of 2851008 bins
WARNING: most bins have no or very low coverage; check that the right BED file was used
Processing antitarget: PT
Wrote PT.cnr
Segmenting PT.cnr ...
Traceback (most recent call last):
  File "cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.7.10', 'cnvkit.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1659, in run_script
  File "/share/ScratchGeneral/weejar/bcbiometasv/miniconda/lib/python2.7/site-packages/CNVkit-0.7.10-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 11, in <module>

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 118, in _cmd_batch

  File "build/bdist.linux-x86_64/egg/cnvlib/parallel.py", line 14, in apply_async
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 216, in batch_run_sample

  File "build/bdist.linux-x86_64/egg/cnvlib/segmentation/__init__.py", line 28, in do_segmentation
  File "build/bdist.linux-x86_64/egg/cnvlib/segmentation/__init__.py", line 99, in drop_outliers
ValueError: need at least one array to concatenate

I used to run this sample without '--target-avg-size 1000' and worked okay. So, now I have rerun without a specific bin size. Should I do anything else to fix this? My tumour bam is around 45x and 30x Blood BAM. Thankyou

James

**Comment by etal** [comment]
So, you upgraded CNVkit from a previous version to the current v0.7.10, and the WGS pipeline is failing now. Are you saying the current version works for you if you run the command without `--target-avg-size 1000`, but fails if you add `--target-avg-size 1000`?

Can you look inside the file "PT.targetcoverage.cnn" and see if the values in the column "log2" are all `-20`, a similarly low negative number, or close to 0? If it's unclear, could you post the first few lines of that file here?

**Comment by wjaratlerdsiri** [comment]
Sorry I was not clear. Now I used v0.7.10. I rerun again with --target-avg-size 200, but still get the same result below. It may be because there is something wrong with my sample. Other samples so far with hg38 do not have these errors.

Keeping 0 of 14254988 bins
WARNING: most bins have no or very low coverage; check that the right BED file was used
Processing antitarget: UP2153_PT
Wrote cnvkitUP2153_update.200/UP2153_PT.cnr
Segmenting cnvkitUP2153_update.200/UP2153_PT.cnr ...
Traceback (most recent call last):
  File "cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.7.10', 'cnvkit.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1659, in run_script
  File "/share/ScratchGeneral/weejar/bcbiometasv/miniconda/lib/python2.7/site-packages/CNVkit-0.7.10-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 11, in <module>
    
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 118, in _cmd_batch
    
  File "build/bdist.linux-x86_64/egg/cnvlib/parallel.py", line 14, in apply_async
  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 216, in batch_run_sample
    
  File "build/bdist.linux-x86_64/egg/cnvlib/segmentation/__init__.py", line 28, in do_segmentation
  File "build/bdist.linux-x86_64/egg/cnvlib/segmentation/__init__.py", line 99, in drop_outliers
ValueError: need at least one array to concatenate


Here is "PT.targetcoverage.cnn":

chromosome	start	end	gene	log2
chr1	10000	10200	DDX11L1	9.34466
chr1	10200	10400	DDX11L1	8.92417
chr1	10400	10600	DDX11L1	7.69533
chr1	10600	10800	DDX11L1	3.16912
chr1	10800	11000	DDX11L1	4.40837
chr1	11000	11200	DDX11L1	5.71795
chr1	11200	11400	DDX11L1	6.32724
chr1	11400	11600	DDX11L1	6.55113
chr1	11600	11800	DDX11L1	7.36571
chr1	11800	12000	DDX11L1	7.37539

However, I used to run this sample with v0.7.5 and generated the following PT.targetcoverage.cnn. Note I intentionally removed the first 2 bins out to make the program run without warning about empty antitargetcoverage.cnn file.

chromosome      start   end     gene    log2
chr1    227417  227683  -       6.16887
chr1    227683  227950  -       6.35201
chr1    227950  228217  -       6.94295
chr1    228217  228484  -       7.06843
...
chr1    266918  267185  -       6.45667
chr1    267185  267452  -       5.65033
chr1    267452  267719  -       4.92657
chr1    317719  317985  LOC100132062    4.92646
chr1    317985  318252  LOC100132062    5.73838
chr1    318252  318519  LOC100132062    5.82995
chr1    318519  318786  LOC100132062    6.30958
chr1    318786  319052  LOC100132062    6.32064

With the PT.targetcoverage.cnn above, I ran successfully and got the following cns file:

chromosome	start	end	gene	log2	probes	weight
chr1	10500	227950	-	0.0721705	4	2.19118
chr1	228217	238093	-	0.979006	27	4.08134
chr1	238359	258110	-	0.571911	63	13.2869
chr1	258110	383873	LOC100132062	0.116023	196	47.3444
chr1	384140	524027	LOC100132062,LOC101928626	0.324204	228	55.5892
chr1	524027	837290	LOC101928626,OR4F16	0.179237	844	203.033
chr1	837290	1010881	OR4F16	0.0570952	582	145.004
chr1	1010881	1014081	OR4F16	-0.5082	12	1.88716
chr1	1014081	1567919	OR4F16	0.0549989	1732	432.78

Can you catch anything wrong? or I should use the result from the old version for now. Thankyou for this great program anyway.

James

**Comment by wjaratlerdsiri** [comment]
Sorry for my mess, I think my Normal.bam was corrupted. I checked it with md5sum.

James
